### ISSUE TITLE
Unable to use NONE authorization method with AWS_IAM default authorizer

### ISSUE THREAD

**Issue by TDaglis** [awslabs/serverless-application-model#1014]
**Description:**

It is not possible to create an API with just AWS_IAM authorizer and add a public route to it. Adding any other authorizer to the API, even an unused one, fixes the issue, but it's hacky. The source of the issue is probably not taking into account that the AWS_IAM authorizer is declared only as a default authorizer and not listed in the `Authorizers` dictionary.

**Steps to reproduce the issue:**
1. Create a sam template with an API with AWS_IAM default authorizer.
2. Create 2 endpoints
3. In one endpoint, add `Authorizer: "NONE"` as the method authorizer.
4. Try to deploy the template

Example sam template:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test API

Globals:
  Function:
    Runtime: python3.6
    Timeout: 600
    MemorySize: 1024

Resources:
  myapi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: v1
      Auth:
        DefaultAuthorizer: AWS_IAM

  private:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: test.lambda_handler
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /private
            Method: get
            RestApiId: !Ref myapi

  public:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: test.lambda_handler
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /public
            Method: get
            RestApiId: !Ref myapi
            Auth:
                Authorizer: "NONE"
```
**Observed result:**

Deployment fails with the following message:
```Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found:1. Resource with id [public] is invalid. Event with id [GetEvent] is invalid. Unable to set Authorizer [NONE] on API method [get] forpath [/public] because the related API does not define any Authorizers.```

**Expected result:**

Deployment succeeds with the `/private` resource having AWS_IAM authorizer and the `/public` route having no authorizer.
