### ISSUE TITLE
DataTraceEnabled: false does not disable APIGW Log full requests/responses data

### ISSUE THREAD

**Issue by lmunro** [awslabs/serverless-application-model#1016]
The Serverless::Api resource does not disable logging of full requests/responses data when 
DataTraceEnabled: false

To reproduce.

Deploy APIGW with logging of full requests/responses data enabled
```MyApi:
        Type: AWS::Serverless::Api
        Properties:
            MethodSettings:
            - LoggingLevel: INFO
            MetricsEnabled: true
            ResourcePath: "/*"
            HttpMethod: "*"
            DataTraceEnabled: true
```

then try to disable 

```MyApi:
        Type: AWS::Serverless::Api
        Properties:
            MethodSettings:
            - LoggingLevel: INFO
            MetricsEnabled: true
            ResourcePath: "/*"
            HttpMethod: "*"
            DataTraceEnabled: false
```

**Observed result:**
logging of full requests/responses data is still enabled

**Expected result:**
logging of full requests/responses should be disabled

This logging setting is a security sensitive as it will log all post data unencrypted in cloudwatch,  so it's important to explicitly ensure it's disabled in some use cases.

**Comment by keetonian** [comment]
@lmunro Just for clarification, are all of the properties that you're using in the above example supposed to be nested under `MethodSettings`? The other properties you're using there aren't supported as top-level properties for a Serverless::Api

**Comment by praneetap** [comment]
This looks like an indentation issue. MethodSettings should be formatted like this -
```yaml
        Type: AWS::Serverless::Api
        Properties:
            MethodSettings:
            - LoggingLevel: INFO
              MetricsEnabled: true
              ResourcePath: "/*"
              HttpMethod: "*"
              DataTraceEnabled: false
```
You may also consider running [cfn-lint](https://github.com/aws-cloudformation/cfn-python-lint) on the template.
