### ISSUE TITLE
AWS::SES::ReceiptRule: fails when LambdaAction is specified

### ISSUE THREAD

**Issue by dmccaffery** [awslabs/serverless-application-model#1021]
When using SAM to create a ReceiptRule resource, the resource fails to create despite a valid permission within the same template with the following error:

(Service: AmazonSimpleEmailService; Status Code: 400; Error Code: InvalidLambdaFunction; Request ID: X)

This would indicate that the function ARN is invalid or the permissions required are not specified. Even after creating the rule in the AWS Console, which adds the permissions on its own if they are not already specified, the SAM deployment still fails. This works correctly if the rule is created in the console.

Steps to reproduce:

Use the following template:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  # function
  ReceiveFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: example-function
      Handler: handler.js
      Runtime: nodejs8.10

  # permission
  Permission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref Function
      Principal: ses.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  # ruleset
  RuleSet:
    Type: AWS::SES::ReceiptRuleSet
    Properties:
      RuleSetName: example-rule-set

  # rule
  Rule:
    Type: AWS::SES::ReceiptRule
    DependsOn:
      - Permission
    Properties:
      RuleSetName: !Ref RuleSet
      Rule:
        ScanEnabled: true
        Enabled: true
        Name: example-rule
        Recipients: test@example.com
        Actions:
          - LambdaAction:
              FunctionArn: !Ref Function
```

Expected:

SAM application to successfully deploy.

Actual:

(Service: AmazonSimpleEmailService; Status Code: 400; Error Code: InvalidLambdaFunction; Request ID: X)

**Comment by dmccaffery** [comment]
As a side note, the policy does exist on the function:

```json
{
    "Policy": "{\"Version\":\"2012-10-17\",\"Id\":\"default\",\"Statement\":[{\"Sid\":\"allowSesInvoke\",\"Effect\":\"Allow\",\"Principal\":{\"Service\":\"ses.amazonaws.com\"},\"Action\":\"lambda:InvokeFunction\",\"Resource\":\"arn:aws:lambda:us-west-2:X:function:example-function\",\"Condition\":{\"StringEquals\":{\"AWS:SourceAccount\":\"X\"}}}]}",
    "RevisionId": "X"
}
```

**Comment by praneetap** [comment]
Looks like the function name used throughout the template is incorrect.
```yaml
FunctionName: !Ref Function
```
should be 
```yaml
FunctionName: !Ref ReceiveFunction
```

The reason you are getting the error though is because to get the function arn you need to use GetAtt instead of Ref (which just returns the resource name)
```yaml
        Actions:
          - LambdaAction:
              FunctionArn: !Ref Function
```
should be

```yaml
        Actions:
          - LambdaAction:
              FunctionArn: !GetAtt ReceiveFunction.Arn
```
