### ISSUE TITLE
Sam Package translates AWS::Cognito::UserPoolClient ExplicitAuthFlows

### ISSUE THREAD

**Issue by belialboy** [awslabs/serverless-application-model#1030]
**Description:**

I have a template.yml which contains a `AWS::Cognito::UserPoolClient` which looks a bit like this:
``` yaml 
  MyCognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref MyCognitoUserPool
      ClientName: "UserPoolClient"
      GenerateSecret: false
      ExplicitAuthFlows:
      - ADMIN_NO_SRP_AUTH
```

When I parse this through the `sam package` this is translated into:

```yaml
  MyCognitoUserPoolClient:
    Properties:
      ClientName: UserPoolClient
      ExplicitAuthFlows: ADMIN_NO_SRP_AUTH
      GenerateSecret: false
      UserPoolId:
        Ref: MyCognitoUserPool
    Type: AWS::Cognito::UserPoolClient
```

Notice that the `ExplicitAuthFlows` property has gone from a List of Strings to a String. This fails CloudFormation parsing, and so it bawlks and so it rollsback.

**Steps to reproduce the issue:**
1. Have a template that contains a Cognito UserPoolClient resource, that has an ExplicitAuthFlow property set to a List of Strings. 
2. Have the single value of `ADMIN_NO_SRP_AUTH` as a value in this list.
3. Run sam package on your template
4. Review the compiled template to see that it's been translated poorly. 
5. Run the template through cloudformation, and see that it fails and rolls-back
6. Update the translated template inline so that it's a List of Strings again
7. Run the template through cloudformation again, and see that it succeeds.

**Observed result:**

```yaml
  MyCognitoUserPoolClient:
    Properties:
      ClientName: UserPoolClient
      ExplicitAuthFlows: ADMIN_NO_SRP_AUTH
      GenerateSecret: false
      UserPoolId:
        Ref: MyCognitoUserPool
    Type: AWS::Cognito::UserPoolClient
```

**Expected result:**
```yaml
  MyCognitoUserPoolClient:
    Properties:
      ClientName: UserPoolClient
      ExplicitAuthFlows: 
      - ADMIN_NO_SRP_AUTH
      GenerateSecret: false
      UserPoolId:
        Ref: MyCognitoUserPool
    Type: AWS::Cognito::UserPoolClient
```
