### ISSUE TITLE
sam build using wrong SSM parameter

### ISSUE THREAD

**Issue by chizou** [awslabs/serverless-application-model#1039]
I have the following template snippet:
```
Parameters:
  OrgFunctionsArn:
    Default: /layers/orgfunctions
    Description: SSM Name of the orgfunctions ARN
    Type: AWS::SSM::Parameter::Value<String>

  CfDeployer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/cf_deployer/
      Layers:
        - !Ref OrgFunctionsArn
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "sts:AssumeRole"
              Resource: "*"
      Timeout: 300
```
Running this: `sam build -b build -s $(pwd)`
Returns this error: `Error: /layers/orgfunctions is an Invalid Layer Arn.`

Interestingly, if I run `sam package`, it seems to work correctly.

```
$ sam --version
SAM CLI, version 0.18.0
```

**Comment by chizou** [comment]
I don't know if my use case is just bad or if there is something wrong with `sam build`, but I decided to try ditching the above method and using dynamic references and that also fails. With the following stanza:
```
  CfDeployer:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/cf_deployer/
      Layers: '{{resolve:ssm:/layers/orgfunctions:1}}'
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: "sts:AssumeRole"
              Resource: "*"
      Timeout: 300
```
I now get this error: `samcli.commands.validate.lib.exceptions.InvalidSamDocumentException: [InvalidResourceException('CfDeployer', "Type of property 'Layers' is invalid.")] ('CfDeployer', "Type of property 'Layers' is invalid.")`
