### ISSUE TITLE
Feature Request: Add support to specify a SNS topic that belongs to a different region

### ISSUE THREAD

**Issue by DaichiUeura** [awslabs/serverless-application-model#105]
Hello,

I tried to set a SNS topic existed in a different region as a trigger like below. However CloudFormation said "Invalid parameter: TopicArn". Is this a current limitation or something like that?

```
...
Parameters:
  EventTopicArn:
    Type: String
Resources:
  SampleProcessor:
    Type: 'AWS::Serverless::Function'
    Properties:
...
      Events:
        SampleSNS:
          Type: SNS
          Properties:
            Topic: !Ref EventTopicArn
...
```
