### ISSUE TITLE
Referencing an AWS::ApiGateway::Authorizer in DefaultAuthorizer settings

### ISSUE THREAD

**Issue by ronlut** [awslabs/serverless-application-model#1050]
**Description:**
I don't find an option to reference an already defined `AWS::ApiGateway::Authorizer` from the `DefaultAuthorizer` setting.
In addition, from what I understand, the authorizer must be declared in the `Auth-> Authorizers` part of `AWS::Serverless::Api` to be available to use.
Two questions:

1. Is it possible to set the `DefaultAuthorizer` to an existing authorizer, declared independently in the template?
2. If not, If I declare the authorizer in the `Auth-> Authorizers` section, can I reference it from `'AWS::ApiGateway::Method'` resources?

Example resources:
```
    CustomAuthorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        Name: "CustomAuthorizer"
        Type: "REQUEST"
        IdentitySource: "method.request.header.Cookie"
        AuthorizerResultTtlInSeconds: 300
        AuthorizerCredentials: !GetAtt ApiGatewayRole.Arn
        AuthorizerUri: SOMELONGLAMBDAURI
        RestApiId: !Ref ApiGateway

    RootResourceGET:
        Type: 'AWS::ApiGateway::Method'
        Properties:
            RestApiId: !Ref ApiGateway
            ResourceId: !GetAtt
                - ApiGateway
                - RootResourceId
            HttpMethod: GET
            AuthorizationType: CUSTOM
            AuthorizerId: !Ref CustomAuthorizer
            Integration:
                Type: AWS
                IntegrationHttpMethod: GET
                Uri: SOMES3URI
                Credentials: !GetAtt [ApiGatewayRole, Arn]
                PassthroughBehavior: WHEN_NO_MATCH
```
As you can see, the `Method` references the authorizer, and `AuthorizationType` can't be null. So it has to be set to either an `Authorizer` or to 'NONE' (I don't know what'll happen in that case)

Thanks.
