### ISSUE TITLE
Null ApplicationId in AWS::Serverless::Application fails with Internal Server Error

### ISSUE THREAD

**Issue by ylynn** [awslabs/serverless-application-model#1053]
**Description:**

Null ApplicationId in AWS::Serverless::Application fails with unhandled exception

Template:
```
Resources:
  Application:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: null
        SemanticVersion: 1.0.0
```
errorMessage=Internal Server Error: Parameter validation failed:
Invalid type for parameter ApplicationId, value: None, type: <type 'NoneType'>, valid types: <type 'basestring'>
