### ISSUE TITLE
Feature Request: ACM integration - apiGateway

### ISSUE THREAD

**Issue by balldarrens** [awslabs/serverless-application-model#106]
Looks like ACM can be integrated with API Gateway.  Are there any folks out there integrating this at this point?  Any examples in the pipeline?

**Comment by jolexa** [comment]
This integration was just released: https://aws.amazon.com/ru/about-aws/whats-new/2017/03/amazon-api-gateway-integrates-with-aws-certificate-manager-acm/

But I am also interested to know when SAM will support this fuctionality

**Comment by balldarrens** [comment]
I had originally meant 'can be' not 'can not be'.  I was pointed to this update this AM, and would really like to get this into the bigger picture.  How does this become a feature request? @sanathkr - via you possibly?

**Comment by jolexa** [comment]
@balldarrens hi there, just following up on this since it was closed without comment and I was following to watch for updates. Did you hear about the timeline for this feature request via another means?

**Comment by dinvlad** [comment]
The biggest problem at the moment is to create a 'Api DomainName' resource for Api Gateway through CFN. The problem is that you'd need to create it as a custom resource, but even that is not possible at the moment if you'd like to stay within Node.js 4.3 runtime, because it hasn't yet been updated to a newer version that supports the new API calls. You may be able to do it with Python though.

`AWS::ApiGateway::BasePathMapping` is created easily, but it has to have an explicit `DependsOn` for the 'Api DomainName' resource created above.

Another problem is that `AWS::Serverless::Api` does not 'export' its implicitly created `AWS::ApiGateway::Stage` resource, so you'd either have to use `AWS::ApiGateway::RestApi` directly (together with explicit `AWS::ApiGateway::Stage` and `AWS::ApiGateway::Deployment`), or rely on the undocumented `Stage` naming scheme and add `DependsOn` to `AWS::ApiGateway::BasePathMapping` for that, as described in #32.

All of the other resources are easily created through CFN, namely `AWS::CertificateManager::Certificate` and `AWS::Route53::RecordSet`.

So everything will soon be able to be done entirely through CFN, we mostly just need to wait for the Lambda runtime to be updated to the latest version.

**Comment by balldarrens** [comment]
There is a problem with AWS::CertificateManager::Certificate, in that it requests ACM certificate in the region in which for CFN executes and it also waits until the certificate is approved (manual process).  The integration of ACM into API Gateway currently is us-east-1 only - another problem.

**Comment by dinvlad** [comment]
That's interesting, indeed I was setting everything up in us-east-1 - so had fewer problems. In general though, isn't it best practice to create one stack per region anyway? I've always thought of that as integral to using `${AWS::Region}` and other features to (somewhat ironically) make CloudFormation templates more "portable".

Of course, the uneven rollout of features between regions by AWS breaks that benefit, but I've heard it's somewhat intentional - they make sure everything works smoothly in one region, then can move to the others (beside purely business factors, of course).

**Comment by jolexa** [comment]
Thanks for your help @balldarrens! -- I wanted to figure it out further so I wrote my own reference https://github.com/jolexa/aws-apigw-acm

**Comment by balldarrens** [comment]
@jolexa @dinvlad There are plenty of work arounds for the interim, lambdas that would generate the versions correctly, lambdas for aliasing etc....  

I would imagine that this is imminent w.r.t. this functionality.  I would hope that there is a full example included shortly that encompasses a CI/CD pipeline with Lambda (w/ versions/aliases), APIGateway (w/Staging that is pointing to lambda versions/aliases) , ACM (w/ basepath mapping) and Routing.  

I am pulling this together in CodePipeline/CodeBuild so it would be nice if SAM did this sort of thing (or most of it) in one template.

I'll reopen this and see if they can label it a feature request - although there are a lot of features in this thread that are missing.

**Comment by jolexa** [comment]
Agreed, our org puts it all into a deployment pipeline as well because the end-to-end solution is not there.

**Comment by dinvlad** [comment]
+1, it's be awesome if they supported versioning natively (i.e. keeping multiple versions of the same API without creating a stack for each one, etc.)

**Comment by christiansalazar** [comment]
Hi there. So, if i have a set of: Dynamo+Lambda+Cronjob currently running on Oregon and then i decide to have a ApiGateway with custom domain names....then...EVERYTHING should be moved to Ohio because the ACM issue is only supported in this region ? (or im missing something here).  Thank u.

**Comment by sanathkr** [comment]
Reg ACM integration, this can be implemented by hacking together SAM & Customer Lambda resources but it is not neat. I'd rather wait for a native API Gateway/CFN solution.

Reg Lambda versioning in SAM, yes this is another important feature we are working on. Taking a bit longer than expected to get the dev experience ironed out. Will keep you guys posted.

**Comment by sanathkr** [comment]
Let's use #41 to track function verisions & aliases support.

**Comment by dinvlad** [comment]
`AWS::ApiGateway::DomainName` has been released almost 2 weeks ago, however currently it seems to be experiencing `Internal Failure` when trying to reference its `DistributionDomainProperty`. Hopefully we'll be able to use it once the team fixes that.

**Comment by wjordan** [comment]
> Its happening! #248

(For reference, #248 is a 'Parent Tracking Issue' for a bunch of unrelated work items. The item related to this issue 'Custom Domains & ACM' is still unchecked, implying it still hasn't been complted yet, so I'll continue discussion here rather than pollute that parent issue with mixed conversation.)

Here's an example template that integrates a SAM stack with a custom HTTPS domain using ACM and Route53. It adds `DomainName`, `BasePathMapping` and `RecordSetGroup` resources, hooking up the default `Prod` stage of the `ServerlessRestApi` implicit API, referencing `CertificateArn` (e.g., `arn:aws:acm:us-east-1:[account]:certificate/[id]`, `DomainName` (e.g., `api.example.com`) and `HostedZoneName` (e.g., `example.com.`) as input Parameters.

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  CertificateArn:
    Type: String
  DomainName:
    Type: String
  HostedZoneName:
    Type: String
    AllowedPattern: '.*\.$'
    ConstraintDescription: Must end with trailing dot `.`
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        API:
          Type: Api
          [...etc...]
  APIDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: !Ref CertificateArn
      DomainName: !Ref DomainName
  APIBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref APIDomainName
      RestApiId: !Ref ServerlessRestApi
      Stage: Prod
  APIDomain:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          DNSName: !GetAtt APIDomainName.DistributionDomainName
          HostedZoneId: Z2FDTNDATAQYW2 # static ID for CloudFront aliases
Outputs:
  ApiUrl:
    Value: !Sub "https://${DomainName}"
```

For future SAM support, for the simple use-case it might be possible to wrap up these resources into a more user-friendly `CustomDomain` object appended to `Serverless::Function` or `Serverless::Api` resources, e.g.:

```yaml
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CustomDomain: # Creates implicit DomainName, BasePathMapping and RecordSetGroup resources
        CertificateArn: !Ref CertificateArn # Required
        DomainName: !Ref DomainName # Required
        # HostedZoneName not required; can be derived from provided DomainName
```
Of course, this makes lots of simplifying assumptions (the API is mapped to the root path of the subdomain, no other `RestApi`s share the same `DomainName`, the Route53 Hosted Zone and ACM certificate both exist, etc etc..), but I think it could still be interesting for the simple use-case.
