### ISSUE TITLE
Support for EventBridge / Custom Event Buses

### ISSUE THREAD

**Issue by brandonstevens** [awslabs/serverless-application-model#1067]
[Amazon EventBridge](https://aws.amazon.com/about-aws/whats-new/2019/07/introducing-amazon-eventbridge/) was announced. One aspect of the announcement was added support for custom event buses. Custom buses provide a clean way to isolate events for custom applications. We should be able to specific a custom bus as the source for triggering Lambda functions.

Example template:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  SlackNotify:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main.handler
      CodeUri: app/
      Runtime: python3.7
      Timeout: 5
      Events:
        AnyRequest:
          Type: CloudWatchEvent
          Properties:
            Bus: example-custom-bus
            Pattern:
              source:
                - example.test
```
