### ISSUE TITLE
Execution failed due to configuration error: Lambda was not able to access EC2's API using the Lambda Execution Role to set up the Lambda function

### ISSUE THREAD

**Issue by wes3985** [awslabs/serverless-application-model#1074]
I'm not sure if this is a bug or just a lack of 'complete' examples to template from in the docs. I am seeing the above error with AWS SAM CLI when deploying lambdas through cloud formation. The following yaml works:

```
Globals:
  Function:
    Timeout: 750
    VpcConfig:
      SecurityGroupIds: 
        - sg-xxxx
      SubnetIds: 
       - subnet-1
       - subnet-2
Resources:
   MyFunction:
     Type: AWS::Serverless::Function 
     Properties: 
        CodeUri: src/
        Handler: MyFunction.lambda_handler 
        Policies:
        - Statement:
            Sid: "ec2resources"
            Effect: Allow
            Action: 
              - "ec2:CreateNetworkInterface"
              - "ec2:AttachNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DetachNetworkInterface"
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeSubnets"
              - "ec2:DescribeVpcs"
            Resource:
              - "*"
```

The following throws the error even through the subnets and security groups are identical to those in the globals configuration:

```
        .......
        - Statement:
            Sid: "ec2resources"
            Effect: Allow
            Action: 
              - "ec2:CreateNetworkInterface"
              - "ec2:AttachNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - "ec2:DescribeNetworkInterfaces"
              - "ec2:DetachNetworkInterface"
              - "ec2:DescribeSecurityGroups"
              - "ec2:DescribeSubnets"
              - "ec2:DescribeVpcs"
            Resource:
              - "arn:aws:ec2:eu-west-1:acc:security-group/sg-xxxx"
              - "arn:aws:ec2:eu-west-1:acc:subnet/subnet-1"
              - "arn:aws:ec2:eu-west-1:acc:subnet/subnet-2"
              - "arn:aws:ec2:eu-west-1:acc:network-interface/*"
              - "arn:aws:ec2:eu-west-1:acc:vpc/vpc-xyz"
```

Is it possible I am missing a permission? Or a resource from the policy?
