### ISSUE TITLE
ManagedPolicy not updating its resources when redeploying stack

### ISSUE THREAD

**Issue by joshpeng** [awslabs/serverless-application-model#1078]
**Description:**

In my `AWS::Serverless::Function`, I am referencing a `AWS::IAM::ManagedPolicy` . The managed policy has a resource enabled via a `!Sub`. When I redeploy this stack after changing the parameter value, it doesn't actually update my managed policy in the changeset.

**Steps to reproduce the issue:**
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31 # allows for AWS SAM defined objects
Description: Sample ManagedPolicy not updating

Parameters:
  MyLambdaParam:
    Type: String
    Default: "some-endpoint-name"
    Description: SageMaker endpoint's name

...

  MyLambdaFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: mylambda/
      Handler: app.lambda_handler
      Runtime: python3.7
      FunctionName: !Sub "${AWS::StackName}-ODSP"
      Description: Transforms input and passes along to SageMaker for MyLambda
      Policies:
        - !Ref SageMakerInvokeEndpointPolicy

...

  SageMakerInvokeEndpointPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          -   Effect: "Allow"
              Action:
                - "sagemaker:InvokeEndpoint"
              Resource: 
                - !Sub "arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/${MyLambdaParam}"
```

**Observed result:**
Stack is deployed without updating the `SageMakerInvokeEndpointPolicy` with latest resource based on param.

**Expected result:**
Expected the `SageMakerInvokeEndpointPolicy` to have it's resources updated.
