### ISSUE TITLE
Function-specific environment variables get not merged with Globals

### ISSUE THREAD

**Issue by 39otrebla** [awslabs/serverless-application-model#1097]
**Description:**
As per the doc, it would seem that, for each function, properties defined in `Globals` are merged with the ones defined under `Function`, with the latter taking precedence over the former.

In our use case, we would like to globally define default CORS configuration (i.e. define them in  `Globals -> Environment  -> Variables`), and, eventually, override some of these configs under `Function`.

Though, it is not working as either:

-  `Globals` take precedence over `Function`-specific ones, or
- they actually don't get merged

**Steps to reproduce the issue:**
1) Define an env variable under `Globals`:

```yaml
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs10.x
    Handler: index.handler
    Environment:
      Variables:
        CORS: "true"
        CORS_HEADERS: "Authorization,Accept"
        CORS_METHOD: "HEAD,GET,POST"
        CORS_ORIGIN: "*"
```

2) Then override one or more of these for a specific `Function`:
```yaml
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/foo
      Environment:
        Variables:
          CORS_HEADERS: "Authorization,Accept,XC-Client-Version"
```

3) Run the Function.

**Observed result:**

```javascript
console.log(process.env.CORS_HEADERS);
// prints: Authorization,Accept
```

**Expected result:**

```javascript
console.log(process.env.CORS_HEADERS);
// prints: Authorization,Accept,XC-Client-Version
```

**Comment by keetonian** [comment]
@39otrebla this is by design. In our documentation, we list that [primitive values are replaced](https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst#primitive-values-are-replaced) when we merge global and resource properties.

**Comment by 39otrebla** [comment]
Did you read the issue?

The problem is indeed that function-specific primitive variables replacement is not working.

In my example, I’m getting the Global value for ‘CORS_HEADERS’.

**Comment by keetonian** [comment]
What do you mean by running the function? If you are invoking it locally, you need to pass in a file with the environment variables to have them available using the [`--env-vars` option](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-cli-command-reference-sam-local-invoke.html).

I ran this template locally to verify the output.

```yaml
Globals:
  Function:
    Timeout: 10
    Runtime: nodejs10.x
    Handler: index.handler
    Environment:
      Variables:
        CORS: "true"
        CORS_HEADERS: "Authorization,Accept"
        CORS_METHOD: "HEAD,GET,POST"
        CORS_ORIGIN: "*"
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        print('hi')
      Environment:
        Variables:
          CORS_HEADERS: "Authorization,Accept,XC-Client-Version"
```

The template transformed into the following, with the correct behavior observed in the environment variables.
```json
{
  "Resources": {
    "MyFunction": {
      "Type": "AWS::Lambda::Function", 
      "Properties": {
        "Code": {
          "ZipFile": "print('hi')\n"
        }, 
        "Tags": [
          {
            "Value": "SAM", 
            "Key": "lambda:createdBy"
          }
        ], 
        "Environment": {
          "Variables": {
            "CORS_ORIGIN": "*", 
            "CORS_HEADERS": "Authorization,Accept,XC-Client-Version", 
            "CORS_METHOD": "HEAD,GET,POST",
            "CORS": "true"
          }
        }, 
        "Handler": "index.handler", 
        "Role": {
          "Fn::GetAtt": [
            "MyFunctionRole", 
            "Arn"
          ]
        }, 
        "Timeout": 10, 
        "Runtime": "nodejs10.x"
      }
    }, 
    "MyFunctionRole": {
      "Type": "AWS::IAM::Role", 
      "Properties": {
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        ], 
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17", 
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ], 
              "Effect": "Allow", 
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ]
        }
      }
    }
  }
}
```
