### ISSUE TITLE
RFC: Combine Test and Prod permissions for Api Events

### ISSUE THREAD

**Issue by ShreyaGangishetty** [awslabs/serverless-application-model#1102]
**Issue Summary**
Currently, SAM creates two permissions (one for production and one for test) for every API event defined in the CloudFormation stack. The test permission is needed for the Test button to work on the console. Because of this extra permission for the test button, the limit of 200 resources per stack can be quickly reached. Related Issues: [#285](https://github.com/awslabs/serverless-application-model/issues/285), [#337](https://github.com/awslabs/serverless-application-model/issues/337)

**Design Spec**
The approach is to combine both permisions into a single permission and give the exact same functionality without a spec change. This is achieved by using a `"*"` in place of the stage name in the single permission, which is exactly what the "Test" permission does today.

Sample Template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        print("hello world") 
      Handler: app.lambda_handler
      Runtime: python3.6
      Events:
        HttpGetUserExample:
          Type: Api
          Properties:
            Path: '/users/userid'
            Method: GET
```
For this sample template, the resources generated by existing approach look like:

```json
    ...
    "HelloWorldFunctionHttpGetUserExamplePermissionProd": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:invokeFunction",
        "Principal": "apigateway.amazonaws.com",
        "FunctionName": {
          "Ref": "HelloWorldFunction"
        },
        "SourceArn": {
          "Fn::Sub": [
            "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/users/userid",
            {
              "__Stage__": "Prod",
              "__ApiId__": {
                "Ref": "ServerlessRestApi"
              }
            }
          ]
        }
      }
    },
    "HelloWorldFunctionHttpGetUserExamplePermissionTest": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:invokeFunction",
        "Principal": "apigateway.amazonaws.com",
        "FunctionName": {
          "Ref": "HelloWorldFunction"
        },
        "SourceArn": {
          "Fn::Sub": [
            "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/users/userid",
            {
              "__Stage__": "*",
              "__ApiId__": {
                "Ref": "ServerlessRestApi"
              }
            }
          ]
        }
      }
    },
    ...
```

With the proposed approach the resources generated would look like:

```json
    ...
    "HelloWorldFunctionHttpGetUserExamplePermissionProd": {
      "Type": "AWS::Lambda::Permission", 
      "Properties": {
        "Action": "lambda:invokeFunction", 
        "Principal": "apigateway.amazonaws.com", 
        "FunctionName": {
          "Ref": "HelloWorldFunction"
        }, 
        "SourceArn": {
          "Fn::Sub": [
            "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/GET/users/userid", 
            {
              "__Stage__": "*", 
              "__ApiId__": {
                "Ref": "ServerlessRestApi"
              }
            }
          ]
        }
      }
    },
    ...
```

This approach will reduce the number of permissions created for api events by half. This approach gives the same functionality as the existing approach without any change in the spec. Hence, it is backward compatible.
