### ISSUE TITLE
Feature Request: Add TableName to AWS::Serverless::SimpleTable

### ISSUE THREAD

**Issue by digitalfiz** [awslabs/serverless-application-model#112]
Not sure why this was omitted you can do it with the `AWS::DynamoDB::Table` resource type...

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html

**Comment by bjinwright** [comment]
TableName is set in the name of the resource instead of the properties. In the example below the table name is maintable.

```yaml
--- |
  AWSTemplateFormatVersion: '2010-09-09'
  Resources:
    maintable:
      Properties:
        PrimaryKey:
          Name: _id
          Type: String
      Type: AWS::Serverless::SimpleTable
    testpublish:
      Properties:
        CodeUri: s3://gungho/photoactions.zip
        Handler: s3resize.handler
        Runtime: python2.7
      Type: AWS::Serverless::Function
  Transform: AWS::Serverless-2016-10-31

```

**Comment by digitalfiz** [comment]
Part of the TableName comes from the resource name combined with the stack name and some random string. I am wanting to set the exact name of the table to match our companies conventions.

For example this template:

```yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Description: mytest
Resources:
  maintable:
    Properties:
      PrimaryKey:
        Name: _id
        Type: String
    Type: AWS::Serverless::SimpleTable
Transform: AWS::Serverless-2016-10-31
```

Followed by this command:

```sh
aws cloudformation deploy \
    --template-file sam_test.yml \
    --stack-name marctest \
    --capabilities CAPABILITY_NAMED_IAM
```

Will result in a table called `marctest-maintable-L3BF17IRFDSL`

I feel that it would be a good feature to allow some of the properties of the original types to be capable of being overridden. TableName being the one most important to me obviously but others might could benifit from making more if not all of the original properties overridable.
