### ISSUE TITLE
[Custom Domains][M1]Implement the base case

### ISSUE THREAD

**Issue by praneetap** [awslabs/serverless-application-model#1125]
## Related Issues
#783 
## Description 
This is a proposal to implement the base case of Custom Domains feature.
SAM input -
```yaml
  Type: AWS::Serverless::Api
  Properties:
    Domain:
      DomainName: example.com
      CertificateArn: !Ref CertificateARN 
```
This takes in a valid certificate ARN and creates a Regional endpoint mapping of the custom domain to the API basepath `/`. The CFN resources that are created are - 
```yaml
  APIDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      EndpointConfiguration:
        Types: [REGIONAL]
      RegionalCertificateArn: !Ref CertificateARN
      DomainName: !Ref DomainName

  APIBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref APIDomainName
      RestApiId: !Ref MyApi
      BasePath: /
      Stage: Prod
```
Apart from template creation, couple more in Acceptance Criteria : 
1. This must add base path and server fields to swagger/openapi doc. 
1. Also add this to the hash so that API GW redeploys if there is a change in base path or domain resources. (Since changing the base path does not update the swagger every time)
