### ISSUE TITLE
[Custom Domains][M1] Implement the Edge endpoint for CustomDomains

### ISSUE THREAD

**Issue by praneetap** [awslabs/serverless-application-model#1126]
## Related Issues
#783 
## Description 
This is a proposal to implement the handling EDGE endpoint for Custom Domains (with no Route53 support)
```yaml
  Type: AWS::Serverless::Api
  Properties:
    Domain:
      DomainName: example.com
      CertificateArn: !Ref CertificateARN
      EndpointConfiguration: EDGE 
```

The SAM generated resources that should change are -
```yaml
  APIDomainName:
    Type: 'AWS::ApiGateway::DomainName'
    Properties:
      EndpointConfiguration:
        Types: [EDGE]
      CertificateArn: !Ref CertificateARN
      DomainName: !Ref DomainName
```
