### ISSUE TITLE
[Custom Domains][M1] Implement multiple basepath mappings for single domain single api.

### ISSUE THREAD

**Issue by praneetap** [awslabs/serverless-application-model#1127]
## Related Issues
#783 
## Description 
This is a proposal to add Basepath mappings for Custom Domains usecase.

```yaml
  Type: AWS::Serverless::Api
  Properties:
    Domain:
      DomainName: example.com
      Certificate: !Ref CertificateARN 
      BasePath: [pathone, pathtwo] # '/' is no longer a valid basepath if you have multiple. They all map to Api.Stage.
```

SAM must create a `AWS::ApiGateway::BasePathMapping` resource per base path.
SAM must also add the basepath to the swagger.
