### ISSUE TITLE
[Custom Domains][M2] Support creating Route53 IpV6 records

### ISSUE THREAD

**Issue by praneetap** [awslabs/serverless-application-model#1129]
## Related Issues
#783 
## Description 
Milestone 2 targets adding Route53 support to Custom Domains feature. This task is to track adding Route 53 type AAAA records to a provided HostedZone by adding a IpV6 flag to SAM template.
SAM input
```yaml
  Type: AWS::Serverless::Api
  Properties:
    Domain:
      DomainName: example.com
      Certificate: !Ref MyApiSimpleDomainCertificate 
      EndpointConfiguration: REGIONAL # this is default, so same as not having this here
      Route53:
        EvaluateTargetHealth: true #false by default
        HostedZoneId: xyz # required, must be string
        IpV6: true # false by default
Distribution:
  Type: AWS::CloudFront::Distribution # Must have a cloudfront distribution set up
  ....
```
New Resource created should look like this -
```yaml
  DomainNameIpV6Route53RecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # (const value for cloudfront distributions)
          DNSName: !GetAtt Distribution.DomainName
      - Name: !Ref DomainName
        Type: AAAA
        AliasTarget:
          HostedZoneId: Z2FDTNDATAQYW2 # (const value for cloudfront distributions)
          DNSName: !GetAtt Distribution.DomainName
```
