### ISSUE TITLE
[Custom Domains][M3] Make API property `Domain` accept a list of objects

### ISSUE THREAD

**Issue by praneetap** [awslabs/serverless-application-model#1130]
## Related Issues
#783 
## Description 
Custom Domains Milestone 3 is to enable multiple domains to multiple Apis mapping. The task tracks adding multiple domains in SAM template.
```yaml
  Type: AWS::Serverless::Api
  Properties:
    Domain:
    - DomainName: example.com
      Certificate: !Ref MyApiExampleDomainCertificate 
    - DomainName: another.com
      Certificate: !Ref MyApiAnotherDomainCertificate 
      EndpointConfiguration: REGIONAL # this is default, so same as not having this here
```
Resources - Create a 'AWS::ApiGateway::DomainName' and `AWS::ApiGateway::BasePathMapping` for each domain name:api mapping.
