### ISSUE TITLE
[Custom Domains][M3] Enable adding basepath mappings in Domain property 

### ISSUE THREAD

**Issue by praneetap** [awslabs/serverless-application-model#1131]
## Related Issues
#783 
## Description 
Custom Domains Milestone 3 is to enable multiple domains to multiple Apis mapping. The task tracks adding specific basepath mappings.

SAM input
```yaml
  Type: AWS::Serverless::Api
  Properties:
    Domain:
    - DomainName: example.com
      Certificate: !Ref MyApiExampleDomainCertificate 
      BasePathMappings: 
          - BasePath: somepath # BasePath takes a string, or a list of strings. Required value. 
            Api: !Ref MyFirstApi  # Default: !Ref MyApiAdvancedDomain; use case: mapping this domain to additional APIs
            Stage: ''  # Default: {MyApi.Stage} Defaults to the current Api's stage
    - DomainName: another.com
      BasePathMappings:
          - BasePath: [anotherpath, andanother] 
            Api: !Ref MySecondApi  # Default: !Ref MyApiAdvancedDomain; use case: mapping this domain to additional APIs
            Stage: !Ref MySecondApi.Stage  # Default: {MyApi.Stage} Defaults to the current Api's stage
      Certificate: !Ref MyApiAnotherDomainCertificate 
      EndpointConfiguration: REGIONAL # this is default, so same as not having this here
```
