### ISSUE TITLE
RFC: Usage Plans for Auth

### ISSUE THREAD

**Issue by ShreyaGangishetty** [awslabs/serverless-application-model#1141]
**Resources**
[Api keys](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-setup-api-key-with-console.html), [create and use Api keys with Usage Plans](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-api-usage-plans.html), [Auth](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-controlling-access-to-apis.html)

**Associated Issues**
[#248](https://github.com/awslabs/serverless-application-model/issues/248), [#547](https://github.com/awslabs/serverless-application-model/issues/547)

**Description**
Api keys can be generated by creating a Usage Plan or by using existing Usage Plan.

The template for Usage plans in SAM would look like:
```yaml
  ...
      UsagePlan:  
        CreateUsagePlan: SHARED  # Accepted values: SHARED | NONE | SINGLE # Required field
        UsagePlanId: !Ref usageplanId # Optional field
  ...
```
* SAM creates three resources, `AWS::ApiGateway::ApiKey` with name `ServerlessApiKey`, `AWS::ApiGateway::UsagePlan` with name `ServerlessUsagePlan`, and `AWS::ApiGateway::UsagePlanKey` with name `ServerlessUsagePlanKey` for a stack when `CreateUsagePlan` is set to `SHARED` in Globals / Api.
* SAM creates three resources, `AWS::ApiGateway::ApiKey` with name `<ApiName>ApiKey`, `AWS::ApiGateway::UsagePlan` with name `<ApiName>UsagePlan`, and `AWS::ApiGateway::UsagePlanKey` with name `<ApiName>UsagePlanKey` for an Api when `CreateUsagePlan` is set to `SINGLE` in Globals / Api.
* SAM creates `AWS::ApiGateway::ApiKey` and `AWS::ApiGateway::UsagePlanKey` when `UsagePlanId` is given. SAM will not create/update `AWS::ApiGateway::UsagePlan` resource and expects `ApiStages` to be defined by the user seperately.

**Input to SAM**
```yaml
Globals:
  Api:
    Auth:
      ApiKeyRequired: true
      UsagePlan:
        CreateUsagePlan: SHARED

Resources:
  ...
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod

  MyDifferentApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
  ...
```
**CloudFormation Template generated by SAM for Usage Plans**
```yaml  
Globals:
  Api:
    Auth:
      ApiKeyRequired: true
      CreateUsagePlan: true

Resources:
  ...
  # resources created by SAM
  ServerlessApiKey: 
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - ServerlessUsagePlan
    Properties:
      Enabled: true

  ServerlessUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - MyApi
      - MyDifferentApi
    Properties:
      ApiStages:
        - ApiId: !Ref MyApi
          Stage: !Ref MyApi.Stage
        - ApiId: !Ref MyDifferentApi
          Stage: !Ref MyDifferentApi.Stage
 
  ServerlessUsagePlanKey: 
    Type: AWS::ApiGateway::UsagePlanKey
    Properties:
      KeyId: !Ref ServerlessApiKey
      UsagePlanId: !Ref ServerlessUsagePlan
      KeyType: API_KEY

Outputs:
  # Output added by SAM
  ServerlessKeyId:
    Description: "ID of the API Key"
    Value: !Ref ServerlessApiKey
```
