### ISSUE TITLE
Multiple API Gateways or Invoking lambdas ?

### ISSUE THREAD

**Issue by otherview** [awslabs/serverless-application-model#1148]
Hi guys! 

Really loving the stuff you're doing with SAM.

I'm trying to abstract away the repository logic for the business and API logic.
Wondering whats the best approach in this case ?

Which should I implement :
```
API -> Lambda API Functions -> Lambda Repo Functions -> Repo
```
or something like this (mainly Tier 1 and Tier 3)

![](https://i.stack.imgur.com/KsgMj.png)

I've tried without success using SDK-Lamba to invoke another lambda function.
Pretty sure my template.yml is incorrect, could anyone point me in the right direction ?

This is my template for case 1, where Users should call the Repo
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  derp-serverless

  SAM Template for derp-serverless

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5

Resources:
  UserFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: bin/
      Handler: getUser
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      Events:
        CatchAll:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /user/{userId+}
            Method: GET
          cors: true
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
  
  derpRepoFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: derpRepo
      Runtime: go1.x
      Tracing: Active # https://docs.aws.amazon.com/lambda/latest/dg/lambda-x-ray.html
      
Outputs:
  UserAPI:
    Description: "API Gateway endpoint URL for Prod environment for User"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/user/"

  UserFunction:
    Description: "User Lambda Function ARN"
    Value: !GetAtt UserFunction.Arn

  UserFunctionIamRole:
    Description: "Implicit IAM Role created for User function"
    Value: !GetAtt UserFunctionRole.Arn
```

**Comment by jlhood** [comment]
@otherview Yes, you can absolutely invoke a Lambda function from inside another Lambda function using the AWS SDK. I'm not sure exactly what issue you're running into trying to do this, but looking at your example template, it looks like you want `UserFunction` to be able to invoke `derpRepoFunction` directly. In order to do this, `UserFunction` needs to know the name of `derpRepoFunction`. You can pass this into `UserFunction` via environment variables.

Also, your `UserFunction` will need permissions to invoke `derpRepoFunction`. You can use [SAM policy templates](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-policy-templates.html) to add this permission.

All together, here are the changes you need:

```yaml
  UserFunction:
    Type: AWS::Serverless::Function 
    Properties:
...
      Policies:
        LambdaInvokePolicy:
          FunctionName: !GetAtt derpRepoFunction
      Environment:
        Variables:
          DERP_REPO_FUNCTION: !GetAtt derpRepoFunction
```

Then inside your code for `UserFunction`, you can pull the function name out of the DERP_REPO_FUNCTION environment variable (`os.Getenv("DERP_REPO_FUNCTION")`) and pass it to the Lambda Invoke API as the FunctionName parameter.

Hope this helps!
