### ISSUE TITLE
Set throttling and all of the other parameters supported by StageDescription

### ISSUE THREAD

**Issue by dinvlad** [awslabs/serverless-application-model#115]
Hi @sanathkr,

Would it be possible to specify all of the parameters for an Api deployment, e.g. per-stage (or even per-method) ThrottlingRateLimit etc.? `AWS::ApiGateway::Deployment` already supports that, but it doesn't update Stage when re-deploying the Api. So if we benefit from automatic redeployments by `AWS::Serverless::Api`, we have to sacrifice control over throttling etc. Would it be possible to enable full functionality for the latter?

EDIT: also, I don't really want to enable UsagePlans just so I could control throttling. That would require specifying an API key in addition to normal authentication parameters, which would increase burden on my clients.

Thanks!

**Comment by sanathkr** [comment]
Should be able to. So you want this to be a per-stage property?

**Comment by dinvlad** [comment]
At the very least, it'd be good to add it to the list of properties for `AWS::Serverless::Api`. If (when) we get support for multiple stages, that could be set on a per-stage level to handle use cases where e.g. we have several environments (currently, we just keep them in separate stacks, which is fine).

**Comment by rajanarkenbout** [comment]
Is there a ETA for this functionaliity. I would really like to use the throttling functionality in AWS::Serverless::Api

**Comment by jfuss** [comment]
We created a parent task to track this. Please see #248 for updates.

Closing as duplicate of #248

**Comment by liesislukas** [comment]
This works: 

```yaml
  SomeApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "SomeApi"
      Description: "Some api"
      StageName: production
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
          ThrottlingBurstLimit: 3
          ThrottlingRateLimit: 4
```

Take a look at StageName, i entered "production" whatever the name will be, that stage will be created and these limits applied to that stage

![image](https://user-images.githubusercontent.com/2733862/126875903-94141e47-5c68-4d68-b04a-aaf10e55dd06.png)
