### ISSUE TITLE
Global CORS AllowCredentials: true not setting header

### ISSUE THREAD

**Issue by peregrinius** [awslabs/serverless-application-model#1166]
**Description:**

I'm getting the following error even though I have applied the AllowCredentials: "true" setting to my config:

```
Access to XMLHttpRequest at 'http://localhost:3000/auth/token' from origin 'http://localhost:8080' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' which must be 'true' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.
```

**Steps to reproduce the issue:**

```
Globals:
  Api:
    Cors:
      AllowOrigin: "http://localhost:8080"
      AllowHeaders: "*"
      AllowCredentials: "true"
```

**Observed result:**

Changing AllowHeaders is reflected in the response to my request.

![image](https://user-images.githubusercontent.com/5101137/65839694-07b82000-e310-11e9-9a61-229f4a8529e4.png)

![image](https://user-images.githubusercontent.com/5101137/65839705-2a4a3900-e310-11e9-9fb6-b8236c31cc17.png)

**Expected result:**

No CORS Error :-D

**Comment by ShreyaGangishetty** [comment]
@peregrinius Could you try by removing the quotes for `AllowCredentials: true`. `AllowCredentials` expects a [boolean value](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cors-configuration)

Template:
```yaml
Globals:
  Api:
    Cors:
      AllowOrigin: "http://localhost:8080"
      AllowHeaders: "*"
      AllowCredentials: true
```

**Comment by peregrinius** [comment]
Thanks for your reply Shreya. I tried that but still the same error :-(

**Comment by keetonian** [comment]
Hi @peregrinius! It also looks like Cors expects quoted strings:

```yaml
Globals:
  Api:
    Cors:
      AllowOrigin: "'http://localhost:8080'"
      AllowHeaders: "'*'"
      AllowCredentials: true
```

https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#cors-configuration
