### ISSUE TITLE
Cloudformation does not respect given conditions on resources while creating change set

### ISSUE THREAD

**Issue by wimzyLive** [awslabs/serverless-application-model#1167]
Sorry for filing issue here, but I am not sure where to file this cloudformation related issue or may be documantation issue. Could someone please point me to correct repo.
### ISSUE: 
AWS Cloudformation does not respect given conditions on resources. Instead it tries to create resources anyway.

I want to deploy using same template to multiple aws partitions, where one of the partitions does not have resource available. Therefore, I put conditions on resource assuming that cloudformation will ignore resource creation whichever does not meet given condition, but this is not the case.

i.e.:
mystack.yml
```yml
Conditions:
  IsInternational: !Equals
    - !Ref 'AWS::Partition'
    - 'aws'
  IsChinaMainland: !Equals
    - !Ref 'AWS::Partition'
    - 'aws-cn'

Resources:
  ApplicationS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketName: 'my-unique-bucket-name
  CodeRepo:
    Type: AWS::CodeCommit::Repository
    Condition: IsInternational
    Properties:
      RepositoryName: some-unique-repo-name
      RepositoryDescription: This is my repo for doing x.
```

The above template will successfully deploy to AWS international account since `AWS::CodeCommit::Repository` does exit in AWS international. 
However, it will not work since AWS China doesn't have support for `AWS::CodeCommit::Repository` yet.
From looking at above template it looks valid and if conditions were taken into account template should successfully deploy to both AWS International and AWS China.

Does anyone know if this is the desired behaviour and if not, should it be documented somewhere in Docs.
