### ISSUE TITLE
AWS::Serverless::Api - Auth property doesn't allow intrinsic functions?

### ISSUE THREAD

**Issue by beatleboy501** [awslabs/serverless-application-model#1184]
I am currently deploying an API to multiple environments (prod, test, dev). I would like to turn off "Auth" in dev so we can focus on developing post-login features in that environment. However it is not possible to conditionally add the "Auth" property to my Api resource because of how we are validating:

https://github.com/awslabs/serverless-application-model/blob/4fa5d6a4ec60e82681daae6f0ff9d7669642c266/samtranslator/model/api/api_generator.py#L312

Therefore something like this is not possible currently:

```
Api:
  Type: AWS::Serverless::Api
  Properties:
    ...
    Auth:
      Fn::If:
        - IsDev
        - !Ref "AWS::NoValue"
        - DefaultAuthorizer: CognitoAuthorizer
          Authorizers:
            CognitoAuthorizer:
              UserPoolArn: !GetAtt UserPool.Arn
              Identity:
                Header: Authorization
                ValidationExpression: "." 
```

**Comment by praneetap** [comment]
@beatleboy501 This should be resolved in a pr https://github.com/awslabs/serverless-application-model/pull/1179 going out in v1.16 release.

**Comment by cantwelc** [comment]
The intrinsic mapping for API was not added in v1.16 or v1.20.0 from what I can see. I can see intrisic mapping for function deployment preferences (https://github.com/awslabs/serverless-application-model/pull/1196)

**Comment by dbourdin** [comment]
Is there any workaround to this issue? I'm trying to do the same thing @beatleboy501 mentioned but without any luck.
I've tried setting the default authorizer to "AWS::NoValue" if it's dev environment, but it throws an error saying DefaultAuthorizer is not a string
```
  Api:
    Type: AWS::Serverless::Api
    Properties:
      ...
      Auth:
        DefaultAuthorizer: !If [IsDevEnv, !Ref "AWS::NoValue", CognitoAuth]
        Authorizers:
          CognitoAuth:
            UserPoolArn: !GetAtt MyCognitoUserPool.Arn
            Identity:
              Header: Authorization
```

I've also tried the approach mentioned above but it says it's an invalid value for 'Auth' property.

I've also tried using different API resources, and using a conditional within my Function in RestApiId property. I've seen this approach in [this stackoverflow post](https://stackoverflow.com/questions/60178155/when-creating-multiple-api-gateway-instances-in-template-yaml-how-do-you-contro). Unfortunately, this is not working either and I'm still stuck with this issue.
