### ISSUE TITLE
Request Model mapping does not work 

### ISSUE THREAD

**Issue by abhinav-jain09** [awslabs/serverless-application-model#1193]
**Description:**
I tried very hard to map the request model to the java based POJO  but it does not work . 
I am getting null for the POJO fields 

**Steps to reproduce the issue:**
1. Create hello world function 
2.define handler as follows 
```
public class App  implements RequestHandler<RequestClass,Object> {

    public Object handleRequest(RequestClass input, Context context) {

        Map<String, String> headers = new HashMap<>();
        headers.put("Content-Type", "application/json");
        headers.put("X-Custom-Header", "application/json");
***this value is always null****
    System.out.println(input.getTest());
        try {
            final String pageContents = this.getPageContents("https://checkip.amazonaws.com");
            String output = String.format(input.toString(), pageContents);
            return new GatewayResponse(output, headers, 200);
        } catch (IOException e) {
            return new GatewayResponse("{}", headers, 500);
        }
    }

    private String getPageContents(String address) throws IOException{
        URL url = new URL(address);
        try(BufferedReader br = new BufferedReader(new InputStreamReader(url.openStream()))) {
            return br.lines().collect(Collectors.joining(System.lineSeparator()));
        }
    }
}
```

request class as follows 

```
public class RequestClass {
    public String test;

    public String getTest() {
        return test;
    }

    public void setTest(String test) {
        this.test = test;
    }

    @Override
    public String toString() {
        return "HelloWorld{" +
                "test='" + test + '\'' +
                '}';
    }

    public RequestClass() {
    }
}
```
3. Tenplate as follows 

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-app

  Sample SAM Template for sam-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 20

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: HelloWorldFunction
      Handler: helloworld.App::handleRequest
      Runtime: java8
      MemorySize: 1024
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          PARAM1: VALUE
      Events:
        HelloWorld:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties: 
            Path: /{proxy+}
            Method: POST
            RestApiId: !Ref HelloWorldApi
            RequestModel: 
              Model: RequestClass # REQUIRED; must match the name of a model defined in the Models property of the AWS::Serverless::API
              Required: true # OPTIONAL; boolean
             
               
  HelloWorldApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName : dev
        Models:
         RequestClass : 
          type: object
          properties:
            test:
             type: string
            
   
Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  HelloWorldApi:
    Description: "API Gateway endpoint URL for Prod stage for Hello World function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  HelloWorldFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt HelloWorldFunction.Arn
  HelloWorldFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt HelloWorldFunctionRole.Arn
```

Input given by postman  after sam local start-api

{
"test":"hello"
}

**Observed result:**
The result is always null for the print statement in the program  value
**Expected result:**

The print statement should print hello

It should print the value
