### ISSUE TITLE
Create function that can call itself

### ISSUE THREAD

**Issue by ingomueller-net** [awslabs/serverless-application-model#1204]
**Description:**

I *think* it is currently not possible to create a function that it allowed to call itself. I am trying to achieve this with the following template.

```yaml
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: aws_lambda
      Handler: handler.run
      Runtime: python3.7
      MemorySize: 2048
      Policies:
        - LambdaInvokePolicy:
            FunctionName: !Ref MyFunction
```

This fails with the following message:

```
FAILED. Reason: Circular dependency between resources: [MyFunction, MyFunctionRole]
```

It looks to me like I cannot break this circular dependency. The function needs to know which role it should be created with and role defines the policy, which needs to know what function it refers to.

I'd be glad to hear that there is a way to do it currently. Otherwise, this would be a great feature to add.

**Comment by keetonian** [comment]
To avoid the circular dependency issue, you will need to pass in the actual name of the function to the `FunctionName` parameter of `LambdaInvokePolicy`. There are two ways of doing this:

1. You can add a name to the function in the `FunctionName` parameter of the `Serverless::Function` resource and pass the same name into the `FunctionName` parameter of the `LambdaInvokePolicy` policy template.
1. You can deploy the function without the policy, copy the physical id of the function, then put the policy back in the template with the actual name of the function (without using `!Ref`).

Example:
```yaml
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: MyFunctionNameAbc
      CodeUri: ./
      Handler: hello.handler
      Runtime: python3.6
      Policies:
        - LambdaInvokePolicy:
            FunctionName: MyFunctionNameAbc
```

This creates the following policy:
```json
{
    "Statement": [
        {
            "Action": [
                "lambda:InvokeFunction"
            ],
            "Resource": "arn:aws:lambda:us-west-2:123456789012:function:MyFunctionNameAbc*",
            "Effect": "Allow"
        }
    ]
}
```
