### ISSUE TITLE
Support Fn::If when choosing an Event Type

### ISSUE THREAD

**Issue by stevenmhood** [awslabs/serverless-application-model#1217]
**Description:**

I'd like to be able to choose an Event Source based on a Condition.  I have some code that can work with both DynamoDB and Kinesis streams, deployed as a `AWS::Serverless::Function`.  The only thing that isn't working is defining the `Type` of the `Event`.

**Steps to reproduce the issue:**
```yaml
Parameters:
  EventStreamSource:
    Type: String
    Description: Source for streaming events.  Currently supported sources are DynamoDB and DynamoDBWrappedKinesis
                 (contains DynamodbStreamRecord payloads).
    Default: DynamoDB
    AllowedValues:  # Values are used to select the Java class (see StreamRepartitionerFunction's Handler property)
    - DynamoDB
    - DynamoDBWrappedKinesis
  EventStreamSourceArn:
    Type: String
    Description: Stream ARN from which snapshots will be produced.
Conditions:
  UseDynamoDBSource:
    Fn::Equals:
    - Ref: EventStreamSource
    - DynamoDB
Resources:
  StreamRepartitionerFunction:
    Type: AWS::Serverless::Function
    DependsOn:
    - RepartitioningStream
    - StreamRepartitionerFunctionRole
    Properties:
      Handler:
        Fn::Sub: com.amazon.snapshot.repartition.Repartitioner${EventStreamSource}LambdaHandler::handleRequest
      Runtime: java8
      CodeUri:
        Bucket: s3-bucket-here
        Key: s3-key-here
      Description: Repartitions an event stream using a Kinesis Stream
      MemorySize: 320
      Timeout: 15
      Role:
        Fn::GetAtt: StreamRepartitionerFunctionRole.Arn
      Events:
        StreamEvent:
          Type: 
            Fn::If:
            - UseDynamoDBSource
            - DynamoDB
            - Kinesis
          Properties:
            Stream:
              Ref: EventStreamSourceArn
            StartingPosition: LATEST
            BatchSize: 1000
            MaximumBatchingWindowInSeconds:
              Ref: RepartitionMaximumBatchingWindowInSeconds
            Enabled: true
```

**Observed result:**
Creating a ChangeSet fails with the following error:
```
Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [StreamRepartitionerFunction] is invalid. Event with id [StreamEvent] is invalid. unhashable type: 'dict'
```

[cfn-lint](https://github.com/aws-cloudformation/cfn-python-lint) fails with the following error:
```
E0001 Error transforming template: Resource with id [StreamRepartitionerFunction] is invalid. Event with id [StreamEvent] is invalid. unhashable type: 'dict_node'
template.yml:1:1
```

**Expected result:**
The transform should complete and create the appropriate `AWS::Lambda::EventSourceMapping`, so cfn-lint and the ChangeSet succeed.
