### ISSUE TITLE
Enabled property not accepting String values using Parameters/Mappings/Intrinsic functions

### ISSUE THREAD

**Issue by kanikaaws** [awslabs/serverless-application-model#1229]
I'm trying to create `AWS::Serverless::Function `resource with Events Type: Schedule, and for the property `"Enabled"`, it accepts Boolean value True/False. I need to pass this True/False value using Parameters/Mappings/Intrinsic function, but whenever I pass the value, it gets evaluated to "True", no matter what is in the string. 

Similar Issue: https://github.com/awslabs/serverless-application-model/issues/1154

**Use-case**: 
Need to enable/disable the cron rule based on environment type i.e. set to False/Disabled if environment equal to dev/stage, and set to True/Enable when environment equals to prod.

**Observed result:**
If EnvironmentType=dev, CronState=False, and so the Events Rule must be created with DISABLED state, however, it doesn't resolve the FindInMap or !Ref, and instead creates the rule with ENABLED state. 

```
Parameters:
  EnvironmentType:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - stage
      - prod
Mappings:
  EnvironmentMapping:
    stage:
      CronState: true
    dev:
      CronState: false
   prod:
      CronState: true
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
     Events:
        TestEvent:
          Type: Schedule
          Description: run every 1 minute
          Properties:
            Schedule: rate(5 minutes)
            Enabled: !FindInMap ["EnvironmentMapping",!Ref "EnvironmentType","CronState"]
            # accepts only hardcoded Boolean values --> Enabled: False or Enabled: True
            
```

**Expected result:**
The value must yield to False, and the Events::Rule must be created with DISABLED state.
