### ISSUE TITLE
Global AllowCredentials is not working

### ISSUE THREAD

**Issue by dz902** [awslabs/serverless-application-model#1272]
```
Globals:
  Api:
    Cors:
      AllowOrigin: "'http://localhost:9000'"
      AllowCredentials: "'true'"
      AllowMethods: "'GET,POST'"
      AllowHeaders: "'*'"
```

I have seen this: https://github.com/awslabs/serverless-application-model/issues/1166

But `AllowCredentials` is definitely not working for either `true`, `"true"` or `"'true'"`. Since this is a very important setting, not sure why no one is raising this up.

All other cors settings work without problem, just `AllowCredentials`.
