### ISSUE TITLE
Cannot set DynamoDB event's MaximumRetryAttempts

### ISSUE THREAD

**Issue by Hand-E-Food** [awslabs/serverless-application-model#1283]
**Description:**

In a template.yaml, I cannot set the MaximumRetryAttempts for a Lambda's DynamoDB event source as described in the documentation:
https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#dynamodb

**Steps to reproduce the issue:**
1. Create a template.yaml:

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  MyTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: MyTable
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: MyCode::Function
      Runtime: dotnetcore2.1
      Events:
        MyEvent:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt MyTable.StreamArn
            StartingPosition: LATEST
            MaximumRetryAttempts: 0
```

2. Run `sam validate`

**Observed result:**

> Template provided at 'C:\path\template.yaml' was invalid SAM Template.
> Error: [InvalidResourceException('MyFunctionMyEvent', 'property MaximumRetryAttempts not defined for resource of type DynamoDB')] ('MyFunctionMyEvent', 'property MaximumRetryAttempts not defined for resource of type DynamoDB')

**Expected result:**

> C:\path\template.yaml is a valid SAM Template
