### ISSUE TITLE
Support Serverless Tags format for all resources

### ISSUE THREAD

**Issue by sbol-coolblue** [awslabs/serverless-application-model#1297]
**Description:**

In AWS::Serverless::* resources, we define tags as follows:

```
  MySimpleTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: "my-table"
      ...
      Tags:
        Name: "my-table"
        Environment: "production"
```

Regular AWS resources have a different, more verbose, style of defining tags:

```
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      ...
      Tags:
        - Key: "Name"
          Value: "my-queue"
        - Key: "Environment"
          Value: "Production"

```

Since SAM Templates contain a mix of Serverless resources processed by SAM, and "regular" resources used directly by CloudFormation, we have to define our tags in two different ways. This makes it harder than it can be to apply new tags to our resources.

Since the two tagging formats are using a different data structure it should be relatively trivial for SAM to detect when the serverless format is used and rewrite it to the classic style.

I'd like to propose supporting the dictionary format for all resources, and have SAM translate to the list-style format for any resources that are not handled by SAM.

**Steps to reproduce the issue:**

1. In the Queue example above, use the dictionary-style format.
2. Run the SAM transformation on it

**Observed result:**
Invalid template, because the Tags are a Dictionary whereas Cloudformation requires a List.

**Expected result:**
Valid template, because SAM transformed each element in the Dictionary to a List element with a Key and Value.
