### ISSUE TITLE
Use of InlineCode uploads entire workdir

### ISSUE THREAD

**Issue by gdw2** [awslabs/serverless-application-model#1309]
**Description:**

Using the `InlineCode` property seems to be ignored.  Instead, the current working dir (which could be quite large) is uploaded wholesale to s3.

**Steps to reproduce the issue:**

Versions:
```
# python3 -V
Python 3.7.5

# pip3 freeze | grep sam
aws-sam-cli==0.37.0
aws-sam-translator==1.19.0
```

Input template:
```
AWSTemplateFormatVersion: '2010-09-09'

Transform: [ 'AWS::Serverless-2016-10-31']

Resources:

  # Lamba that spits out version

  VersionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: "HelloWorld"
      Handler: index.handler
      Runtime: nodejs10.x
      InlineCode: |
        exports.handler = async (event) => {
          return {
            statusCode: 200,
            headers: {'Content-Type':'application/json'},
            body: "hello"
            }
        }

```

Package command:
```
sam package --profile gwarner7 --region us-west-2 --template-file basic_function.yaml --output-template-file package_fn.yaml --s3-bucket bep-om-gwarner7
```
**Observed result:**
Output template:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::Serverless-2016-10-31
Resources:
  VersionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorld
      Handler: index.handler
      Runtime: nodejs10.x
      InlineCode: "exports.handler = async (event) => {\n  return {\n    statusCode:\
        \ 200,\n    headers: {'Content-Type':'application/json'},\n    body: \"hello\"\
        \n    }\n}\n"
      CodeUri: s3://bep-om-gwarner7/a769e4395407e36cdc9359ec10cdc19c
```

Furthermore, and as stated above, the contents of my working dir (which is 1 GB+) is uplaoded to s3 in support of this simple inline function.  

**Expected result:**

I would expect something like the following (note the absense of a `CodeUri` and the presence of a `ZipFile`:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::Serverless-2016-10-31
Resources:
  VersionFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: HelloWorld
      Handler: index.handler
      Runtime: nodejs10.x
      Code: 
            ZipFile: | "exports.handler = async (event) => {\n  return {\n    statusCode:\
        \ 200,\n    headers: {'Content-Type':'application/json'},\n    body: \"hello\"\
        \n    }\n}\n"

```
