### ISSUE TITLE
Error when transforming parameter list of strings that contains numbers

### ISSUE THREAD

**Issue by matsev** [awslabs/serverless-application-model#131]
Some strings are not transformed correctly when executing `aws cloudformation package`.

Given the following `template.yaml`:

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Example Template

Parameters:
  Month:
    Description: Select month
    Type: String
    AllowedValues: ["01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12"]
    Default: "06"

Resources:
  ExampleLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Description: Example Lambda
      Environment:
        Variables:
          MONTH: !Ref Month
      Handler: index.handler
      Policies: AWSLambdaBasicExecutionRole
      Runtime: nodejs6.10
```

Executing `aws cloudformation package` result in the following `packaged-template.yaml`:

```
AWSTemplateFormatVersion: 2010-09-09
Description: Example Template
Parameters:
  Month:
    AllowedValues:
    - '01'
    - '02'
    - '03'
    - '04'
    - '05'
    - '06'
    - '07'
    - 08
    - 09
    - '10'
    - '11'
    - '12'
    Default: '06'
    Description: Select month
    Type: String
Resources:
  ExampleLambda:
    Properties:
      CodeUri: s3://billing-deployment/360dc36bb10d9734e0e16e96cdf2d171
      Description: Example Lambda
      Environment:
        Variables:
          MONTH:
            Ref: Month
      Handler: index.handler
      Policies: AWSLambdaBasicExecutionRole
      Runtime: nodejs6.10
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
```

Note that **08** and **09** are translated as numbers, not strings.

AWS CLI:
```
$ aws --version
aws-cli/1.11.83 Python/2.7.10 Darwin/16.5.0 botocore/1.5.46
```
