### ISSUE TITLE
Unable to update CognitoUserPool. CloudFormation stack update failes.

### ISSUE THREAD

**Issue by vasylk** [awslabs/serverless-application-model#134]
Apparently there is an issue with UserPool update - not possible to modify UserPool properties at all.

The stack update fails with:
* Status UPDATE_FAILED
* Type: AWS::Cognito::UserPool
* Status reason: Internal Failure

Details:
* AWS Region: eu-central-1
* The only parameter that was changed RequreNumbers from true to false
```
  
   Type: "AWS::Cognito::UserPool"
   Properties:
      ..... (more properties)
      Policies:
	PasswordPolicy:
	  RequireNumbers: false
          .....(more properties)

```

And second issue with LambdaTriggers for UserPool, which are a part of the same CloudFormation stack.
After the stack is  successfully created, LamdaTriggers fail to execute with AccessDenied Exception. Lamda functions are mapped correcly as Triggers.

The remedy for this is to go to AWS Console/UserPool properties/Triggers and just "Save changes" without changing anything.

**Comment by kskory** [comment]
For you second issue (AccessDenied) you have to add permissions for user pool to execute lambda, you can do it in CF like that:

```
  CognitoPostAuthLambaPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref PostAuthLambdaHandler
      Principal: "cognito-idp.amazonaws.com"
      SourceArn: !GetAtt CognitoUserPool.Arn
```

And about your fist issue, I saw something similar when trying to update "AWS::Cognito::UserPoolClient". It fails with Internal Failure.
It looks like there's some problem even in Cognito UI. It fails when you try to update the ClientName if you don't click "show details" first.
