### ISSUE TITLE
Conditional DeploymentPreference not supported

### ISSUE THREAD

**Issue by hgl** [awslabs/serverless-application-model#1342]
**Description:**

I want to disable `DeploymentPreference` for staging and only enable for prod, it seems it's not supported.

**Steps to reproduce the issue:**

```
Conditions:
  IsProd: !Equals [ !Ref Stage, prod ]
Function:
  Type: AWS::Serverless::Function
  Properties:
    DeploymentPreference:
      Enabled: !If [ IsProd, true, false ]
      Type: Canary10Percent10Minutes
```

**Observed result:**

Failed with
```
Resource with id [Function] is invalid. 'Enabled' must be a boolean value
```
**Expected result:**

It should deploy.
