### ISSUE TITLE
Allow to override the AWS::Serverless::Function generated Version SHA 

### ISSUE THREAD

**Issue by jmnarloch** [awslabs/serverless-application-model#1375]
**Description:** `AutoPublishAlias` will lead to SAM creating a Lambda::Version with SHA computed based on Function `Code` configuration. This behaviour is not aligned with Lambda PublishVersion check that can lead into API call failing with error message 

```
409 - Conflict
A version for this Lambda function exists.
```

This becomes problematic if you deploy the same code into S3 as new object key, SAM will attempt to create new CloudFormation Lambda version, while Lambda will reject that at runtime.

It becomes even more problematic if you use a single CloudFormation template to deploy more then one Lambda function at a time.

**Steps to reproduce the issue:**
1. Create a SAM template:

```
Resources:
  MinimalFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: s3://sam-demo-bucket/hello.zip
      Handler: hello.handler
      Runtime: python2.7
      AutoPublishAlias: live
      VersionDescription: sam-testing
```

2. Execute `sam init && sam deploy`
3. Copy the S3 object as new key and update it in the template.
4. Repeat this step.

**Observed result:**

The execution fails with stack being rollback due to `A version for this Lambda function exists.`

**Expected result:**
The end result that we would like to be able to achieve is to associated with SAM Function the SHA of the deployed code that would grant that the CloudFormation deployment will not be attempting to create new version of Lambda function each time.

i.e. this could be achieved by introducing new attribute like `AutoPublishAliasCodeSha256` (or just `CodeSha256` for short, though I did not want to confuse it with the existing Lambda::Version `CodeSha256`).
