### ISSUE TITLE
missing validation error with Domain HostedZoneId

### ISSUE THREAD

**Issue by timoschilling** [awslabs/serverless-application-model#1383]
**Description:**

I missed to nested `HostedZoneId` under `Route53` and didn't get an validation error.

**Steps to reproduce the issue:**

1. create a stack with
```yaml
Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: FooBar
      StageName: Prod
      Domain:
        DomainName: !Ref Domain
        CertificateArn: !Ref CertificateArn
        HostedZoneId: Z1WXXXXXXC4O
```

**Observed result:**

Deploy without creating an creating a domain.

**Expected result:**

An validation error.
