### ISSUE TITLE
Transforms do not support Conditions

### ISSUE THREAD

**Issue by brandond** [awslabs/serverless-application-model#142]
If I put a Condition on a resource of type "AWS::Serverless::Function", this condition is neither honored by the transform, nor is it passed through to the resources created by the transform. This makes it impossible to conditionally create transformed resources.

### Tracking Conditions support:
- [x] Serverless::Function
    - [x] Function resource (v1.10.10)
    - [x] Events (v1.10.0) (see https://github.com/awslabs/serverless-application-model/issues/214 for tracking conditions support inside of events, which is not implemented in v1.10.0)
    - [x] Implicit API: Issue https://github.com/awslabs/serverless-application-model/issues/758
    - [x] Alias (v1.10.0)
- [x] Serverless::Api (v1.10.0)
- [x] Serverless::LayerVersion (v1.10.0)
- [x] Serverless::Application (v1.10.0)
- [x] Serverless::SimpleTable (v1.10.0)

**Comment by sanathkr** [comment]
Yup, feature request. We already have being implemented now. Will update once its ready.

**Comment by mikecbrant** [comment]
I would add that my experience has not been having the transform silently ignore conditions, but rather to have the conditions cause the generic "internal transform failure" error message at the point of trying to create a change set (template validation does not catch the issue).

In my case, I was trying to conditionally set the "Path" property on an API event in AWS::Serverless:Function like the following:

```
      Events:
        GetByKey:
          Type: Api
          Properties:
            Path: !If [DynamoHasRangeKey, '/{hashKey}/{rangeKey}', '/{hashKey}']
            Method: get
```

The condition works in other areas of the template (like the AWS::DynamoDB::Table resource that is being defined).

**Comment by brandond** [comment]
@mikecbrant that's not a condition, that's a function that evaluates a conditional test (If). Conditions look like this:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Conditions: 
  IsTargetRegion: !Equals [ !Ref "AWS::Region", "us-west-2" ]
Resources: 
  NewVolume: 
    Type: "AWS::EC2::Volume"
    Properties: 
      Size: 100
    Condition: IsTargetRegion
```

The resource gets skipped entirely if the condition evaluates to false.

**Comment by mikecbrant** [comment]
@brandond Yes, I suppose that would be proper nomenclature, however the intrinsic function in my example is tied to a condition that has defined in the Cloudformation template "Conditions" property (in this case DynamoHasRangeKey). That was probably not clear from my example.  This functionality seems to break down in certain places in the template.

**Comment by glenveegee** [comment]
If conditional resource creation is eventually supported you might also have to support conditional events as in the following example where in some environments a bucket might not already exist and so it can be created and the event attached to the lambda. While in other environments the bucket may already exist and the trigger needs to be manually defined because cloudformation doesn't yet use existing resources

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: Lambda that responds to S3 events

Parameters:
    PreExistingBucket:
        Description: "Does an existing bucket exist (not managed by cloudformation)"
        Type: String
        Default: 'no'
        AllowedValues:
            - 'yes'
            - 'no'
        ConstraintDescription: must specify yes or no.

Conditions:
  NeedsSomeBucket: !Equals [ !Ref PreExistingBucket, 'no' ]

Resources:
    BucketEventConsumer:
        Type: AWS::Serverless::Function
        Properties:
            Handler: BucketEventConsumer.main.lambda_handler
            Runtime: python3.6
            CodeUri: bundle.zip
            Events:
                CreateMetaEvent:
                    Condition: NeedsSomeBucket
                    Type: S3
                    Properties:
                        Bucket: !Ref SomeBucket
                        Events: "s3:ObjectCreated:*"
                        Filter:
                            S3Key:
                                Rules:
                                    -
                                        Name: suffix
                                        Value: meta.json
    SomeBucket:
        Condition: NeedsSomeBucket
        Type: "AWS::S3::Bucket"
        Properties:
            BucketName: 'some-bucket-somewhere'
        DeletionPolicy: Retain
```
I'd like to draw your attention to the following crucial lines:

```yaml
                CreateMetaEvent:
                    Condition: NeedsSomeBucket
```

**Comment by jfuss** [comment]
@glenveegee That is an interesting thought and idea! Would you mind create a new issue with this use case? It will help us prioritize this in the future and will ensure it does not get lost or forgotten about in this issue (since they are slightly different).

**Comment by glenveegee** [comment]
Sure. Moved to https://github.com/awslabs/serverless-application-model/issues/214

**Comment by sanathkr** [comment]
Closing this in favor of #214

**Comment by brandond** [comment]
#224 is a completely separate request and should NOT replace this issue. This is just asking for conditionals to be honored passed through - for example, if I put a conditional on a `AWS::Serverless::Function`, I expect those conditions to be passed through to the resources that the function template expands to (Lambda, IAM role, etc).

**Comment by jfuss** [comment]
This was closed by mistake. Reopening.

**Comment by seokheekim** [comment]
Any work around for now?

**Comment by ruhkopf** [comment]
Any updated or workarounds on this issue?

**Comment by barrett-rob** [comment]
bump

**Comment by ColinWhitmarsh** [comment]
bump

**Comment by knadigatla** [comment]
any update on this yet?

**Comment by brettstack** [comment]
Happy to work with someone if they want to submit a PR for this.

**Comment by pc-mreeves** [comment]
Last message that is was being worked on was about a year ago:
`Yup, feature request. We already have being implemented now. Will update once its ready.`

Pretty please? :-)

**Comment by DarkJaguar91** [comment]
Have the same issue, don't want to create a AWS::Serverless::Function in a specific region but the condition is being ignored.

**Comment by meinctutw** [comment]
Same here. We need conditions to deploy AWS::Serverless::Function to specific stages. As example to deploy a delete function to test stage but not prod.
Condition is being ignored. It would be great if this is gets implemented.

**Comment by evankozliner** [comment]
Does anyone know if adding this feature for `AWS::Serverless::Api` is also in the works?

**Comment by lstatro** [comment]
Just found this issue deploying between aws partitions.  Hopefully there's a fix to this sooner rather then later.

**Comment by jackrk** [comment]
Incredible

**Comment by alex-gausman** [comment]
Is this feature in the pipeline?

**Comment by keetonian** [comment]
@alex-gausman We are reviewing it and it should be available with the next SAM release.

**Comment by jlhood** [comment]
@Jacco Just merged in your PR to support conditions! Note, since that PR was submitted prior to our re:Invent release, it adds Condition support for `AWS::Serverless::Function`, `AWS::Serverless::Api`, and `AWS::Serverless::SimpleTable`, but not for the 2 new resource types added for re:Invent: `AWS::Serverless::Application` and `AWS::Serverless::LayerVersion`.

Wondering if you'd be willing to submit a PR to add Condition support to those two resources as well prior to our next release. 🙏

**Comment by nagarajatantry** [comment]
Hi, Any timeline on when this fix will be released ?

**Comment by keetonian** [comment]
This is staged for the v1.10.0 release ([diff](https://github.com/awslabs/serverless-application-model/compare/release/v1.10.0)) which will be released soon

**Comment by keetonian** [comment]
Released!

**Comment by rhbecker** [comment]
I'm having a hard time understanding what should and shouldn't be working at this point. Is this documented somewhere? The [spec](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md) doesn't really mention conditions.

My reason for seeking this issue out is that I want a function that always exists, but with the ability to toggle whether that function is subscribed to an sns event based on a param evaluated in a condition. The idea is to "disable" the function from acting without having to delete the stack, or to delete the function from the stack.

For example ...

```Yaml
Parameters:
  IsListening:
    AllowedValues: [true, false]
    Default: true
    Type: String

Conditions:
  EventsActive: !Equals ['true', !Ref IsListening]

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ExampleTopic:
          Type: SNS
          Condition: EventsActive
```

In the _Tracking Conditions support:_ checklist at the top of this issue, _Serverless::Function_ > _Events_ is checked off, but then the note next to that checkbox states that "conditions support inside of events [...] is not implemented".

It's not clear to me what the check-off is noting as completed, and it's not clear what exactly is meant by "support inside of events". Based on issue #214, I think what I'm trying to do is not yet possible, but it'd be great to confirm and to find some sort of user-friendly guidance about what _is_ supported.
