### ISSUE TITLE
Can't use DeletionPolicy with Type: AWS::DynamoDB::Table

### ISSUE THREAD

**Issue by mrichman** [awslabs/serverless-application-model#1465]
I have the following:

```
MyTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      TableName: mytable
      AttributeDefinitions:
      - AttributeName: PK
        AttributeType: S
      - AttributeName: SK
        AttributeType: N
      KeySchema:
      - AttributeName: PK
        KeyType: HASH
      - AttributeName: SK
        KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
```

When I deploy, I get `Encountered unsupported property DeletionPolicy`.

I need to ensure the DynamoDB table is not deleted upon rollback of the stack.
