### ISSUE TITLE
ESM event sources DestinationConfig.OnFailure.Type not removed by the translator

### ISSUE THREAD

**Issue by nmoutschen** [awslabs/serverless-application-model#1475]
**Description:**

SAM supports an optional "Type" property for DestinationConfig.OnFailure for ESM events (DynamoDB, Kinesis, etc.). The `AWS::Lambda::EventSourceMapping` resource does not support a "Type" property for [DestinationConfig.OnFailure](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-lambda-eventsourcemapping-onfailure.html). The translator should therefore remove it to respect the CloudFormation specification.

When defining the DestinationConfig.OnFailure.Type property for ESM event sources for AWS::Serverless::Function, `cfn-lint` fails with `E3002 Invalid Property Resources/FunctionKinesis/Properties/DestinationConfig/OnFailure/Type`.

You can find a sample failing template here:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: 'AWS::Serverless-2016-10-31'


Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue

  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      ShardCount: 1

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      CodeUri: ./src/
      Handler: main.handler
      Events:
        Kinesis:
          Type: Kinesis
          Properties:
            Stream: !GetAtt KinesisStream.Arn
            StartingPosition: TRIM_HORIZON
            DestinationConfig:
              OnFailure:
                Type: SQS
                Destination: !GetAtt DeadLetterQueue.Arn
```

**Steps to reproduce the issue:**
1. ```bash
   cat > template.yaml << EOF
   AWSTemplateFormatVersion: "2010-09-09"
   Transform: 'AWS::Serverless-2016-10-31'
   
   
   Resources:
     DeadLetterQueue:
       Type: AWS::SQS::Queue
   
     KinesisStream:
       Type: AWS::Kinesis::Stream
       Properties:
         ShardCount: 1
   
     Function:
       Type: AWS::Serverless::Function
       Properties:
         Runtime: python3.8
         CodeUri: ./src/
         Handler: main.handler
         Events:
           Kinesis:
             Type: Kinesis
             Properties:
               Stream: !GetAtt KinesisStream.Arn
               StartingPosition: TRIM_HORIZON
               DestinationConfig:
                 OnFailure:
                   Type: SQS
                   Destination: !GetAtt DeadLetterQueue.Arn
   EOF
   ```
2. ```bash
   cfn-lint template.yaml
   ```

**Observed result:**

```
E3002 Invalid Property Resources/FunctionKinesis/Properties/DestinationConfig/OnFailure/Type
template.yaml:28:17
```

**Expected result:**

```
```

_(empty string)_
