### ISSUE TITLE
AccessDenied: NoSuchEntityException when attaching AWSLambdaBasicExecutionRole for a new Function

### ISSUE THREAD

**Issue by dinvlad** [awslabs/serverless-application-model#150]
Hi Team,

I've just got a strange AccessDenied exception when creating a new `AWS::Serverless::Function`. I'm trying to add a function that picks up item updates from a DynamoDB stream and indexes them in CloudSearch. However, when updating the stack with that new function, CloudFormation fails with an 'AccessDenied' error, saying that
```
API: iam:AttachRolePolicy User: arn:aws:sts::************:assumed-role/infrastructure-BackendDeploymentRole-XXXXX/AWSCloudFormation is not authorized to perform: iam:AttachRolePolicy on resource: role backend-beta-CloudSearchUploadDocumentsRole-YYYYY
```
That is strange, because I have added permissions for `infrastructure-BackendDeploymentRole-XXXXX` to attach `AWSLambdaBasicExecutionRole` to any of the roles with `backend-beta-` prefix, which are created automatically for the the corresponding functions by SAM, and this has worked for all other functions before.

Further, the CloudTrail log displays that this `AccessDenied` error is in fact
```
Error code: NoSuchEntityException
Resources Referenced (2):
IAM Role	backend-beta-CloudSearchUploadDocumentsRole-YYYYY	
IAM Policy	arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
```
So it appears that CloudFormation doesn't 'see' the role it has just created for this function when trying to attach `AWSLambdaBasicExecutionRole` to it. I don't know why and how such a race condition could occur, given that all functions before this one worked fine.

Here's my reference config, just in case:
```
  CloudSearchUploadDocuments:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-CloudSearchUploadDocuments
      CodeUri: ../app
      Handler: search.uploadDocuments
      Runtime: nodejs6.10
      Environment:
        Variables:
          SEARCH_DOC_ENDPOINT: !GetAtt SetupSearchDomain.DocEndpoint
      Events:
        DatasetsTable:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DatasetsTable.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 100
      Policies:
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:ListStreams
              - dynamodb:DescribeStream
              - dynamodb:GetShardIterator
              - dynamodb:GetRecords
            Resource:
              - !Sub arn:aws:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${DatasetsTable}/stream/*
          - Effect: Allow
            Action:
              - cloudsearch:UploadDocuments
            Resource:
              - !Sub arn:aws:cloudsearch:${AWS::Region}:${AWS::AccountId}:domain/${SearchDomain}
```

Thanks
