### ISSUE TITLE
Usage plan not supported for implicit APIs

### ISSUE THREAD

**Issue by mcintyre94** [awslabs/serverless-application-model#1513]
**Description:**

Usage plans for auth on APIs was added in #1141 

Looking at ApiAuth docs (the Auth field on AWS::Serverless::Api objects) - https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiauth.html - the `UsagePlan` field is present.

But implicit APIs (Api events under AWS::Serverless::Function) - https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-function-apifunctionauth.html - are missing that field. So the APIs produced by Lambda functions in SAM don't seem to support this field, which would be useful. Is it possible to support it?

**Steps to reproduce the issue:**

Add to a SAM template:

```
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/my-function
      Handler: index.lambdaHandler
      Runtime: nodejs12.x
      Events:
        MyFunctionApi:
          Type: Api
          Properties:
            Path: /my-function
            Method: post
            Auth:
              ApiKeyRequired: true
              UsagePlan:
                CreateUsagePlan: PER_API
```

**Observed result:**

When deployed, this API is created, but no usage plan or API key are.

**Expected result:**

The API is created, with a usage plan and API key - in the same way they would if it was a top-level API object, as described in #1141
