### ISSUE TITLE
SAM Ignores Metadata section in template

### ISSUE THREAD

**Issue by iscofield** [awslabs/serverless-application-model#153]
As soon as you declare "Transform: AWS::Serverless-2016-10-31" in the template, it no longer respects the Metadata top level section where you can define "AWS::CloudFormation::Interface" to nicely print parameters.   If I comment out the transform line, then it displays my Parameters Groups.  It would be nice if this were respected since it makes the parameters much easier to read and grouped into sections.

**Comment by sanathkr** [comment]
What resources did you add this on? The `Serverless::*` resources or CloudFormation ones?

**Comment by iscofield** [comment]
Neither.  The parameter groups are for parameters, not resources, which are agnostic to the SAM framework.

Open this template below.  Then comment out the Transform line and open it again.

```YAML
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  CodeBucket:
    Type: String
    Description: Bucket name where code is located
  CodeKey:
    Type: String
    Description: Key name (including all prefixes) of code zip
  AutoScalingGroup:
    Type: String
    Description: The name of your AutoScalingGroup
  LocalSG:
    Type: String
    Description: The security group ID of your local Security Group (sg-abcd1234)
  RemoteSG:
    Type: String
    Description: The security group ID of your remote Security Group (sg-abcd1234)
  RemoteRegion:
    Type: String
    Description: The region name of the remote region (us-west-2, us-east-1, etc.)
  RemoteASG:
    Type: String
    Description: The name of your remote region AutoScalingGroup
  RemoteTable:
    Type: String
    Description: The name of the remote DynamoDB Table
Metadata: 
  AWS::CloudFormation::Interface: 
    ParameterGroups: 
      -
        Label: 
          default: "Local Resources"
        Parameters: 
          - LocalSG
          - AutoScalingGroup
      - 
        Label: 
          default: "Remote Resources"
        Parameters: 
          - RemoteSG
          - RemoteRegion
          - RemoteASG
          - RemoteTable
      - 
        Label: 
          default: "General Configuration"
        Parameters: 
          - CodeBucket
          - CodeKey
    ParameterLabels: 
      LocalSG: 
        default: "Local Security Group ID"
      AutoScalingGroup:
        default: "Local Auto Scaling Group Name"
      RemoteSG:
        default: "Remote Security Group ID"
      RemoteRegion:
        default: "Remote Region Name"
      RemoteASG:
        default: "Remote Auto Scaling Group Name"
      RemoteTable:
        default: "Remote DynamoDB Table Name"
      CodeBucket:
        default: "Code Zip S3 Bucket Name"
      CodeKey:
        default: "Code Zip S3 Object Key"
Resources:
  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      AttributeDefinitions: 
        - AttributeName: region
          AttributeType: S
        - AttributeName: asg
          AttributeType: S
      KeySchema: 
        - AttributeName: region
          KeyType: HASH
        - AttributeName: asg
          KeyType: RANGE
      ProvisionedThroughput: 
        ReadCapacityUnits: 3
        WriteCapacityUnits: 3
```
