### ISSUE TITLE
Ref throws error for AutoPublishAliasCodeSha256 property

### ISSUE THREAD

**Issue by ShreyaGangishetty** [awslabs/serverless-application-model#1536]
**Description:**

Ref doesn't work for `AutoPublishCodeSha256`

**Steps to reproduce the issue:**
Template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters:
  AutoPublishCodeSha256:
    Type: "String"
    Description: "Sha256 to uniquely identify creation of the lambda"
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = async () => 'Hello World!'
      Handler: index.handler
      Runtime: nodejs12.x
      AutoPublishCodeSha256: !Ref AutoPublishCodeSha256
      AutoPublishAlias: "live"
```

**Observed result:**
```
TypeError: unhashable type: 'slice'
```

**Expected result:**
Template should deploy successfully without throwing any errors
