### ISSUE TITLE
AWS SAM does not support Auth property for AWS::Serverless::HttpApi

### ISSUE THREAD

**Issue by youjinp** [awslabs/serverless-application-model#1556]
**Description:**
In a SAM template I have a `HttpApi` resource with the authorizer specified, along with a `lambda` resource.

With the `auth` property specified on the `HttpApi` resource specified, the routes for the `HttpApi` are not shown in the console, and no `authorizer` is created.

Removing the `auth` property brings back the routes.

**Template:**
```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  V0API:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: develop
      Auth:
        DefaultAuthorizer: OAuthAuthorizer
        Authorizers:
          OAuthAuthorizer:
            IdentitySource: "$request.header.Authorization"
            JwtConfiguration:
              issuer: "https://example.com/develop/connect/issuer"
              audience:
                - MyApi

  Lambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambda/cmd/
      Handler: main
      Runtime: go1.x
      Tracing: Active
      Timeout: 5
      Events:
        HttpPost:
          Type: HttpApi
          Properties:
            ApiId: !Ref V0API
            Path: /login
            Method: post
      Policies:
        - AWSLambdaExecute
```

**Observed result:**
- `HttpApi` resource created **without** authorizer and routes

**Expected result:**
- `HttpApi` resource created **with** authorizer and routes
