### ISSUE TITLE
"API Stage not found" in AWS::ApiGateway::UsagePlan resource when changing API Stage name

### ISSUE THREAD

**Issue by piersf** [awslabs/serverless-application-model#1560]
**Description:**
I have the below API and Usage Plan resources created in my SAM template:

```yaml
Parameters:
  ApiStageName:
    Type: String

ManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "my-api"
      StageName: !Ref ApiStageName

UsagePlanForManagementApi:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: [ "ManagementApi" ]
    Properties:
        ApiStages:
            - ApiId: !Ref ManagementApi
              Stage: !Ref ApiStageName
        Description: "Management API Usage Plan"
        Quota:
            Limit: 100
            Period: DAY
        Throttle:
            BurstLimit: 50
            RateLimit: 100
        UsagePlanName: "my-api-usage-plan"
```
The above resource get deployed just fine and without any issues.

However, when I change the value of the `ApiStageName` parameter from `v1` to `v2`, and try to run a `sam deploy`, the update with fail with the below error:

```
UPDATE_IN_PROGRESS                        AWS::ApiGateway::RestApi        ManagementApi        -
UPDATE_ROLLBACK_IN_PROGRESS               AWS::CloudFormation::Stack      dev-management-api-sam          The following resource(s) failed to update: [UsagePlanForManagementApi].
UPDATE_FAILED                             AWS::ApiGateway::UsagePlan      UsagePlanForManagementApi 
                                                                                                           API Stage not found: API_ID:v2 
                                                                                                           (Service: AmazonApiGateway; Status Code: 404; 
                                                                                                           Error Code: NotFoundException; Request ID: xxxxxxxxxxxxxxxxxxxxxxxxxxxx)
```
It looks like there's some race condition going on here. I have used `DependsOn` on the Usage Plan resource to depend on the API resource but it does not seem make any difference.

Any idea how this can be fixed? Is this a bug in SAM?

**Steps to reproduce the issue:**
1. Create the above resources and initially set the value of the `ApiStageName` parameter to `v1`
2. Deploy
3. Update the value of the `ApiStageName` parameter from `v1` to `v2`
4. Deploy

**Observed result:**
The deployment fails with the above error when updating the value of the `ApiStageName` parameter to `v2`

**Expected result:**
The deployment should  not fail with the above error

I came across issue #32 which has been closed but I didn't see a solution. Also, that issue is from 2 years ago so I'm hoping a fix has been released since then.

Thank you

**Comment by keetonian** [comment]
For your current setup, it looks like you need to depend on the Stage resource that SAM generates rather than the API.

```yaml
  UsagePlanForManagementApi:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - ManagementApi.Stage
```

On a side note, have you considered using the [UsagePlan](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiusageplan.html) feature in SAM? The syntax for this same example you posted would be the following:

```yaml
Parameters:
  ApiStageName:
    Type: String

Resources:
  ManagementApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: "my-api"
      StageName: !Ref ApiStageName
      Auth:
        UsagePlan:
          CreateUsagePlan: PER_API
          UsagePlanName: "my-api-usage-plan"
          Quota:
            Limit: 100
            Period: DAY
          Throttle:
            BurstLimit: 50
            RateLimit: 100
          Description: "Management API Usage Plan"
```

SAM handles the depends on and other resource dependencies for you in this case.

**Comment by duc2019** [comment]
I had same issue and this works for me. 

```
DependsOn: 'ApiGatewayDeployment${sls:instanceId}'
```

**Comment by piersf** [comment]
> I had same issue and this works for me.
> 
> ```
> DependsOn: 'ApiGatewayDeployment${sls:instanceId}'
> ```

@duc2019 isn't that from the `serverless` framework? This is AWS SAM we're talking about.

**Comment by mkrauklis** [comment]
Looks like since writing this the naming convention for the logical name of the stage has changed to include the stage name.

e.g. if the provided stage name above was Prod then the depends on would need to be:
`DependsOn: ManagementApiProdStage`

**Comment by sawilde** [comment]
@mkrauklis weird, I don't get the stage name included in the LogicalResourceId 

```
+ Add                                   RestApiPublicApiAuthorizerAuthorizerP   AWS::Lambda::Permission                 N/A                                   
                                        ermission                                                                                                             
+ Add                                   RestApiStage                            AWS::ApiGateway::Stage                  N/A                                   
+ Add                                   RestApi                                 AWS::ApiGateway::RestApi                N/A                                   
```

for anyone looking at this, reviewing the changeset will help identify the miscreant you are after :)

**Comment by PhilA1** [comment]
> > I had same issue and this works for me.
> > ```
> > DependsOn: 'ApiGatewayDeployment${sls:instanceId}'
> > ```
> 
> @duc2019 isn't that from the `serverless` framework? This is AWS SAM we're talking about.

this worked for me.
It allows the serverless framework to finish off everything it needs, before firing off the usageplan amendments.
thanks

**Comment by domengabrovsek** [comment]
Why has this issue been closed? I'm still experiencing the same issue as the author of this issue. This is the only approach that worked for me: https://github.com/aws/serverless-application-model/issues/1560#issuecomment-638944938

https://github.com/aws/serverless-application-model/issues/1560#issuecomment-615486160 is not an option for me because I want to create a usage plan, and an API key and then connect them using "AWS::ApiGateway::UsagePlanKey". If a usage plan is added inside the "AWS::Serverless::Api" resource then it cannot be referenced in the "AWS::ApiGateway::UsagePlanKey". At least I didn't find any documentation or working examples on that.

**Comment by andersenthomas98** [comment]
Thank you @domengabrovsek. Your solution also worked for me.

**Comment by henryfJones** [comment]
Similar to the above solutions I found the below worked for me. (I'm using serverless)

```
WebSocketUsagePlan:
  Type: AWS::ApiGateway::UsagePlan
  DependsOn: 
    - WebsocketsDeploymentStage
```

**Comment by jorgesisco** [comment]
> TestUsagePlan:
>     Type: AWS::ApiGateway::UsagePlan
>     DependsOn: 
>       - ApiGatewayStage
>     Properties:
>       ApiStages:
>         - ApiId: !Ref ApiGateway
>           Stage: !Ref StageName
>       Description: Test Usage Plan

I wonder in 

```
TestUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn: 
      - ApiGatewayStage
    Properties:
      ApiStages:
        - ApiId: !Ref ApiGateway
          Stage: !Ref StageName
      Description: Test Usage Plan
```

Why - ApiGatewayStage and not - ApiGateway ??

I used ApiGatewayStage and it gets deployed but when I do a request to the endpoint providing x-api-ley I get bad gateaway 502.
