### ISSUE TITLE
Feature request: optional parameters for sam policy templates

### ISSUE THREAD

**Issue by timoschilling** [awslabs/serverless-application-model#1570]
**Description:**

SAM policy templates are a very nice feature. But sometime we have use cases where they are unusable. This could be fixed if policy templates are able to deal with default parameters.

**Example S3ReadPolicy:**

We would like to specify the allowed key too.

```yaml
Policies:
  - S3ReadPolicy:
      Bucket: foo
      key: foo/*/bar
```

**Example LambdaInvokePolicy:**

We would like to use it for cross region invoketion.

```yaml
Policies:
  - LambdaInvokePolicy
      FunctionName: foo
      Region: eu-central-1
```

**Example generic:**

```yaml
Policies:
  - LambdaInvokePolicy
      Resource: arn:aws:lambda:eu-central-1:12345678:function:some-function*
```
