### ISSUE TITLE
Proposal: AWS::Serverless::Queue

### ISSUE THREAD

**Issue by timoschilling** [awslabs/serverless-application-model#1571]
**Description:**

Setting up an SQS Queue is sometimes more complicated than it needs to be.
Setting up an Queue should be done in the same DRY way it works for Lambdas.

**Before example:**

```yaml
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt DeadLetterQueue.Arn
        maxReceiveCount: 5

  DeadLetterQueue:
    Type: AWS::SQS::Queue

  QueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - !Ref Queue
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              AWS: '*'
            Action: SQS:SendMessage
            Resource: !GetAtt Queue.Arn
            Condition:
              ArnEquals:
                aws:SourceArn:
                  - !Ref SnsArn
                  - !GetAtt SomeResource.Arn
```

**After Example:**

```yaml
  Queue:
    Type: AWS::SQS::Queue
    Properties:
      DeadLetterQueue: true
      Sources:
         - Arn: !Ref SnsArn
         - Arn: !GetAtt SomeResource.Arn
```
