### ISSUE TITLE
Add support for Alexa Smart Home Skill

### ISSUE THREAD

**Issue by PMudra** [awslabs/serverless-application-model#158]
SAM already includes AlexaSkill as event source type. It would be great if Alexa Smart Home Skills were also supported.

For example I cannot (completely) export my lambda function when using a alexa smart home as trigger:

![image](https://user-images.githubusercontent.com/84765/28073377-c605e7ac-6655-11e7-9339-741b3074b843.png)

- Does this feature simplify creating and deploying some aspect of a Serverless application?
  - Yes, lambda function using the alexa smart home trigger could be deployed using CloudFormation.
- Is this feature solving a problem faced by other Serverless application developers?
  - Yes, I believe so.
- How do developers work around this problem today?
  - It is possible to deploy the lambda function partially. Some manual steps are required to setup the alexa smart home skill.
- How is the proposed feature better than the work around?
  - By adding the feature the deployment can be fully automated.

**Comment by elmi82** [comment]
We are running into the same problem right now. I've spent some time today trying to figure out if it can somehow be done programmatically. But, if I did not miss anything, CloudFormation `AWS::Lambda::Permission` is missing support for `Condition`, which would be required to add the Smart Home Skill Trigger.

So the following does **not** work:
```yaml
  AlexaSmartHomeExecutionPermission:
    Type: AWS::Lambda::Permission
    DependsOn: AlexaLambda
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt AlexaLambda.Arn
      Principal: alexa-connectedhome.amazon.com
      Condition:
        StringEquals:
          lambda:EventSourceToken: "amzn1.ask.skill.<UUID>"
```

It would be great if we could specify the `AWS::Serverless::Function` like this:
```
  AlexaLambda:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: <CodeURI>
      Handler: lambda.handler
      Description: 'Amazon Alexa Service'
      MemorySize: 128
      Runtime: nodejs6.10
      Timeout: 30
      Events:
        Type: AlexaSmartHome
        Properties:
          EventSourceToken: "amzn1.ask.skill.<UUID>"
```
