### ISSUE TITLE
Resources created through the Serverless Transform contain hardcoded partitions in arns

### ISSUE THREAD

**Issue by dontirun** [awslabs/serverless-application-model#1590]
**Description:**

I am writing [custom linting scripts](https://github.com/aws-cloudformation/cfn-python-lint/issues/1522) to detect whether my cloudformation template has hardcoded Partitions and/or Regions. Templates processed by the SAM transform create ARnss with hardcoded Partitions.

For example this AWS::Lambda::Permission

```
    "rCfnNagNotficationLambdaDevelopCfnNagPermission": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:InvokeFunction",
        "Principal": "logs.amazonaws.com",
        "FunctionName": {
          "Ref": "rCfnNagNotficationLambda"
        },
        "SourceArn": {
          "Fn::Sub": [
            "arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:${__LogGroupName__}:*",
            {
              "__LogGroupName__": {
                "Fn::GetAtt": [
                  "rDevelopPipeline",
                  "Outputs.oCfnNagLogGroupName"
                ]
              }
            }
          ]
        }
      }
```
Or this ManagedPolicyArn in this AWS::IAM::Role

```
    "rUploadCustomCfnNagRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ]
        },
        "ManagedPolicyArns": [
          "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        ],
        "Policies": [
          {
            "PolicyName": "rUploadCustomCfnNagRolePolicy0",
            "PolicyDocument": {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Action": [
                    "s3:PutObject",
                    "s3:DeleteObject"
                  ],
                  "Resource": [
                    {
                      "Fn::Sub": "${rCustomCFNNagRulesBucket.Arn}/*"
                    }
                  ],
                  "Effect": "Allow"
                },
                {
                  "Action": [
                    "logs:CreateLogGroup",
                    "logs:CreateLogStream",
                    "logs:PutLogEvents"
                  ],
                  "Resource": "*",
                  "Effect": "Allow"
                }
              ]
            }
          }
        ],
        "Tags": [
          {
            "Value": "SAM",
            "Key": "lambda:createdBy"
          },
          {
            "Value": {
              "Fn::Sub": "${pProjectName}-cfnnag-upload-lambda"
            },
            "Key": "Name"
          }
        ]
      },
      "Condition": "cCfnNagStyleRules"
    }
```
I propose that Pseudo Parameters get used instead.

**Comment by sriram-mv** [comment]
Can you add additional details? AWS::Partition is definitely supported and not hardcoded.

**Comment by jfuss** [comment]
In some cases, we get the Partition from the region you are launched in: https://github.com/awslabs/serverless-application-model/blob/28884c958dfaa1c547e0f0e4ae2b8129f52e34dd/samtranslator/translator/arn_generator.py#L31 

So while the this is not exactly what you are after, we are Partition aware.

On the managed policy, construct the arn in a similar fashion: https://github.com/awslabs/serverless-application-model/blob/28884c958dfaa1c547e0f0e4ae2b8129f52e34dd/samtranslator/translator/arn_generator.py#L20

**Comment by dontirun** [comment]
I am using the [cfn-python-lint](https://github.com/aws-cloudformation/cfn-python-lint) package created by the CloudFormation team. It runs its linting on scripts after they have been translated.

**Comment by jfuss** [comment]
@dontirun While adding {AWS::Partition} can be used to validate its partition aware, it doesn't cover everything. We can update to use this (though it really doesn't matter since SAM is deployed to the region it operates in and therefore is partition aware). 

We would need to validate that this change does not cause a cascading deployment affect. That is would updating to {AWS::Partition} cause resources to be redeployed of a resource? 

Are you interested in taking this up?

**Comment by dontirun** [comment]
Yes, I would be glad to help.

**Comment by dontirun** [comment]
I ran a small test with creating an IAM role. I'm happy to report that the CloudFormation did not  attempt to update the IAM role when I replaced aws with  !Sub .... ${AWS::Partition}

Please let me know if you would like me to perform additional tests.

**Steps**
1. Deploy Template 1 into test stack
2. Attempt to update test stack with Template 2
   * CloudFormation throws warning on creating change set ![image](https://user-images.githubusercontent.com/4570879/81750784-27095500-947c-11ea-9f9e-4ff1eae10cee.png)
   * CloudFormation throws error on attempting to update
![image](https://user-images.githubusercontent.com/4570879/81750819-3a1c2500-947c-11ea-9daa-95ef81d5a3a3.png)


**Template1**
```
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Checks if CloudFormation Resources Update if the same value is subbed in for a
  Ref
Resources:
  rMyLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              print('hi')
      Description: Print hi
      Tags:
        - Value: SAM
          Key: 'lambda:createdBy'
      MemorySize: 128
      Handler: index.lambda_handler
      Role: !GetAtt 
        - rMyLambdaRole
        - Arn
      Timeout: 30
      Runtime: python3.7
  rMyLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole'
      Tags:
        - Value: SAM
          Key: 'lambda:createdBy'
  rMyLambdarCWSchedule:
    Type: 'AWS::Events::Rule'
    Properties:
      State: DISABLED
      ScheduleExpression: rate(1 minute)
      Targets:
        - Id: rMyLambdarCWScheduleLambdaTarget
          Arn: !GetAtt 
            - rMyLambda
            - Arn
  rMyLambdarCWSchedulePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      Principal: events.amazonaws.com
      FunctionName: !Ref rMyLambda
      SourceArn: !GetAtt 
        - rMyLambdarCWSchedule
        - Arn
```
I made a similar template wehre I used a !Sub in the ManagedPolicyArnsL

**Template2**
```
AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Checks if CloudFormation Resources Update if the same value is subbed in for a
  Ref
Resources:
  rMyLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Code:
        ZipFile: |
          def lambda_handler(event, context):
              print('hi')
      Description: Print hi
      Tags:
        - Value: SAM
          Key: 'lambda:createdBy'
      MemorySize: 128
      Handler: index.lambda_handler
      Role: !GetAtt 
        - rMyLambdaRole
        - Arn
      Timeout: 30
      Runtime: python3.7
  rMyLambdaRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action:
              - 'sts:AssumeRole'
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - !Sub >-
          arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Tags:
        - Value: SAM
          Key: 'lambda:createdBy'
  rMyLambdarCWSchedule:
    Type: 'AWS::Events::Rule'
    Properties:
      State: DISABLED
      ScheduleExpression: rate(1 minute)
      Targets:
        - Id: rMyLambdarCWScheduleLambdaTarget
          Arn: !GetAtt 
            - rMyLambda
            - Arn
  rMyLambdarCWSchedulePermission:
    Type: 'AWS::Lambda::Permission'
    Properties:
      Action: 'lambda:InvokeFunction'
      Principal: events.amazonaws.com
      FunctionName: !Ref rMyLambda
      SourceArn: !GetAtt 
        - rMyLambdarCWSchedule
        - Arn
```
