### ISSUE TITLE
Typo in Attribute value for Serverless::Function

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/serverless-application-model#16]
Hi,

 There is currently a [typo in the attribute value](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#fngetatt) returned out of a *Serverless:Function* resource - It should be **Arn** instead of **FunctionArn**.

**This works**

```yaml
Outputs:
    MyFunction:
      Description: "My Function ARN"
      Value: !GetAtt MyFunctionResource.Arn
```

**This doesn't work**

```yaml
Outputs:
    MyFunction:
      Description: "My Function ARN"
      Value: !GetAtt MyFunctionResource.FunctionArn
```
