### ISSUE TITLE
Translate local file strings to AWS::Include transform

### ISSUE THREAD

**Issue by jdub** [awslabs/serverless-application-model#160]
There are quite a few issues on this repo related to variable substitution in separate YAML files, particularly dealing with `x-amazon-apigateway-integration`'s `uri` parameter.

What if, instead of `aws cloudformation package` translating a local file string to an `s3://` URI, it translated it to an AWS::Include transform?

This SAM / CloudFormation template:

```yaml
Resources:
  Api:
    Properties:
      DefinitionUri: ./swagger.yaml
```

… currently translates to:

```yaml
Resources:
  Api:
    Properties:
      DefinitionUri: s3://bucket/swagger.yaml
```

… but could instead translate to:

```yaml
Resources:
  Api:
    Properties:
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: s3://bucket/swagger.yaml
```
