### ISSUE TITLE
ERROR: Mappings attribute {abc} must contain only alphanumeric characters

### ISSUE THREAD

**Issue by tvishwanatharkin** [awslabs/serverless-application-model#1608]
**Description:**

Mapping attribute must contain only alphanumeric characters.
I am trying to deploy an application using sam deploy. My cloudformation template looks some what like this

```
Mappings:
  EnvToRoleMap:
    MY-DEV:
      LAMBDA_EXECUTION_ROLE: arn:aws:iam::1234566777:role/Role1
    MY-STAGING:
      LAMBDA_EXECUTION_ROLE: arn:aws:iam::9876521332:role/Role2
```
This fails when sam build is run 
`Reason: Template format error: Mappings attribute name 'LAMBDA_EXECUTION_ROLE' must contain only alphanumeric characters.`
What's considered as alphanumeric here? 

**Steps to reproduce the issue:**
1. Create a mapping with Role ARN
2. Execute sam build and sam deploy

**Observed result:**
`Reason: Template format error: Mappings attribute name 'LAMBDA_EXECUTION_ROLE' must contain only alphanumeric characters.`

**Expected result:**
Mappings should treat mapping attribute values like any other String

**Comment by tvishwanatharkin** [comment]
Figured out that the attribute name should not have special characters. Changed it to Camelcase syntax which worked. 
However, the error is not thrown for top level key
```
EnvToAccNumberMap:
    MY-STAGING:
      LambdaExecutionRole: "xyz"
    MY-PRODUCTION:
      LambdaExecutionRole: "xyz"
```

**Comment by raunak-mali-incontact** [comment]
Mapping attribute doesnt support underscore or dash

**Comment by raunakmali** [comment]
Mapping attribute doesnt support underscore or dash

**Comment by rambabusaravanan** [comment]
My env files have NODE_ENV, APP_ENV, DB_HOSTNAME which is very very common practice and I tried to use SAM like this

```yaml
Mappings:
  Environment:
    test:
      Fn::Transform:
        Name: AWS::Include
        Parameters:
          Location: env.test.json
    dev:
      Fn::Transform:
        Name: AWS::Include
        Parameters:
          Location: env.dev.json

Resources:
  MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          NODE_ENV: !FindInMap [Environment, !Ref StageName, NODE_ENV]
          APP_ENV: !FindInMap [Environment, !Ref StageName, APP_ENV]
          DB_HOSTNAME: !FindInMap [Environment, !Ref StageName, DB_HOSTNAME]
```
This throws the error
> Error: Mappings attribute name 'DB_HOSTNAME' must contain only alphanumeric characters

Already SAM enforces a lot of restriction the way we code and now forcing us to use CamelCase for env variables.

@jfuss can you please help with a solution for this?
Or Is there any other better way to include env from file as per the provided StageName parameter?
