### ISSUE TITLE
S3 Events using a filter not working?

### ISSUE THREAD

**Issue by seeebiii** [awslabs/serverless-application-model#163]
Hi, maybe I just do not understand the [documentation for S3 as an event source](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#s3) right, but I'd assume that the following template should work:

```
  S3Listener:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.MyListener
      Runtime: java8
      CodeUri: target/example.jar
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Action: 's3:*'
              Resource:
                - !Sub arn:aws:s3:::${MyBucket}        # for listObjects access
                - !Sub arn:aws:s3:::${MyBucket}/*     # for access to the bucket objects
      Events:
        S3FileListener:
          Type: S3
          Properties:
            Bucket: !Ref MyBucket            # bucket is declared in the same template
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.jpg'
```

I assume that my Lambda is called if a file ending with '.jpg' is uploaded to MyBucket. From my understanding, this should be supported by SAM according to the documentation linked above. Is something wrong with this template or is the documentation lacking some kind of information? This template is deployed using `aws cloudformation package` and `aws cloudformation deploy`. The latter gets aborted after some time. In the stack details I can see that an entry for a new stack change set has been added, but it just displays "CREATE_IN_PROGRESS". Deleting the change set results in an error. Also the stack is never updated, because the change set did not finish. Maybe also important to know: if I leave out the complete "Filter: " object, the stack update behaves like expected.

I hope you can help me!

**Comment by seeebiii** [comment]
**Update on this:** I've figured out that the template above results in a circular dependency (which is not obvious to see). You can't use `!Ref MyBucket` in `Events` together with a policy statement containing a reference/substitution to `MyBucket` as well. I assume this is due to the Lambda Role which waits for `MyBucket` to be resolved to add the name into the policy statement and the bucket waits for the Lambda to be created so that an event notification can be added.

My solution to this problem is that I just add the bucket name directly into the resource ARN. In my case the bucket name needs to be generated like this:

```
  S3Listener:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.example.MyListener
      Runtime: java8
      CodeUri: target/example.jar
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: "Allow"
              Action: 's3:*'
              Resource:
                - !Sub
                  - arn:aws:s3:::${_bucket}       # for listObjects access
                  - { _bucket: !Join ['-', ['my', 'bucket']] }
                - !Sub
                  - arn:aws:s3:::${_bucket}/*     # for access to the bucket objects
                  - { _bucket: !Join ['-', ['my', 'bucket']] }
      Events:
        S3FileListener:
          Type: S3
          Properties:
            Bucket: !Ref MyBucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: '.jpg'
```


The big problem was that my original template (containing multiple dynamo dbs, buckets and lots of SAM Lambda functions) did not say that there is such a circular dependency. It just waited endlessly to create a ChangeSet. I've just figured it out using a small test project with a simple setup: one Lambda and one bucket. In that case the error was shown directly.
