### ISSUE TITLE
serverless_app_plugin transforms ApplicationId to us-east-1

### ISSUE THREAD

**Issue by NathanYocum** [awslabs/serverless-application-model#1632]
**Description:** The serverless_app_plugin transforms SAR application id's to us-east-1 regardless of region / defaults. This makes it so transforming the template can only occur in us-east-1 if the SAR is published in that region.

Not 100% sure if this is a bug with `sam build`'s usage of the lifecycle hooks or with the hook's resolution value always being us-east-1

**Steps to reproduce the issue:**
Reproduction repo: https://github.com/NathanYocum/sam-sar-bug - includes a SAR application to publish and a consumer of the Application
0. Using aws-sam-cli==0.53.0
1. Package an AWS::ServerlessRepo::Application into us-east-1 and us-east-2
2. Create a sam template that uses the application through a mapping:
```
Mappings:
  SAMBuildTest:
    us-east-1:
      ApplicationId: arn:aws:serverlessrepo:us-east-1:854484851566:applications/sam-build-test
      SemanticVersion: 0.0.2
    us-east-2:
      ApplicationId: arn:aws:serverlessrepo:us-east-2:854484851566:applications/sam-build-test
      SemanticVersion: 0.0.2
Resources:
  SAMBuildSAR:
    Type: AWS::Serverless::Application
    Properties:
      Location:
        ApplicationId: !FindInMap [ SAMBuildTest, !Ref AWS::Region, ApplicationId ]
        SemanticVersion: !FindInMap [ SAMBuildTest, !Ref AWS::Region, SemanticVersion ]
```
3. Run `sam build --region us-east-2` on the template

**Observed result:**
```
[InvalidResourceException('SAMBuildSAR', 'Application with id arn:aws:serverlessrepo:us-east-1:854484851566:applications/sam-build-test could not be found.')] ('SAMBuildSAR', 'Application with id arn:aws:serverlessrepo:us-east-1:854484851566:applications/sam-build-test could not be found.')
```
When I dug into it I found https://github.com/awslabs/serverless-application-model/blob/develop/samtranslator/plugins/application/serverless_app_plugin.py#L90 was causing the application id to get replaced with us-east-1 instead of whatever `AWS_DEFAULT_REGION`, my `~/.aws/config`, or my flag was set to.

**Expected result:**
Transform succeeds in all regions regardless of arg.
