### ISSUE TITLE
CORS problem when using User Pool authentication

### ISSUE THREAD

**Issue by GregSommerville** [awslabs/serverless-application-model#1633]
**Description:**
I have a SAM template that creates an API which is authenticated using Cognito user pools.  I've set up CORS to allow everything, but when I try to call the API with a DELETE method, I get an error saying that the call was blocked by CORS policy.  Originally I wrote the API to not use authentication, and that was working.  Adding authentication seems to have introduced a problem.

Here's the start of my template:
```
Globals:
  Api:
    Auth:
        DefaultAuthorizer: CognitoAuthorizer
        AddDefaultAuthorizerToCorsPreflight: False
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'" 
      AllowOrigin: "'*'"


```
All GET and POST methods work fine, but a DELETE causes a CORS issue.

Does anyone have an idea of what's going wrong?  Thanks!
