### ISSUE TITLE
Unable to use cross-account token lambda authorizer with SAM template

### ISSUE THREAD

**Issue by xiananfan** [awslabs/serverless-application-model#1637]
**Description:**

We have 2 AWS accounts, let's say account A and account B. Account A contains a lambda authorizer we want to use in Account B with API Gateway as a token authorizer. Using the classic cloud formation template, we will be able to create the authorizer reference in account B, and it will not attempt to modify the authorizer in account A to update its resource-based policy to allow cross-account access. The CFT deployment will be able to complete without problems.

However, using SAM syntax like below will cause the CFT deployment to fail:
```
# template.yaml, intended to be deployed in Account B
    TestAuthServiceGateway:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref Environment
            OpenApiVersion: '3.0.0'
            Auth:
                DefaultAuthorizer: MyAuthorizerInAccountA
                Authorizers:
                    MyAuthorizerInAccountA:
                        FunctionArn: arn:aws:lambda:us-west-2:<AccountA>:function:dev-us-west-2-StandardAuthorizer
                        FunctionPayloadType: 'TOKEN'
                        Identity:
                            ReauthorizeEvery: 0 # disable cache
                            ValidationExpress: ^Bearer [a-zA-Z0-9\-_]+?\.[a-zA-Z0-9\-_]+?\.([a-zA-Z0-9\-_]+)?$
```
The reason is the user who triggered this deployment is currently in Account B and does not have permission to modify the authorizer in Account A.

The error CFT gives looks like below:
```
User: arn:aws:iam::<AccountB>:user/CICD is not authorized to perform: lambda:AddPermission on resource: arn:aws:lambda:us-west-2:<AccountA>:function:dev-us-west-2-StandardAuthorizer (Service: AWSLambda; Status Code: 403; Error Code: AccessDeniedException; Request ID: 964a7be1-fb95-4759-8c2d-11476c74630b)
```

My questions are:
1. Is there a way to setup IAM role/policy/trust relationship, such that user in Account B, at cloudformation deployment time, can have the permission to modify cross-account authorizer's resource-based policy? This [wiki](https://docs.amazonaws.cn/en_us/lambda/latest/dg/access-control-resource-based.html) does not suggest "lambda:AddPermission" is a supported API in resourced-based policy. I also gave it a try, and could not get it to work.
2. Is it possible to suggest a feature request that do not set the authorizer's resource policy at deployment time? And assume it's already done outside out cloud formation? (This is a one-time thing either way). Something similar to this "[AddDefaultAuthorizerToCorsPreflight](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-property-api-apiauth.html#sam-api-apiauth-adddefaultauthorizertocorspreflight)" flag? 

**Steps to reproduce the issue:**
1. Create an lambda authorizer in Account A
2. Trying to deploy a SAM template in Account B referencing the token authorizer in Account A
3. See the failure in cloud formation saying it does not have permission to modify the resource-based policy of authorizer

**Observed result:**
Unable to modify authorizer resource-based policy in Account A

**Expected result:**
Able to modify given appropriate cross-account permission setup, or allow disable this step of updating the authorizer's resource policy.

**Comment by denniskribl** [comment]
Just stumbled across the same problem. The workaround is to mix the SAM Serverless::Api with the classic cloudformation ApiGateway::Authorizer resource. 

imo modifying the resource should be optional. Looking forward to the discussion here

**Comment by denniskribl** [comment]
If the outcome of this issue results in code changes, I'll happily contribute as this issue is really bothering me and my team :smile:

**Comment by icj217** [comment]
Also running into this issue

**Comment by icj217** [comment]
Ended up creating a very simple custom macro to do this for me.

Macro stack:

```yaml
Description: Remove Authorizer Lambda Permissions
AWSTemplateFormatVersion: "2010-09-09"
Transform: [AWS::Serverless-2016-10-31]

Resources:
  RemoveAuthorizerLambdaPermissionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      Description: CFN Macro function that removes AWS::Lambda::Permission resources associated with lambda authorizers
      Runtime: python3.7
      Handler: index.handler
      InlineCode: |
        def handler(event, context):
          print("Got a request", str(event))
          # Get list of resources to be deleted
          resources = [name for name in event['fragment']['Resources'] if name.endswith('AuthorizerPermission')]
          # Delete them from template
          for resource in resources:
            print('Deleting authorizer permission:', resource)
            event['fragment']['Resources'].pop(resource)
          # Return template to CFN
          return { "requestId": event["requestId"], "status": "success", "fragment": event["fragment"] }
  RemoveAuthorizerLambdaPermissionsMacro:
    Type: AWS::CloudFormation::Macro
    Properties:
      Name: RemoveAuthorizerLambdaPermissions
      Description: Removes AWS::Lambda::Permission resources associated with lambda authorizers
      FunctionName:
        Ref: RemoveAuthorizerLambdaPermissionsFunction
```

Once the above stack is deployed, you can simply add the macro to to your API stack's `Transform`:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: [AWS::Serverless-2016-10-31, RemoveAuthorizerLambdaPermissions]

  DeidApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: my-api
      Auth:
        DefaultAuthorizer: MyFn
        Authorizers:
          MyTokenFn:
            ...
```

Not ideal but it works for our use case 🤷

**Comment by brysontyrrell** [comment]
+1 It would be beneficial for orgs where there is a centrally managed authorizer to be able to deploy stacks that aren't trying to also create the permission.

**Comment by santiperone** [comment]
@sriram-mv I'm having this exact same issue. Any updates on this subject?

**Comment by santiperone** [comment]
I thik it should be possible to add an attribute like "AddPermissions" which defaults to true (to maintain current behaviour) here: https://github.com/aws/serverless-application-model/blob/e62dcfc6ed2ea3b4f3473e7797ee0663f4e06302/samtranslator/model/api/api_generator.py#L1113-L1133

**Comment by cortexcompiler** [comment]
I found that you can work around this issue if you specify your Authorizer in an OpenAPI Spec file, this way SAM does not attempt to create the `AWS::Lambda::Permission`.  You will need to manage the permissions for the Lambda in the target account. Snippets:
**template.yaml:**
```yaml
  Api:
    Type: AWS::Serverless::Api
    Properties:
        ...
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: api/openapi-spec.yaml
```

open-api-spec.yaml
```yaml
  securitySchemes:
    TokenAuthorizer:
      type: apiKey
      name: Authorization
      in: cookie
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        type: request
        identitySource: method.request.header.Cookie
        authorizerUri:
          'Fn::Sub': 'arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CrossAccountAuhtorizerARN}/invocations'
        authorizerResultTtlInSeconds: 600
```
Don't forget your alias on your Lambda ARN if used.  Ensure you do not specify the `authorizerCredentials` in the [x-amazon-apigateway-authorizer](https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-swagger-extensions-authorizer.html).

Other examples of an authorizer definition in an OpenAPI Spec:
- [aws-iot-builder-tools/iot-provisioning-secretfree/api-definition.yaml](https://github.com/aws-iot-builder-tools/iot-provisioning-secretfree/blob/4f015f08f93fa740f324ae45f2d92d018d7b9829/api-definition.yaml#L53)
- [aws-samples/serverless-coffee/backends/5-order-manager/RestAPIs/api.yaml](https://github.com/aws-samples/serverless-coffee/blob/082d2e3050cad7d095d13c6414a09632605a9da6/backends/5-order-manager/RestAPIs/api.yaml#L323)
- [linkai-io/cf_templates_mod/templates/am-console-api.yaml](https://github.com/linkai-io/cf_templates_mod/blob/fa5c3efb3c7ec1db1bb5542ba5c5cc1498b4391b/templates/am-console-api.yaml#L1691)
