### ISSUE TITLE
AWS::ApiGatewayV2::Integration and AWS::ApiGatewayV2::Route deleted after updating stack

### ISSUE THREAD

**Issue by rvadim** [awslabs/serverless-application-model#1650]
**Description:**

API Gateway route /versions which points to S3 object was deleted after updating /api/ specific route with lambda.
Source template:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: ""

Globals:
  Function:
    Timeout: 20

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "bucket-name-${AWS::StackName}"
  S3BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement:
          -
            Effect: Allow
            Action: 's3:GetObject'
            Resource:
              - !Sub "arn:aws:s3:::${S3Bucket}/*"
            Principal: "*"
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowHeaders: ['*']
        AllowMethods: ['*']
        AllowOrigins: ['*']
      Domain:
        DomainName: example.com
        CertificateArn: arn
        Route53:
          HostedZoneId: zone-id
  APIVersionsIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: HTTP_PROXY
      IntegrationUri: !Sub "https://${S3Bucket}.s3-${AWS::Region}.amazonaws.com/versions.json"
      IntegrationMethod: GET
      PayloadFormatVersion: "1.0"
  APIVersionsRoute:
    Type: AWS::ApiGatewayV2::Route
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: 'GET /versions'
      Target: !Join
        - /
        - - integrations
          - !Ref APIVersionsIntegration
  KCSmaster:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/master
      Handler: com.compiler.server.lambdas.StreamLambdaHandler::handleRequest
      Runtime: java8
      MemorySize: 2048
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/{proxy+}
            Method: any
            PayloadFormatVersion: "1.0"
  KCSmasterOld:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/master
      Handler: com.compiler.server.lambdas.StreamLambdaHandler::handleRequest
      Runtime: java8
      MemorySize: 2048
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /Server
            Method: any
            PayloadFormatVersion: "1.0"
  KCS1372:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/1.3.72
      Handler: com.compiler.server.lambdas.StreamLambdaHandler::handleRequest
      Runtime: java8
      MemorySize: 2048
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/1.3.72/{proxy+}
            Method: any
            PayloadFormatVersion: "1.0"
  KCS14m2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas/1.4-M2
      Handler: com.compiler.server.lambdas.StreamLambdaHandler::handleRequest
      Runtime: java8
      MemorySize: 2048
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /api/1.4-M2/{proxy+}
            Method: any
            PayloadFormatVersion: "1.0"
```
versions.json:
```
[
  {
    "version": "1.4-M3"
  },
  {
    "version": "1.3.72",
    "latestStable": true
  }
]
```
Patch:
```
--- a/template.yaml
+++ b/template.yaml
@@ -104,10 +104,10 @@ Resources:
             Path: /api/1.3.72/{proxy+}
             Method: any
             PayloadFormatVersion: "1.0"
-  KCS14m2:
+  KCS14m3:
     Type: AWS::Serverless::Function
     Properties:
-      CodeUri: lambdas/1.4-M2
+      CodeUri: lambdas/1.4-M3
       Handler: com.compiler.server.lambdas.StreamLambdaHandler::handleRequest
       Runtime: java8
       MemorySize: 2048
@@ -116,7 +116,7 @@ Resources:
           Type: HttpApi
           Properties:
             ApiId: !Ref HttpApi
-            Path: /api/1.4-M2/{proxy+}
+            Path: /api/1.4-M3/{proxy+}
             Method: any
             PayloadFormatVersion: "1.0"
```

**Steps to reproduce the issue:**
1. Deploy source stack
2. Curl apigateway endpoint /versions -> 200
3. Apply patch
4. Deploy again
5. Curl apigateway endpoint /versions -> 404

**Observed result:**
```
Uploading to kcs-prod/c63a38241d610b16d311a32fc3aa60fb.template  4062 / 4062.0  (100.00%)
Waiting for changeset to be created..

CloudFormation stack changeset
------------------------------------------------------------------------------------------------
Operation                        LogicalResourceId                ResourceType                   
------------------------------------------------------------------------------------------------
+ Add                            KCS14m3ApiEventPermission        AWS::Lambda::Permission        
+ Add                            KCS14m3Role                      AWS::IAM::Role                 
+ Add                            KCS14m3                          AWS::Lambda::Function          
* Modify                         APIVersionsIntegration           AWS::ApiGatewayV2::Integration 
* Modify                         APIVersionsRoute                 AWS::ApiGatewayV2::Route       
* Modify                         HttpApiApiGatewayDefaultStage    AWS::ApiGatewayV2::Stage       
* Modify                         HttpApiApiMapping                AWS::ApiGatewayV2::ApiMapping  
* Modify                         HttpApi                          AWS::ApiGatewayV2::Api         
* Modify                         KCS1372ApiEventPermission        AWS::Lambda::Permission        
* Modify                         KCS1372                          AWS::Lambda::Function          
* Modify                         KCSmasterApiEventPermission      AWS::Lambda::Permission        
* Modify                         KCSmasterOldApiEventPermission   AWS::Lambda::Permission        
* Modify                         KCSmasterOld                     AWS::Lambda::Function          
* Modify                         KCSmaster                        AWS::Lambda::Function          
- Delete                         KCS14m2ApiEventPermission        AWS::Lambda::Permission        
- Delete                         KCS14m2Role                      AWS::IAM::Role                 
- Delete                         KCS14m2                          AWS::Lambda::Function          
------------------------------------------------------------------------------------------------

Changeset created successfully.

2020-07-06 11:34:56 - Waiting for stack create/update to complete

CloudFormation events from changeset
-------------------------------------------------------------------------------------------------
ResourceStatus           ResourceType             LogicalResourceId        ResourceStatusReason   
-------------------------------------------------------------------------------------------------
CREATE_IN_PROGRESS       AWS::IAM::Role           KCS14m3Role              Resource creation      
                                                                           Initiated              
UPDATE_IN_PROGRESS       AWS::Lambda::Function    KCSmaster                -                      
UPDATE_IN_PROGRESS       AWS::Lambda::Function    KCS1372                  -                      
UPDATE_IN_PROGRESS       AWS::Lambda::Function    KCSmasterOld             -                      
CREATE_IN_PROGRESS       AWS::IAM::Role           KCS14m3Role              -                      
UPDATE_COMPLETE          AWS::Lambda::Function    KCSmasterOld             -                      
UPDATE_COMPLETE          AWS::Lambda::Function    KCSmaster                -                      
UPDATE_COMPLETE          AWS::Lambda::Function    KCS1372                  -                      
CREATE_COMPLETE          AWS::IAM::Role           KCS14m3Role              -                      
CREATE_IN_PROGRESS       AWS::Lambda::Function    KCS14m3                  -                      
CREATE_COMPLETE          AWS::Lambda::Function    KCS14m3                  -                      
CREATE_IN_PROGRESS       AWS::Lambda::Function    KCS14m3                  Resource creation      
                                                                           Initiated              
UPDATE_IN_PROGRESS       AWS::ApiGatewayV2::Api   HttpApi                  -                      
UPDATE_COMPLETE          AWS::ApiGatewayV2::Api   HttpApi                  -                      
CREATE_IN_PROGRESS       AWS::Lambda::Permissio   KCS14m3ApiEventPermiss   Resource creation      
                         n                        ion                      Initiated              
CREATE_IN_PROGRESS       AWS::Lambda::Permissio   KCS14m3ApiEventPermiss   -                      
                         n                        ion                                             
CREATE_COMPLETE          AWS::Lambda::Permissio   KCS14m3ApiEventPermiss   -                      
                         n                        ion                                             
UPDATE_COMPLETE_CLEANU   AWS::CloudFormation::S   kcs-prod                 -                      
P_IN_PROGRESS            tack                                                                     
DELETE_IN_PROGRESS       AWS::Lambda::Permissio   KCS14m2ApiEventPermiss   -                      
                         n                        ion                                             
DELETE_IN_PROGRESS       AWS::Lambda::Function    KCS14m2                  -                      
DELETE_COMPLETE          AWS::Lambda::Permissio   KCS14m2ApiEventPermiss   -                      
                         n                        ion                                             
DELETE_COMPLETE          AWS::Lambda::Function    KCS14m2                  -                      
DELETE_IN_PROGRESS       AWS::IAM::Role           KCS14m2Role              -                      
UPDATE_COMPLETE          AWS::CloudFormation::S   kcs-prod                 -                      
                         tack                                                                     
DELETE_COMPLETE          AWS::IAM::Role           KCS14m2Role              -                      
-------------------------------------------------------------------------------------------------
```
Deploy was successful, but /versions integration deleted and users get 404 when try to access endpoint.
```
{"message":"Not Found"}
```
There are no /versions route in UI of API Gateway also integration is deleted

**Expected result:**
Keep custom API Gateway routes when deploy new versions of another routes.
