### ISSUE TITLE
HTTP API documentation inconsistency

### ISSUE THREAD

**Issue by rts-rob** [awslabs/serverless-application-model#1657]
**Description:**

Building an AWS SAM application I found what seems to be an inconsistency between the docs and the AWS SAM CLI behavior.
 
On [this page of the docs](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-httpapi.html#sam-httpapi-definitionuri) it says:

> AWS S3 Uri, local file path, or location object of the the OpenAPI document defining the API.
> …
> If a local file path is provided, the template must go through the workflow that includes the `sam deploy` or `sam package` command, in order for the definition to be transformed properly.

When I attempt to define an HTTP API using the _DefinitionUri_ key and a local filename as the value, I get an error.

**Steps to reproduce the issue:**
1. In an AWS SAM template, define the following resource:
    ```yaml
    Resources:
      PassthroughAPI:
        Type: AWS::Serverless::HttpApi
        Properties:
          DefinitionUri: api-definition.yaml
    ```
1. In a file _api-definition.yaml_ in the same directory, define a simple API that proxies all traffic to a remote host:
    ```yaml
    openapi: "3.0.1"
    info:
      title: "Mainframe to serverless migration"
      version: "0.1.0"
     
    paths:
      /{proxy+}:
        x-amazon-apigateway-any-method:
          responses:
            default:
              description: "Default response for ANY /"
          x-amazon-apigateway-integration:
            payloadFormatVersion: "1.0"
            type: "http_proxy"
            httpMethod: "ANY"
            uri: "https://github.com/{proxy}"
            connectionType: "INTERNET"
    ```
3. Build the AWS SAM application with `sam build`
4. Deploy the AWS SAM application with `sam deploy`

**Observed result:**

> Waiting for changeset to be created..
> Error: Failed to create changeset for the stack: mainframe-migration, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [PassthroughAPI] is invalid. 'DefinitionUri' is not a valid S3 Uri of the form 's3://bucket/key' with optional versionId query parameter.

**Expected result:**

An HTTP API is created using the definition in api-definition.yaml

**Additional information:**
Flagging per conversation with @therealjeffg

I propose updating to match the documentation. I have pasted a workaround below but the _DefinitionUri_: _<filename>_ pattern is much cleaner. It would be ideal if support matched the _DefinitionUri_ + _DefinitionSubstitutions_ pattern used in AWS SAM support for AWS Step Functions.

**Workaround:**
In _template.yaml_:
```yaml
Resources:
  PassthroughAPI:
    Type: AWS::Serverless::HttpApi
    Properties:
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: api-definition.yaml
```
