### ISSUE TITLE
sam package and sam build refer to different locations for layers

### ISSUE THREAD

**Issue by johnt337** [awslabs/serverless-application-model#1658]
**Description:**
While working with SAM to build a serverless app using both functions and layers locally appears to refer to different locations
depending on if I am building or deploying.

It appears that when you do `sam build` it copies your `CodeUri` content to a tmp dir and exposes `$(ARTIFACTS_DIR)`. Which is a pointer to `$PWD/.aws-sam/build/<logical-resource-id>` . However, when you run `sam package` it bundles from `CodeUri`

My project has the following structure:
```bash
.aws-sam/build/
Lambda/ # my lambda code is staged here
LayerOne/Makefile
LayerOne/requirements.txt
LayerOne/python # all staged modules are located here
```

**Steps to reproduce the issue:**
1. Create a layer based on instructions from [here](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/building-layers.html) 
2. Use a `CodeUri` of `Layer1` with a config similar too:
SAM Template:
```yaml
  LayerOne:
    Type: "AWS::Serverless::LayerVersion"
    Properties:
      LayerName: layer_one
      CompatibleRuntimes:
        - python3.7
      ContentUri: LayerOne/
      Description: Common code for Lambdas
      LicenseInfo: MIT
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile
```

3. Define a `Makefile`:
```Makefile
Makefile:
```
requirements.txt:
	pipenv lock -r > ./requirements.txt

build-LayerOne: requirements.txt
	$(info [+] Installing '3rd party' dependencies...)
	pipenv run pip3 install \
			--isolated \
			--disable-pip-version-check \
			-Ur requirements.txt -t $(ARTIFACTS_DIR)/python
	cp -f ./requirements.txt $(ARTIFACTS_DIR)/python/
```

3. Build:
```bash
sam build LayerOne
```

4. Package:
```bash
	sam package \
		--template-file template.yaml \
		--output-template-file packaged.yaml \
		--s3-bucket ${BUCKET} \
		--s3-prefix ${BUCKET_PREFIX}
```
5. Deploy
```
	sam deploy \
	  --no-fail-on-empty-changeset \
          --template-file packaged.yaml \
	  --stack-name ${STACK_NAME} \
	  --s3-bucket ${BUCKET} \
	  --s3-prefix stacks \
  	  --capabilities CAPABILITY_IAM CAPABILITY_AUTO_EXPAND
```
**Observed result:**
When you download the layer, the only files that will be bundled will be `requirements.txt` because the pip install
targeted the `$(ARTIFACTS_DIR)` and did not stage to `CodeUri/python`

**Expected result:**
The layer should contain the entire contents of `$(ARTIFACTS_DIR)`

6. Revise your `Makefile`
Makefile:
```
build-LayerOne: configure
	ls -latr > $(ARTIFACTS_DIR)/log 
	pwd >> $(ARTIFACTS_DIR)/log  
	cp -fa ./python $(ARTIFACTS_DIR)/ 
	cp -f ./requirements.txt $(ARTIFACTS_DIR)/python/

requirements.txt:
	pipenv lock -r > ./requirements.txt

configure: ./requirements.txt
	$(info [+] Installing '3rd party' dependencies...)
	pipenv run pip3 install \
			--isolated \
			--disable-pip-version-check \
			-Ur requirements.txt -t ./python
```
7. Re-run steps 3, 4, & 5

**Observed result:**
When you download the layer, all files that are in `CodeUri/python` will be visible.
