### ISSUE TITLE
DefinitionUri for AWS::Serverless::StateMachine errors if it contains a - character

### ISSUE THREAD

**Issue by jbesw** [awslabs/serverless-application-model#1660]
Hyphen/dash character in DefinitionUrl causes error - error message does not indicate this is the problem.

### Description

Deploying a template with a Uri like this:

```
  ResizerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: definitions/1-resizer.asl.json
```
...causes the error "Property validation failure: [Encountered unsupported properties in {/}: [DefinitionUri]]" Removing the dash, it deploys correctly.

### Steps to reproduce

Deploy a state machine with a dash in the DefinitionUri.

### Observed result

 "Property validation failure: [Encountered unsupported properties in {/}: [DefinitionUri]]" 

### Expected result
Either:
1. Successful deployment (dash accepted).
2. Error indicating that the dash character is problematic, not the "/" character as shown.

### Additional environment details (Ex: Windows, Mac, Amazon Linux etc)

1. OS: Windows
2. `sam --version`: 0.53.0

`Add --debug flag to command you are running`

**Comment by mndeveci** [comment]
Hi @jbesw , can you run the following command (`sam validate --debug`) and provide the value for `DefinitionUri` in generated CFN template?

**Comment by aaronlelevier** [comment]
Hi, I am getting the same error. This is what I got when I ran `sam validate --debug` which came back as valid.

```yaml
CustomResourceStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionUri: statemachine/main.asl.json
```

**Comment by hoffa** [comment]
The SAM transform doesn't support local paths, while SAM CLI does.

I tried reproducing with the SAM transform using the closest valid template:

```yaml
Transform: AWS::Serverless-2016-10-31
Resources:
  ResizerStateMachine:
    Type: AWS::Serverless::StateMachine
    Properties:
      DefinitionUri: s3://foo-bar/egg-baz
```

Which transformed (as expected) to the following template:

```yaml
Resources:
  ResizerStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionS3Location:
        Bucket: foo-bar
        Key: egg-baz
      RoleArn: !GetAtt 'ResizerStateMachineRole.Arn'
      Tags:
        - Key: stateMachine:createdBy
          Value: SAM
  ResizerStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - states.amazonaws.com
      ManagedPolicyArns: []
      Tags:
        - Key: stateMachine:createdBy
          Value: SAM
```
