### ISSUE TITLE
Support Step Function Actions in Api Gateway

### ISSUE THREAD

**Issue by drewsb** [awslabs/serverless-application-model#1664]
### Feature Proposal

**Description:**

Similar to this post https://github.com/serverless-operations/serverless-step-functions/issues/72 for serverless-framework, I was wondering if there is an easy way to create Api Gateway endpoints that directly invoke Step Functions API actions (e.g. DescribeExecution, ListExecutions, etc.) without creating an entire Api Gateway resource that calls the URL. If not, is this a reasonable feature request? As mentioned in the post I linked, an "Action:" parameter could added to the _Events_ to distinguish the different actions (StartExecution, DescribeExecution, etc.):

```
Events:
      StateMachineApi:
          Type: Api
          Properties:
            Method: get
            Path: /describe
            Action:DescribeExecution
```
