### ISSUE TITLE
processed template in change set adds extra "Stage" stage

### ISSUE THREAD

**Issue by homingli** [awslabs/serverless-application-model#176]
original template:
```
Resources:
  myApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: swagger.yml
      StageName: Prod
      Variables:
        LambdaFunctionName: !Ref myFunction
```
processed template:
```
"Resources": {
    "myApiDeploymentxxxxxxxxxx": {
      "Type": "AWS::ApiGateway::Deployment",
      "Properties": {
        "RestApiId": {
          "Ref": "myApi"
        },
        "Description": "RestApi deployment id:  <hash> ",
        "StageName": "Stage"
      }
    },
    "myApiProdStage": {
      "Type": "AWS::ApiGateway::Stage",
      "Properties": {
        "Variables": {
          "LambdaFunctionName": {
            "Ref": "myFunction"
          }
        },
        "RestApiId": {
          "Ref": "myApi"
        },
        "DeploymentId": {
          "Ref": "myApiDeployment0bcc95243b"
        },
        "StageName": "Prod"
      }
    },
```

Note `"StageName": "Stage"` and `"StageName": "Prod"` in the processed template.
