### ISSUE TITLE
Cloudformation randomly fails to create stack

### ISSUE THREAD

**Issue by Pelto** [awslabs/serverless-application-model#184]
We have a cloudformation stack with the following resources:

```
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub '${AWS::Region}-${AWS::StackName}-bucket'

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs6.10
      Handler: index.handler
      CodeUri: .
      Timeout: 60
      MemorySize: 1536
      Policies:
        - Version: '2012-10-17' # Policy Document
          Statement:
            - Effect: Allow
              Action: s3:GetObject*
              Resource: !Sub 'arn:aws:s3:::${AWS::Region}-${AWS::StackName}-bucket/*'
      Events:
        UploadVisitorData:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
```

The creation of the Bucket fails sometimes with the error message: `Unable to validate the following destination configurations`.

After looking closer to it the best source of information that we have have found has been https://aws.amazon.com/premiumsupport/knowledge-center/unable-validate-destination-s3/.

This seems to be a race condition within the stack outside our control.
