### ISSUE TITLE
API backend template gives 502 Bad Gateway error

### ISSUE THREAD

**Issue by dwschulze** [awslabs/serverless-application-model#185]
I wrote lambda functions in Java following this example

  https://github.com/piomin/sample-serverless-aws-lambda

I did a manual deploy and configuration following this

  https://dzone.com/articles/building-serverless-on-aws-lambda

and they worked.
  
I deployed the same lambda functions using the serverless-application-model (SAM) code below.
The SAM deployment could not run the API gateway console tests against the lambdas.  I had to turn off lambda proxy integration in the Integration Request for POST and in the Method Response I had to add a Response for the 200 status code.  The console tests then worked for POST and GET.

When I try to run GET from Postman I get a 502 Bad Gateway error so something is not right with the API gateway configuration.  The Lambdas have an IAM Role that includes AWSLambdaBasicExecutionRole so SAM got that part right.  The SAM missed something that the manual deploy and configuration got right. 

The CloudWatch logs only show logs for aws/lambda and they don't have much in them.  They show

    Account: null
    Null key found for public java.lang.String aws.serverless.example.account.model.Account.getId()

Account is one of my Java objects.  For some reason an Account is being created with a null id, which
will be a problem reading or writing the object to DynamoDB.  That doesn't seem related to the 502 error though.

Here is my SAM code:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: account-customer-service account functions.
Resources:
  GetAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws.serverless.example.account.crud.GetAccount::handleRequest
      Runtime: java8
      #CodeUri: target/account-service-0.0.1-SNAPSHOT.jar
      CodeUri: s3://serverless-lambda-upload-bucket/account-service-0.0.1-SNAPSHOT.jar
      MemorySize: 512
      Policies: AmazonDynamoDBReadOnlyAccess
      #Policies: AWSLambdaBasicExecutionRole    # Is this granted by default?
      Timeout: 20
      Events:
        GetAccount:
          Type: Api
          Properties:
            Path: /account/{id}
            Method: get

  GetAccountForCustomerFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws.serverless.example.account.crud.GetAccountsByCustomerId::handleRequest
      Runtime: java8
#      CodeUri: target/account-service-0.0.1-SNAPSHOT.jar
      CodeUri: s3://serverless-lambda-upload-bucket/account-service-0.0.1-SNAPSHOT.jar
      MemorySize: 512
      Policies: AmazonDynamoDBReadOnlyAccess
      #Policies: AWSLambdaBasicExecutionRole    # Is this granted by default?
      Timeout: 20
      Events:
        GetAccountForCustomer:
          Type: Api
          Properties:
            Path: /account/customer/{customerId}
            Method: get

  PostAccountFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: aws.serverless.example.account.crud.PostAccount::handleRequest
      Runtime: java8
#      CodeUri: target/account-service-0.0.1-SNAPSHOT.jar
      CodeUri: s3://serverless-lambda-upload-bucket/account-service-0.0.1-SNAPSHOT.jar
      MemorySize: 512
      Policies: AmazonDynamoDBFullAccess
      #Policies: AWSLambdaBasicExecutionRole    # Is this granted by default?
      Timeout: 20
      Events:
        PostAccount:
          Type: Api
          Properties:
            Path: /account
            Method: post

  DynamoDBTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      TableName: account

```
