### ISSUE TITLE
FAILED: User is not authorized to perform cloudformation:CreateChangeSet

### ISSUE THREAD

**Issue by kashoory** [awslabs/serverless-application-model#186]
I have the following simple SAM CloudFormation template:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AW::Serverless-2016-10-31
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: main.handler
      Runtime: python3.6
```
I package and deploy it with the following commands:

`
aws cloudformation package --template-file .\template.yaml --s3-bucket xxxxxxx --output-template-file packaged-template.yaml`

`
aws cloudformation deploy --template-file .\packaged-template.yaml --stack-name my-sam-stack --capabilities CAPABILITY_IAM`

Package is successful, but after deploy, I receive the following error message:
`Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: User: arn:aws:iam::xxxxxxx:user/xxx is not authorized to perform: cloudformation:CreateChangeSet on resource: arn:aws:cloudformation:us-east-1:aw:transform/Serverless-2016-10-31`

I tried different combination of permissions for my user including giving AdministratorAccess, however, the error remained the same.
When I use the console to create stack for the same template (the packaged one), I receive the same error.
Am I missing something?
