### ISSUE TITLE
Q: How I can setup different number of variables for lambda based on env? 

### ISSUE THREAD

**Issue by IgorKuzmenko** [awslabs/serverless-application-model#187]
Hi. I would like to have opportunity setup different number of variables for my lambda: 
Example:
``` xml
EnvironmentMappings:
  dev:
    param1: value1
  test:
    param1: value1
    param2: value2
  prod:
    param1: value1
    param2: value2
    param3: value3
```
so, in dev env it will be only one parametr, and three in prod.

**Comment by mikecbrant** [comment]
I was able to achieve this by using a condition in my SAM template.  In my example I was trying to inject environmental variables based on whether a DynamoDb table in the template did or did not have.

Condition:
```
Conditions:
  DynamoHasRangeKey: !Not [!Equals [!Ref DynamoRangeKey, 'null']]
```
And Lambda definition:

```
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      ... other properties ...
      Environment:
        Variables:
          !If
            - DynamoHasRangeKey
            -
              DYNAMO_TABLE: !Ref DynamoDbTable
              DYNAMO_HASH_KEY: !Ref DynamoHashKey
              DYNAMO_HASH_KEY_TYPE: !Ref DynamoHashKeyType
              DYNAMO_RANGE_KEY: !Ref DynamoRangeKey
              DYNAMO_RANGE_KEY_TYPE: !Ref DynamoRangeKeyType
            -
              DYNAMO_TABLE: !Ref DynamoDbTable
              DYNAMO_HASH_KEY: !Ref DynamoHashKey
              DYNAMO_HASH_KEY_TYPE: !Ref DynamoHashKeyType
```
Caution: support for conditions in SAM templates doesn't really seem to be documented at this point, so  you may face some trial in error in trying to figure out how they can be used in your templates.
