### ISSUE TITLE
DeletionPolicy in SAM template is ignored in processed CF template.

### ISSUE THREAD

**Issue by kashoory** [awslabs/serverless-application-model#188]
I defined DeletionPolicy as Retain for a S3 bucket and realised that delete-stack behaves this bucket like a normal bucket without DeletionPolicy.
Then from aws console I found a discrepancy between the original template and processed template: DeletionPolicy was not there!
This is original template:
```
AWSTemplateFormatVersion: 2010-09-09
Description: Serverless backend for PM
Parameters:
  PMInboundBucketName:
    Default: com.v.test.inbound
    Description: Name of inbound bucket for PM objects
    Type: String
Resources:
  PMInboundBucket:
    DeletionPolicy: Retain
    Properties:
      BucketName:
        Ref: PMInboundBucketName
    Type: AWS::S3::Bucket
  PMProcessorFunction:
    Properties:
      CodeUri: s3://com.v.cloudformation.upload/98912aaadab31c003dfb1f6a70192945
      Description: PM processor
      Events:
        PMPublishEvent:
          Properties:
            Bucket:
              Ref: PMInboundBucket
            Events: s3:ObjectCreated:*
          Type: S3
      FunctionName: com-v-PM_PM-processor
      Handler: main.handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
```

And this one is the processed template:

```
{
	"AWSTemplateFormatVersion": "2010-09-09",
	"Parameters": {
		"PMInboundBucketName": {
			"Default": "com.v.test.inbound",
			"Type": "String",
			"Description": "Name of inbound bucket for PM objects"
		}
	},
	"Description": "Serverless backend for PM",
	"Resources": {
		"PMProcessorFunctionPMPublishEventPermission": {
			"Type": "AWS::Lambda::Permission",
			"Properties": {
				"Action": "lambda:invokeFunction",
				"SourceAccount": {
					"Ref": "AWS::AccountId"
				},
				"FunctionName": {
					"Ref": "PMProcessorFunction"
				},
				"Principal": "s3.amazonaws.com"
			}
		},
		"PMProcessorFunctionRole": {
			"Type": "AWS::IAM::Role",
			"Properties": {
				"ManagedPolicyArns": ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"],
				"AssumeRolePolicyDocument": {
					"Version": "2012-10-17",
					"Statement": [{
							"Action": ["sts:AssumeRole"],
							"Effect": "Allow",
							"Principal": {
								"Service": ["lambda.amazonaws.com"]
							}
						}
					]
				}
			}
		},
		"PMProcessorFunction": {
			"Type": "AWS::Lambda::Function",
			"Properties": {
				"Code": {
					"S3Bucket": "com.v.cloudformation.upload",
					"S3Key": "98912aaadab31c003dfb1f6a70192945"
				},
				"FunctionName": "com-v-PM_PM-processor",
				"Tags": [{
						"Value": "SAM",
						"Key": "lambda:createdBy"
					}
				],
				"Handler": "main.handler",
				"Role": {
					"Fn::GetAtt": ["PMProcessorFunctionRole", "Arn"]
				},
				"Runtime": "python3.6",
				"Description": "PM processor"
			}
		},
		"PMInboundBucket": {
			"Type": "AWS::S3::Bucket",
			"Properties": {
				"NotificationConfiguration": {
					"LambdaConfigurations": [{
							"Function": {
								"Fn::GetAtt": ["PMProcessorFunction", "Arn"]
							},
							"Event": "s3:ObjectCreated:*"
						}
					]
				},
				"BucketName": {
					"Ref": "PMInboundBucketName"
				}
			}
		}
	}
}
```

**Comment by kashoory** [comment]
It looks like it has something to do with lambda connection. Defined two s3 buckets not connected to lambda and DeletionPolicy was applied to both properly.

**Comment by jfuss** [comment]
@kashoory Sorry about the tardiness here. This is a super strange bug! Are you still seeing this happen? I am wondering if some strange things were going on before we added DeletionPolicy support. The reason I say that is because I took your template (you shared above) and transformed it. I see DeletionPolicy being retained in the output we produce. This shouldn't be an issue any more but please let us know if it is still occurring so we can properly track this down.

SAM Template I ran locally
```yaml
Resources:
  PMInboundBucket:
    DeletionPolicy: Retain
    Properties:
      BucketName:
        Ref: PMInboundBucketName
    Type: AWS::S3::Bucket
  PMProcessorFunction:
    Properties:
      CodeUri: s3://com.v.cloudformation.upload/98912aaadab31c003dfb1f6a70192945
      Description: PM processor
      Events:
        PMPublishEvent:
          Properties:
            Bucket:
              Ref: PMInboundBucket
            Events: s3:ObjectCreated:*
          Type: S3
      FunctionName: com-v-PM_PM-processor
      Handler: main.handler
      Runtime: python3.6
    Type: AWS::Serverless::Function
```  

Transformed template:
```json
{
  "Resources": {
    "PMProcessorFunctionRole": {
      "Type": "AWS::IAM::Role",
      "Properties": {
        "ManagedPolicyArns": [
          "arn:aws-us-gov:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        ],
        "AssumeRolePolicyDocument": {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Action": [
                "sts:AssumeRole"
              ],
              "Effect": "Allow",
              "Principal": {
                "Service": [
                  "lambda.amazonaws.com"
                ]
              }
            }
          ]
        }
      }
    },
    "PMInboundBucket": {
      "DeletionPolicy": "Retain",
      "Type": "AWS::S3::Bucket",
      "Properties": {
        "NotificationConfiguration": {
          "LambdaConfigurations": [
            {
              "Function": {
                "Fn::GetAtt": [
                  "PMProcessorFunction",
                  "Arn"
                ]
              },
              "Event": "s3:ObjectCreated:*"
            }
          ]
        },
        "BucketName": {
          "Ref": "PMInboundBucketName"
        }
      },
      "DependsOn": [
        "PMProcessorFunctionPMPublishEventPermission"
      ]
    },
    "PMProcessorFunctionPMPublishEventPermission": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "Action": "lambda:invokeFunction",
        "SourceAccount": {
          "Ref": "AWS::AccountId"
        },
        "FunctionName": {
          "Ref": "PMProcessorFunction"
        },
        "Principal": "s3.amazonaws.com"
      }
    },
    "PMProcessorFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": "com.v.cloudformation.upload",
          "S3Key": "98912aaadab31c003dfb1f6a70192945"
        },
        "FunctionName": "com-v-PM_PM-processor",
        "Tags": [
          {
            "Value": "SAM",
            "Key": "lambda:createdBy"
          }
        ],
        "Handler": "main.handler",
        "Role": {
          "Fn::GetAtt": [
            "PMProcessorFunctionRole",
            "Arn"
          ]
        },
        "Runtime": "python3.6",
        "Description": "PM processor"
      }
    }
  }
}
```
