### ISSUE TITLE
Tag the CF Stack with SAM

### ISSUE THREAD

**Issue by c2xbrhdj6u4qs15** [awslabs/serverless-application-model#189]
Hi,

How to Tag the CF Stack which gets created by SAM? I can Tag the resources specified in the SAM CF Template, but I am unable to Tag the Cloudformation Stack. I used a work around by using awscli cloud formation update-stack, but that would fail if there are no changes.

Thanks in advance

**Comment by cluggas** [comment]
I had the same problem, and also wanted to set the `IAM Role` property for the stack. The `cloudformation deploy` command doesn't offer either of these as options.

We worked around it by creating our stacks as a pre-requisite steps using a non-SAM cloud formation template. It just contains a very basic template with a temporary lambda function and role.

```
AWSTemplateFormatVersion: 2010-09-09
Description: Dummy template for new stacks
Resources:
  role: 
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub "${AWS::StackName}-temporary-role"
      AssumeRolePolicyDocument:
        Version : 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole
  lambda:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        ZipFile: "Dummy code"
      Handler: dummy
      Role: !GetAtt role.Arn
      Runtime: nodejs6.10
```

Then creating the stack using the following command:

`cloudformation create-stack --stack-name my-stack --template-url dummy-template.yaml --role-arn ... --tags ... --capabilities CAPABILITY_NAMED_IAM`

This allows you to supply role-arn and tags arguments. Then once created, you can then run your SAM deployment over the top.
