### ISSUE TITLE
Internal transform failure for StageName defined by reference in a SAM template

### ISSUE THREAD

**Issue by dinvlad** [awslabs/serverless-application-model#19]
Hi, I'm trying to create a simple stack for SAM that references a Swagger file using this configuration:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  APIStage:
    Default: dev
    Description: Name of the API stage to use for deployment
    Type: String
    AllowedPattern: '[A-Za-z0-9-]*'

Resources:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref APIStage
      DefinitionUri: models.yaml
```
However,
```
aws cloudformation package --template-file sam.yaml --output-template-file deploy.yaml --s3-bucket backend-dev-xxxx
aws cloudformation deploy --template-file deploy.yaml --stack-name backend-dev --capabilities CAPABILITY_IAM --parameter-overrides APIStage=dev
```
leads to
```
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.
```
When I remove the `Parameters` section and set `StageName: dev` explicitly, the stack is created successfully. So it seems like Transform fails because of the `APIStage` reference, even though the template is validated successfully before CloudFormation calls Transform.

**Comment by dinvlad** [comment]
Update: I got a bit confused but now it seems clear that this issue is specific to how Transform processes referenced `StageName` for `AWS::Serverless::Api` rather than being a generic issue with processing referenced variables. For example, the following template was adopted from the HelloWorld example and appears to work correctly:
```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  APIStage:
    Default: dev
    Description: Name of the API stage to use for deployment
    Type: String
    AllowedPattern: '[A-Za-z0-9-]*'

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      Environment:
        Variables:
          APIStage: !Ref APIStage
```
