### ISSUE TITLE
Why can't I attach a managed policy to the default service-wide role?

### ISSUE THREAD

**Issue by bringingkatigbak** [awslabs/serverless-application-model#193]
I have deployed the following however when I check in the AWS console the managed policy AmazonSESFullAccess is not attached. I have found examples that can do this on the function level but I am interested in doing it at the service level. Is this possible? Is this a bad idea?
```
provider:
  name: aws
  runtime: nodejs6.10
  stage: staging
  region: us-east-1
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "ec2:CreateNetworkInterface"
        - "ec2:DescribeNetworkInterfaces"
        - "ec2:DetachNetworkInterface"
        - "ec2:DeleteNetworkInterface"
      Resource: "*"
  
  managedPolicyArns:
    - arn:aws:iam::aws:policy/AmazonSESFullAccess
```
