### ISSUE TITLE
Cannot add multiple reference variables to AWS::Serverless::Api

### ISSUE THREAD

**Issue by JasonQuinn** [awslabs/serverless-application-model#20]
When adding a AWS::Serverless::Api specifying multiple reference variables causes the message "Number of errors found: 1. Resource with id [TestUploadtestStage] is invalid. Type of property 'Variables' is invalid." when deploying with "aws cloudformation deploy".
I can add either of the variables but cannot add both

```
  TestUpload:
     Type: AWS::Serverless::Api
     Properties:
        StageName: test
        DefinitionUri: swagger.json
        Variables:
          DeleteFunctionArn: !Ref DeleteFunction
          PutFunctionArn: !Ref PutFunction

```

Have I just got the syntax incorrect?
