### ISSUE TITLE
Support multiple events of the same type for functions

### ISSUE THREAD

**Issue by patrickli** [awslabs/serverless-application-model#209]
`AWS::Serverless::Function` type supports multiple event sources however it is limited to one event per type. I have the need to trigger multiple scheduled events for the same function with different inputs.

The only way I can make this work is to manually create multiple `AWS::Events::Rule` and point the target to the function.

The `serverless` framework supports this use case.

**Comment by patrickli** [comment]
I think I figured out how to do that. Closing.

**Comment by tskinn** [comment]
@patrickli how did you do it? I'm facing the same problem.

**Comment by jfuss** [comment]
@tskinn The Events takes a dictionary, so you can give each Event a different name. This is easier to explain in an example (below). You can intermix different 'Types', just as long as you have different 'Keys' in the Events Dictionary. Does that help?

```
Events:
        Timer1:
          Type: Schedule
          Properties:
            Schedule: rate(5 minutes)
        Timer2:
          Type: Schedule
          Properties:
            Schedule: rate(1 hour)
```
