### ISSUE TITLE
"Type of property 'Tags' is invalid" when the tag value is pure numeric

### ISSUE THREAD

**Issue by linusguan** [awslabs/serverless-application-model#210]
When I try to tag my lambda function with a numeric tag, it complains about `Type of property 'Tags' is invalid`
```
Resources:
  MyFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: <FunctionName>
      Description: <Description>
      Handler: <Handler>
      Runtime: python3.6
      CodeUri: ./deployment.zip
      Role: <Role>
      MemorySize: 128
      Timeout: 120
      Tags:
        Project: 'myproject'
        CostCentre: '0090008300'
```
If I add a alphabet as a prefix then it works
