### ISSUE TITLE
Reference external resources

### ISSUE THREAD

**Issue by sonytricoire** [awslabs/serverless-application-model#213]
Hi !

I would my SAM template to references resources (actually lambda functions) that are not managed in my SAM template.

I saw that the Intrisic function ImportValue could do the job but what if the external resources are not managed through a cloudformation stack ?

An approach could be to define kind of RefArn attribute to be able to reference existing (static) ARN's of resources.
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Simple CRUD webservice.
Resources:
  GetFunction:
    Type: AWS::Serverless::Function
    RefArn: arn:aws:lambda:eu-west-1:xxxxxxxx:function:testLambda:current # this function already exists in AWS and I do not expect SAM to manage it
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /resource/{resourceId}
            Method: get
```

Of course it has blocking drawbacks (SAM Local for instance), but is it a relevant feature regarding SAM objectives ?
Is their any workaround to have this working right now with SAM ?

Thanks for your feedback
