### ISSUE TITLE
Policy create issues with Dead Letter Queue and XRay Tracing

### ISSUE THREAD

**Issue by riston** [awslabs/serverless-application-model#217]
I tried adding my function Dead Letter Queue(DLQ) SQS queue and enabling XRay tracing. The stack executer role also had the permissions enabled for the following resources `sqs:*` and `xray:*`.

The function has following inline policies for XRay:
```
- Effect: "Allow" # xray permissions (required)
  Action:
    - "xray:PutTraceSegments"
    - "xray:PutTelemetryRecords"
  Resource:
    - "*"
```

For SQS:
```
- Effect: Allow
  Action:
    - sqs:SendMessage
  Resource: "*"
```

When the stack's changeset is applied it would fail because:
```

12:47:11 UTC+0200 | UPDATE_ROLLBACK_IN_PROGRESS | AWS::CloudFormation::Stack | notifications-lambda | The following resource(s) failed to update: [GeneratorFunction].
-- | -- | -- | -- | --
  | 12:47:08 UTC+0200 | UPDATE_FAILED | AWS::Lambda::Function | GeneratorFunction | The provided execution role does not have permissions to call PutTraceSegments on XRAY
```

The current workaround is to deploy the function first time without the following options:
```
      DeadLetterQueue:
        Type: SQS
        TargetArn: !GetAtt NotificationDeadLetterQueue.Arn
      Tracing: Active
```
After that you can enable the options again, deploy and the stack apply would succeed. Seems like the serverless guys have same issue https://github.com/serverless/serverless/pull/3742.
