### ISSUE TITLE
Codedeploy Service Role Insufficent to invoke hooks

### ISSUE THREAD

**Issue by steveparker-kcom** [awslabs/serverless-application-model#219]
When using deployment preference settings, a service role for codedeploy is created with the following managed policy: arn:aws:iam::aws:policy/service-role/AWSCodeDeployRoleForLambda

Whatever is needed by codedeploy to work, something is missing. All of my deployments are failing. Reading the policy attached to the generated role I set the function name to begin with CodeDeploy_ - but it still fails.

If an org has naming standards, it is not desirable to hardcode function names. It would be better if you could pass in a pre-existing codedeploy role within the deployment preferences.

The error on the CodeDeploy deployment is like so:

`The IAM role <role_arn> does not give you permission to perform operations in the following AWS service: AWSLambda. Contact your AWS administrator if you need help. If you are an AWS administrator, you can grant permissions to your users or groups by creating IAM policies. (Error code: IAM_ROLE_PERMISSIONS)`

Any clue on how to get deployments to go through?

**Comment by jfuss** [comment]
Can you please rephrase the title into some form of a Feature Request ask? Something like [Feature Request] Ability to add existing role for DeploymentPreferences. It is hard to gather what you are asking from the current title.

It sounds like you are asking for either:
1. A way to give an existing role for deployment preferences
2. A way to define the resource name(s) within the generated policy (through a new policy template maybe?)
3. Maybe something similar to what we do for LambdaFunction and have a Policy section. This would allow you do add custom Policies to attach to the role but still allow SAM to generate the Role for you. 

How much control do you really want? Personally, I like the idea of the second way. This keeps the hand managing of resources down for customers. If we look at the AWS::Serverless::Function as an example, if you give a Role we do not append policies to that Role. This requires customers to now manage this Role and when they want to add DLQ support to their function, they need to remember to add this to the Role as well. Allowing SAM to generate these Roles for you as much as we can, will reduce this hand managing for customers. I think this makes for a better customer experience. I realize this limits customers in ways but I would like to not just add a Role everywhere (if we have simpler options).

What are your thoughts?

**Comment by steveparker-kcom** [comment]
More than anything, I want to understand why my implementation doesn't work at present. The following 2 functions in SAM will not deploy:

```
  RetrievePreTrafficHook:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: CodeDeployHook_PreRetrieve
      Description: Retrieve pre-traffic hook.
      Runtime: python3.6
      Handler: pre_traffic_hook.lambda_handler
      CodeUri: ./src/retrieve
      Role: !GetAtt HookLambdaRole.Arn
      MemorySize: 128
      Timeout: 60
      DeploymentPreference:
        Enabled: false
  Retrieve:
    Type: 'AWS::Serverless::Function'
    Properties:
      Description: Retrieve function.
      Runtime: python3.6
      Handler: retrieve.lambda_handler
      CodeUri: ./src/retrieve
      Role: !GetAtt RetrieveLambdaRole.Arn
      MemorySize: 128
      Timeout: 60
      AutoPublishAlias: ACTIVE
      DeploymentPreference:
        Type: AllAtOnce
        Hooks:
          PreTraffic: !Ref RetrievePreTrafficHook
```

On the back of these, SAM will create the codedeploy role and then fail to deploy claiming the IAM role isn't sufficient.

**Comment by jfuss** [comment]
@steveparker-kcom I have been trying to reproduce what you are seeing but no luck yet. What update are you trying to make to your function that causes this?

**Comment by jfuss** [comment]
@steveparker-kcom I noticed you are pointing both functions at the same code (./scr/retrieve). What is the reason behind this? In your ```RetrievePreTrafficHook``` Lambda, are you making the call back to Code Deploy through [this api](http://boto3.readthedocs.io/en/latest/reference/services/codedeploy.html#CodeDeploy.Client.put_lifecycle_event_hook_execution_status)? It is outlined in [here](https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst#traffic-shifting-using-codedeploy), "This Lambda function must call back to CodeDeploy with explicit Success or Failure. On Failure, it will abort and report a failure back to CloudFormation. On Success, CodeDeploy will proceed to traffic shifting."

I think we can make this more obvious in some fashion and an example will defiantly aid in that. I will try and get that updated some time soon.

I can't seem to reproduce the error you are seeing though. Could you explain what update you are doing that causes this error to surface? This will help me in reproducing the issue so we can debug further. I apologize for the issue this is causing you.

**Comment by jfuss** [comment]
Could you also share the Roles to the functions, specifically the ```HookLambdaRole```

**Comment by steveparker-kcom** [comment]
Thanks @jfuss for assisting

The update is using the SAM cli tools via codebuild, so it'll be updating the code package.

```
- aws cloudformation package --template-file sam.yml --output-template-file sam-packaged.yml --s3-bucket $sam_bucket
      - aws cloudformation deploy --template-file sam-packaged.yml --stack-name stMyStack --capabilities CAPABILITY_IAM
```

Both functions were in the same folder for organisation really. The whole application has a number of functions with their own folder and ideally keeping the hooks with the functions makes some sense. Note that in the failures however, the hook functions were never being called.

In light of your query though I moved the hook to a separate folder and the function was executed as expected. I guess this is due to some ordering with cloudformation or something? Probably worth documenting these quirks I guess.

For reference my hook function is here: https://gist.github.com/steveparker-kcom/29f9ba67f5c43734f816605c8dc58bc0

The hook function doesn't return though, it looks like lambdas version of boto3 is outdated:

`'CodeDeploy' object has no attribute 'put_lifecycle_event_hook_execution_status': AttributeError`

**Comment by jfuss** [comment]
@steveparker-kcom, I have an update on the AWS SDK part. We have a cadence of releasing the new versions of the AWS SDK, which hasn't happened yet for the newer version. To avoid this issue and make sure your service/application is future proof, we recommend you to bundle the relevant AWS SDK into your deployment package.

**Comment by jfuss** [comment]
Should have realized this earlier but if you are already packaging the AWS SDK into your deployment package, make sure it has the ```put_lifecycle_event_hook_execution_status``` method on CodeDeploy. I know [version 1.4.8](http://boto3.readthedocs.io/en/latest/reference/services/codedeploy.html#CodeDeploy.Client.put_lifecycle_event_hook_execution_status) has the method. I do not know when it was introduced though.

Hopefully this gets you over all of the issues.

**Comment by steveparker-kcom** [comment]
Thanks for working through this with me @jfuss, I've got it working with the combination of separating the hook folder and packaging the latest sdk with it.

Can't really understand the issue, the IAM role is created in the first run of the project and it's only on the second run that hooks execute, so there's already a good 1-2 minutes gap between the service role creation and when it gets used. Either way I'm happy to have it working now!

**Comment by jfuss** [comment]
@steveparker-kcom You are right, that doesn't make sense. I forgot that the first deployment goes through fine and that it is the second one that caused the issue for you. What I thought only makes sense if it was caused when the Roles were first created. I am at a loss to what caused this. I still think it is something within IAM but can't find data to back that claim up. 

There are a couple things that did come out of this.
- You initially asked for a way to define what Lambda Functions would be called by CodeDeploy. I would like to open a feature request for this to make sure the solution we come up with supports everyone. 
- Until the first one is addressed, we need to update the Documentation to call out the naming convention you will need to use hooks (pre and post). Namely, Pre or Post hook functions need a name as follows: CodeDeployHook_*
- We should call out what min version of the AWS SDK you need to use pre and post hooks.

Is there anything I am missing, related to pre (or post) hooks?

**Comment by jfuss** [comment]
@steveparker-kcom I found the root cause of your permission issue. CodeDeploy became aware of an issue in their managed policy on Friday Dec 1. They have since fixed this issue, which is why you 'magically' saw everything work once got past the naming of the function and sdk version issues.

Please let me know if there are any other action items that can be addressed, in addition to the ones above, or if you are still having trouble in some area.

**Comment by steveparker-kcom** [comment]
Haha fair enough, good to know. Thanks @jfuss - I think the points you highlighted have it covered.

**Comment by bluepeter** [comment]
@jfuss I believe I am experiencing a similar issue in us-west-2. Namely, the policy that is automatically created for CodeDeploy is seemingly insufficient to deploy Lambda functions.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  DummyFunction:
    Type: AWS::Serverless::Function
    Properties:
    ¦ FunctionName: BigOnion_dummyFunction                                                  
    ¦ Role: arn:aws:iam::XXX:role/BigOnion_Lambda_Logs_S3_Dynamo_SNS               
  
    ¦ AutoPublishAlias: live
    ¦ DeploymentPreference:
    ¦   Type: AllAtOnce
  
    ¦ Handler: index.handler
    ¦ Runtime: nodejs6.10
    ¦ CodeUri:
    ¦   Bucket: !ImportValue s3BigOnionFunctionsHolder                                      
    ¦   Key: 'BigOnion_dummyFunction.zip'                     
```

In the CloudFormation log, I see it has created this role:

![screenshot-us-west-2 console aws amazon com-2017-12-06-04-18-34-672](https://user-images.githubusercontent.com/2158187/33644441-a5e10a80-da7f-11e7-97f4-9f6743073dd9.png)

However, looking at that role, it appears to have insufficient Lambda permissions to create a new function version:

![screenshot-console aws amazon com-2017-12-06-04-16-48-198](https://user-images.githubusercontent.com/2158187/33644408-7242d7e4-da7f-11e7-91f7-d7b37f86e4da.png)

**Comment by jfuss** [comment]
CodeDeploy does not deploy your Lambda Function, it routes the traffic between two versions. More info on Traffic Shifting here: http://docs.aws.amazon.com/lambda/latest/dg/lambda-traffic-shifting-using-aliases.html

Will move the conversation over to #223

**Comment by sarojgharat** [comment]
Facing the same issue. The IAM role arn:aws:iam::853493370704:role/Lambda-SAM-CodeDeployServiceRole-1ODWSWYEHLZ4O does not give you permission to perform operations in the following AWS service: AWSLambda. Contact your AWS administrator if you need help. If you are an AWS administrator, you can grant permissions to your users or groups by creating IAM policies. (Error code: IAM_ROLE_PERMISSIONS) 

Why was this feature introduced when it did not work in the first place ?

**Comment by jfuss** [comment]
@sarojgharat It does work, we are missing some key documentation that is handled in #246

As I called out above: "Until the first one is addressed, we need to update the Documentation to call out the naming convention you will need to use hooks (pre and post). Namely, Pre or Post hook functions need a name as follows: CodeDeployHook_*"

Please updated you hook function to follow the naming schema described.

**Comment by jfuss** [comment]
From the callouts/actions items above:

1. You initially asked for a way to define what Lambda Functions would be called by CodeDeploy. I would like to open a feature request for this to make sure the solution we come up with supports everyone.
2. We should call out what min version of the AWS SDK you need to use pre and post hooks.

1. Created issue #250
2. Will make sure is addressed in #246

**Comment by kesiena115** [comment]
I'm having this problem in us-west-2 i.e.,

`The IAM role <IAM_ROLE> does not give you permission to perform operations in the following AWS service: AWSLambda. Contact your AWS administrator if you need help. If you are an AWS administrator, you can grant permissions to your users or groups by creating IAM policies. (Error code: IAM_ROLE_PERMISSIONS)`



```
CodeDeployHook_PreTrafficLambda:
    Type: AWS::Serverless::Function
    FunctionName: CodeDeployHook_PreTrafficLambda
    Properties: ...
      Role:
        Fn::GetAtt: [LambdaRole, Arn]

LambdaRole:
   Type: AWS::IAM::Role
   Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [lambda.amazonaws.com]
        Version: '2012-10-17'
      Policies:
      - PolicyDocument:
          Statement:
          - Action: ['lambda:InvokeFunction', 'lambda:GetFunction', 'codedeploy:PutLifecycleEventHookExecutionStatus']
            Effect: Allow
            Resource: '*'
...
```
Any ideas on how I can resolve this or is this still a pending issue?

**Comment by kesiena115** [comment]
I've realized my mistake. The `FunctionName` of the `PreTrafficLambda` should be part of the properties. Everything worked once I made this change i.e.:

```
PreTrafficLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: CodeDeployHook_PreTrafficLambda
      Role:
        Fn::GetAtt: [LambdaRole, Arn]
```
