### ISSUE TITLE
Support CloudFormation intrinsic functions in SAM resources

### ISSUE THREAD

**Issue by sanathkr** [awslabs/serverless-application-model#22]
We quite often use !Ref, !Sub, !Join in properties that are supposed to hold strings such as CodeUri, DefinitionUri, StageName (#19) etc. This is a perfectly valid CloudFormation, but the transformation logic that parses SAM does not resolve intrinsic functions before parsing the property as a string. So the transformation logic would fail and depending on the property it could either return a `validation error` or `internal failure`. Properties that are directly passed down to CloudFormation are unaffected by this problem.

This is a feature request to add support for resolving a subset of [CloudFormation intrinsics](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html) in the transformation logic. We care about only the subset of properties that the transform manipulates, like CodeUri. 

Following intrinsics will be supported:
- !Sub
- !Join

on following properties:

- CodeUri on AWS::Serverless::Function
- Role on AWS::Serverless::Function
- DefinitionUri on AWS::Serverless::Api
- StageName on  AWS::Serverless::Api

**Comment by dinvlad** [comment]
Does that imply we would be able to use Ref through a !Sub function, e.g. as described in
http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html?:
```
{ "Fn::Sub": [ "www.${Domain}", { "Domain": {"Ref" : "RootDomainName" }} ]}
```

**Comment by dinvlad** [comment]
Does that mean we would be able to reference template parameters through the `${TemplateParameter}` syntax, as described in http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html? Or even use !Ref through !Sub for that matter? Thanks

**Comment by deathbob** [comment]
Trying to use `!GetAtt` for SecurityGroupIds in a VpcConfig section of a Lambda, get ` Type of property 'VpcConfig' is invalid`.

Works fine when I manually look up the values and plug in the strings, so figure it must be this same issue.  

Timeframe on a fix?  Any workarounds possible?

Loving the new SAM stuff but this is a deal-breaker.

**Comment by sanathkr** [comment]
I am sorry you are running into the bug. Unfortunately there are no workarounds besides switching to regular AWS::Lambda::Function resource. 

We are actively working on fixing it. Will let you know once its done

**Comment by stuartstevenson** [comment]
I've been having this issue with `Fn::ImportValue` for the ::Api Variables property to be able to pass in the function arn.

Is this bug fix to support all of the intrinsic functions?

**Comment by sanathkr** [comment]
@stuartstevenson #20 was a bug that was fixed. You should be able to use any Fn:: function with Variables property. However you cannot pass the ARN directly to your Swagger. It doesn't work. You should pass function name and construct the ARN there. See this example: https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/swagger.yaml#L23

**Comment by joekiller** [comment]
`Fn::Import` wasn't  working for.me earlier today. Can you all confirm that it is fixed? I can create an example if necessary.

**Comment by sanathkr** [comment]
Can you give me an example with the error you received?

**Comment by joekiller** [comment]
I'll create one tomorrow and post here.

**Comment by stuartstevenson** [comment]
@sanathkr Thank you for your response. Is there a reason why ARNs in particular cannot be passed as I had made the assumption that the stage variable was just a string i was setting? I would not have assumed that the contents of the string would be validated.

Also I can only use Fn::GetAtt to retrieve the function ARN, not the generated name. Is there a way I can programatically get the function name to be able to pass it into the swagger doc?

**Comment by joekiller** [comment]
I was using multiple short form functions in a row which is not supported. So trying

    Resource: !ImportValue !Sub '${KMSKey}-blah'

Is improper while
```
Resource: !ImportValue 
                      'Fn::Sub': '${KMSKey}-blah'
```
Works. http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-base64.html Notes the problem I had.

**Comment by brettstack** [comment]
I'm still getting this error when trying to use `!ImportValue` for `AWS::Serverless::Function`

```yaml

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: bundle.handler
      MemorySize: 128
      Runtime: nodejs4.3
      Timeout: 3
      Events:
        List:
          Type: Api
          Properties:
            RestApiId: !ImportValue API-ApiId
            Path: /users
            Method: GET
```

**Comment by weargoggles** [comment]
I'm experiencing a variation of this trying to use !Ref as a value in a Function's Environment. Is my only option to switch to AWS::Lambda::Function for now?

**Comment by sanathkr** [comment]
!Ref in environment variables is supposed to work out-of-box. Can you post an example?

**Comment by weargoggles** [comment]
It did work. I was mistaken.

**Comment by jolexa** [comment]
Our org would also like to see `!Ref` supported in a the `CodeUri` field of a `AWS::Serverless::Function` in addition to the proposed items in the original comment.

Something like this, is what we are thinking (idolized design):
```
      CodeUri:
        Fn::Join:
          - '-'
          - - s3://some-known-convention
            - Ref: AWS::AccountId
            - '/github-sha/deployment.zip'
```

**Comment by sanathkr** [comment]
Thanks for the comment. Yes, we will support this usecase as well...

**Comment by dinvlad** [comment]
Interestingly, many of the intrinsics work through CodePipeline action for CloudFormation. Is that case handled differently?

**Comment by sanathkr** [comment]
We have just pushed support for Intrinsic functions - https://github.com/awslabs/serverless-application-model/blob/master/HOWTO.md#using-intrinsic-functions

It should work everywhere except for the caveats mentioned in the above doc. If you find any scenario where it doesn't work, please create a new bug.

`!Sub "Thanks everyone for the awesome feedback. ${your_username} are awesome!" `

**Comment by judahb** [comment]
Just curious, when is this available? Is it currently available in AWS::Serverless-2016-10-31?

**Comment by joekiller** [comment]
Should all be available.

-Joe
Sent via mobile.

**Comment by bluepeter** [comment]
```
  ¦ ¦ CodeUri: Fn::Join                                                                     
  ¦ ¦ ¦ - ''                                                                                
  ¦ ¦ ¦ - - 's3://whatever-function-holder-'                                                
  ¦ ¦ ¦ ¦ - !Ref 'AWS::AccountId'                                                           
  ¦ ¦ ¦ ¦ - '-'                                                                             
  ¦ ¦ ¦ ¦ - !Ref 'AWS::Region'                                                              
  ¦ ¦ ¦ ¦ - '/out.zip'           
```

... is not working

**Comment by baechul** [comment]
I am trying to do something like this to enable both local and CI run but doesn't work:
CodeUri:
        !If
          - CreateDevEnvironment
          - ../../../target/helloworld-1.0-SNAPSHOT.jar
          -
            Bucket: !Ref BucketName
            Key: !Ref CodeKey
Is If intrinsic function supported? Or how I can switch between 2 different objects (string and S3 location object) for CodeUrl in the same template?

**Comment by MaiKaY** [comment]
Dont know if `If` intrinsic functions are supported but an alternative would be to pass `BucketName` and `Key` as a parameter into your CF template.

**Comment by baechul** [comment]
@MaiKaY  Thanks. But in may case, I use a S3 location with BucketName and Key for CI and for local   with "sam local", my CodeUri value should be "./../../target/helloworld-1.0-SNAPSHOT.jar", which is string type.

**Comment by eelixa** [comment]
This is exactly what I'm trying to do as well but I haven't yet been able to find a way around this -- surely this must be a reasonably common use case? I too would like to switch `CodeUri` conditionally depending on if I'm running locally or not. If running locally `CodeUri` should be a String, but if not I need a S3 location with bucket name and key.

Are there any plans to support the `If` intrinsic function, or are there any other ways to achieve this?

**Comment by bluepeter** [comment]
@eelixa did you try using the full name for the intrinsic function, versus the shorthand notation? For SAM my understanding is you must use the former.

**Comment by eelixa** [comment]
@bluepeter Ah right, I didn't realise that was the case. I have the If part working now. Thanks a lot for your help!

**Comment by eelixa** [comment]
I ended up with something like this:

````
Conditions:
  RunLocally:
    Fn::Equals:
      - Ref: pEnvironment
      - "local"
````
And then:
````
  MyFunction:
    Type: "AWS::Serverless::Function"
    Properties:
      CodeUri:
        Fn::If:
          - RunLocally
          - "../../../build/distributions/myfunction.zip"
          -
            Bucket: pMyFunctionS3BucketName
            Key: pMyFunctionS3BucketKey
````

**Comment by joshuahiggins** [comment]
I'm running into an issue using `!Join` and/or `!Ref` on a simple API path:

```
Parameters:
  ApiBasePath:
    Type: String
    Default: /base-path
Resources:
  SomeApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: some.handler
      Runtime: nodejs6.10
      [removed other properties for brevity]
      Events:
        GetSomething:
          Type: Api
          Properties:
            Path: !Join [ !Ref ApiBasePath, /something ]
            Method: get
```

I know this can be defined via Swagger and the `AWS::Serverless::API` definitions, but I am hoping to keep it simple here. This works fine in `aws-sam-local` and I can validate and build the template locally, but when it hits CloudFormation I'm getting `FAILED - Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.`
