### ISSUE TITLE
Document usage of ${ServerlessRestApi}

### ISSUE THREAD

**Issue by matsev** [awslabs/serverless-application-model#222]
Please document the the `${ServerlessRestApi}` CloudFormation pseudo parameter used in the [example project](https://github.com/awslabs/serverless-application-model/blob/3cda50ddf3d2823162438cc3c72277828a20125f/examples/2016-10-31/encryption_proxy/template.yaml#L17). 

A similar example:

```
Outputs:
  ServerUrl:
    Value: !Sub https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod
    Description: The url of the API Gateway
```
