### ISSUE TITLE
AWS::Serverless::Function policies are ignored

### ISSUE THREAD

**Issue by cjohansen** [awslabs/serverless-application-model#224]
```yml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/cfs-termination
      RetentionInDays: 7
  StackTermination:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: TerminateOverdueStacks
      MemorySize: 128
      Description: Terminate CloudFormation Stacks that have the DeleteAfter tag
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 10
      Policies:
        - PolicyName: LambdaListAndTerminateStacks
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:ListExports'
                  - 'iam:PassRole'
                Resource:
                  - '*'
      Events:
        CfsTermination:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)
```

This template applies without issue. However, the resulting role only has the AWSBasicLambdaExection managed policy. My inline policy does not trigger an error, yet is still seemingly ignored. Am I doing something wrong?

**Comment by sanathkr** [comment]
You should only include the Policy Statement ({Statement: {...}}). For inline policies SAM looks for an object with Statement key in it. If it isn't found it ignores the object.

I don't like this experience where some policies are ignored. We should change this to fail fast so you know what's wrong.

Sent from my iPhone

On Dec 7, 2017, at 12:36 AM, Christian Johansen <notifications@github.com<mailto:notifications@github.com>> wrote:


AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  LogGroup:
    Type: 'AWS::Logs::LogGroup'
    Properties:
      LogGroupName: /aws/lambda/cfs-termination
      RetentionInDays: 7
  StackTermination:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: TerminateOverdueStacks
      MemorySize: 128
      Description: Terminate CloudFormation Stacks that have the DeleteAfter tag
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 10
      Policies:
        - PolicyName: LambdaListAndTerminateStacks
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'cloudformation:DescribeStacks'
                  - 'cloudformation:DeleteStack'
                  - 'cloudformation:ListExports'
                  - 'iam:PassRole'
                Resource:
                  - '*'
      Events:
        CfsTermination:
          Type: Schedule
          Properties:
            Schedule: rate(30 minutes)

This template applies without issue. However, the resulting role only has the AWSBasicLambdaExection managed policy. My inline policy does not trigger an error, yet is still seemingly ignored. Am I doing something wrong?

-

**Comment by cjohansen** [comment]
Yes, that solved it. Thanks!

There are a few things here that caught me by surprise:

1. Cloudformation accepting a template that produces no result. It really should fail like you said.
2. The documentation uses the term "IAM policy documents" multiple times. Also, it links vaguely to the IAM policy docs, not sure how I should've known it only expected statements.
3. Using `Policies` for something different than what that means under other resources.

So, my $0.05: If you only want the policy statements, the property should be named differently - `PolicyStatements` or similar, and the documentation should be very clear on this point, as it differs notably from other uses of `Policies`.

**Comment by Palisand** [comment]
Would the following policy be ignored?
``` yaml
Policies:
        Statment:
        - Action:
          - s3:GetObject
          - s3:PutObject
          - s3:PutObjectACL
          Effect: Allow
          Resource: arn:aws:s3:::bucket-name/*
```
I've hardcoded the `bucket-name` since the bucket existing pre-deploy, but this policy was ignored.

**Comment by sanathkr** [comment]
Dupe of #172

**Comment by Jun711** [comment]
@cjohansen 
I wonder what is the working version of your policy statement if you could provide an example. Thanks

**Comment by cjohansen** [comment]
@Jun711 

```yaml
Resources:
  SomeFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: SomeFunction
      MemorySize: 128
      Handler: index.handler
      Runtime: nodejs6.10
      Timeout: 20
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - 'cloudformation:DescribeStacks'
                - 'cloudformation:DescribeStackResources'
                - 'cloudformation:CancelUpdateStack'
                - 'iam:PassRole'
              Resource:
                - '*'
```
