### ISSUE TITLE
[Feature request] Support Cognito event sources

### ISSUE THREAD

**Issue by bluepeter** [awslabs/serverless-application-model#229]
The [documented event sources](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#event-source-types) do not appear to support [Cognito's Lambda triggers](http://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-identity-pools-working-with-aws-lambda-triggers.html).

Can Cognito be added as an event source?

**Comment by sanathkr** [comment]
Of course! Setting the relevant priority and keeping the Issue open for tracking.

**Comment by bombadiltom** [comment]
+1

**Comment by jlhood** [comment]
The path forward for this feature would be to propose SAM syntax for implementing this new event source. Then we can identify the areas of code that would need to be modified. Happy to work with anyone who would like to implement this!

**Comment by ajhool** [comment]
Serverless' existing cognito event source implementation and syntax is simple and looks good: https://serverless.com/framework/docs/providers/aws/events/cognito-user-pool/

**Comment by praneetap** [comment]
We had an existing [comment](https://github.com/awslabs/serverless-application-model/blob/cbd4d9ad40a71b838f1e72b3b960689f30890bf9/examples/2016-10-31/api_cognito_auth/template.yaml#L131) on the cognito user pool example. Does this look like what you had in mind?
```
      Events:
          myCognito:
           Type: CognitoUserPool
           Properties:
             UserPool: !Ref MyCognitoUserPool
             Trigger: PreSignUp (or array?)
```
Does it make sense for Triggers to be an array? That would allow you to set up multiple triggers for the same lambda function.
