### ISSUE TITLE
cors: true

### ISSUE THREAD

**Issue by nalbion** [awslabs/serverless-application-model#23]
One thing that I like about serverless.com is that CORS can be enabled for an endpoint in one short line:

    cors: true

Currently, to enable CORS using `x-amazon-apigateway-integration`, it is necessary to:

- add a header to each response:

```yaml
responses:
        '200':
          description: Request successful
          headers:
            Access-Control-Allow-Origin:
              type: string
          schema:
            $ref: '#/definitions/Success'
        '400':
          description: Authentication failed
          headers:
            Access-Control-Allow-Origin:
              type: string
          schema:
            $ref: '#/definitions/Error'
```

- add responseParameters in `x-amazon-apigateway-integration`:

```yaml
default:
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Origin : "'*'"
          '.*"status":400.*':
            statusCode: '400'
            responseParameters:
              method.response.header.Access-Control-Allow-Origin : "'*'"
```

- add a massive `options` section:
```yaml
options:
      summary: CORS support
      description: |
        Enable CORS by returning correct headers
      responses:
        200:
          description: Default response for CORS method
          headers:
            Access-Control-Allow-Headers:
              type: string
            Access-Control-Allow-Methods:
              type: string
            Access-Control-Allow-Origin:
              type: string
      x-amazon-apigateway-integration:
        type: mock
        requestTemplates:
          application/json: |
            {"statusCode" : 200}
        responses:
          "default":
            statusCode: "200"
            responseParameters:
              method.response.header.Access-Control-Allow-Headers : "'Content-Type,X-Amz-Date,Authorization,X-Api-Key'"
              method.response.header.Access-Control-Allow-Methods : "'*'"
              method.response.header.Access-Control-Allow-Origin : "'*'"
            responseTemplates:
              application/json: |
                {}
```

...it'd be great if `Transform: AWS::Serverless-2016-10-31` could transform the swagger schema, automatically adding all of this if `cors: true` is present in the CloudFormation object

**Comment by sanathkr** [comment]
I like this. This would be doable for implicit APIs specified in the Events section of a Function resource, because CloudFormation generates the swagger for you. For APIs created using AWS::Serverless::API resource, users will supply their own Swagger file in S3.  The logic that parses Serverless resources does not have the access to read and manipulate S3 files.

**Comment by nalbion** [comment]
Does the former allow you to save a local copy of the swagger schema, so that we may merge/cross-check the generated and documenting swagger schema?

**Comment by sanathkr** [comment]
Yeah. After you create the stack you can download the generated template using CloudFormation [get-template](http://docs.aws.amazon.com/cli/latest/reference/cloudformation/get-template.html) command. It will have the Swagger template embedded in it

**Comment by dinvlad** [comment]
This could be somewhat DRYed by defining the default response at the root of the Swagger file:
```
x-amazon-apigateway-integration-cors-headers:
  method.response.header.Access-Control-Allow-Methods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
  method.response.header.Access-Control-Allow-Headers: "'Content-Type,Authorization,X-Amz-Date,X-Api-Key,X-Amz-Security-Token'"
  method.response.header.Access-Control-Allow-Origin: "'*'"
```
After that, these headers can be referenced in `x-amazon-apigateway-integration:` through
```
responseParameters:
  allOf:
    - $ref: '#/x-amazon-apigateway-integration-cors-headers'
```

**Comment by nalbion** [comment]
Personally, I'm a fan of Swagger, but `x-amazon-apigateway-integration` with CORS adds too much noise.

**Comment by dinvlad** [comment]
It'd be nice to keep an option to specify a Swagger template, but without all the extra clutter. One case we need to use Swagger for is for input validation, where we'd like to make sure the shape of the API is preserved between that defined in a SAM template and that specified explicitly in Swagger (with the latter having extra information about input parameter types etc.)

Could there be an option to define a "template template" Swagger, with parameters specified over a `${SOME_VAR}` syntax that are then dynamically expanded during processing of the SAM template? This will be then very similar to how currently the SAM template is itself "expanded" into a normal CloudFormation template during packaging.

**Comment by frehner** [comment]
To echo what @rabowskyb said, it would be nice to have a `cors: true` option in the `sam.yml` file itself. I'm using SAM to build a lot of small microservices and a swagger file seems overkill for something that literally only has one endpoint.

**Comment by sanathkr** [comment]
Here is a proposal of how this could work. API Event will get a new property called `Cors`. Here are two ways to use it:

## Shorthand
```
Type: AWS::Serverless::Function
Properties:
  Runtime: ...
  Events:
     GetApi:
         Type: Api
         Properties:
              Cors: "*"
             Method: GET
             Path: /foo

     PostApi:
         Type: Api
         Properties:
              Cors: "http://example.com"
             Method: POST
             Path: /foo
```

This will generate CORS headers automatically, for each Path+Method combo and set Allow-Origin to "\*".  The value of Cors property is a list of origins you want to allow. Allow-Headers is always set to "\*".

## Long Form
```
Type: AWS::Serverless::Function
Properties:
  Runtime: ...
  Events:
     GetApi:
         Type: Api
         Properties:
              Cors: 
                  AllowOrigin: "List of origins"
                  AllowHeaders: "List of allowed headers"
             Method: GET
             Path: /foo

     PostApi:
         Type: Api
         Properties:
              Cors: 
                  AllowOrigin: "List of origins"
                  AllowHeaders: "List of allowed headers"
             Method: POST
             Path: /foo
```

This will generate CORS headers automatically, for each Path+Method combo and set Allow-Origin and Allow-Headers to whatever value that was specified. 

Would this address use-cases you guys are going after? 

Unfortunately we can't add the same functionality to `AWS::Serverless::Api` property because the translator converting SAM to CloudFormation cannot read and modify your Swagger file.
