### ISSUE TITLE
Lambda version with PreTraffic and PostTraffic hooks

### ISSUE THREAD

**Issue by abhilash80** [awslabs/serverless-application-model#230]
Hi,

The CodeDeploy integration thru SAM is pretty cool! 

I had a question regarding the [Pre & Post Hooks](https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst#pretraffic--posttraffic-hooks) - the payload to the lambda hook function includes 'DeploymentId' and 'LifecycleEventHookExecutionId', but no information on the lambda version itself for which the hook was triggered.

Whats the suggested approach for validating the function version being deployed thru the hook? 

Is it listing out all the versions for the function being deployed and explicitly calling the latest version?

Thanks

**Comment by jfuss** [comment]
@abhilash80 There is an open PR to address/update docs for this question (#246). I will be looking at this PR shortly but will answer your question here.

We recommend you pass the version of the Lambda function to the Pre or Post Hook through the Environment Variables block. Below is a short example. Doing it this way will give you the version that is currently being deployed. This will give you the version arn of the function that you can use to invoke or do whatever you need to.

```
PreTrafficLambdaFunction:
  Type: AWS::Serverless::Function
  Properties:
    Handler: preTrafficHook.handler
    Runtime: python3.6
    FunctionName: 'CodeDeployHook_preTrafficHook'
    DeploymentPreference:
      Enabled: false
    Environment:
      Variables:
        CurrentVersion: !Ref MyLambdaFunction.Version
```

Closing since we have a doc update PR in flight.
