### ISSUE TITLE
Globals are not parsed

### ISSUE THREAD

**Issue by nilesuan** [awslabs/serverless-application-model#237]
I've added

```
Globals:
  Function:
    Handler: index.handler
    Runtime: nodejs6.10
    MemorySize: 128
    Timeout: 60
```

to my template but was wondering why the function timed out after 3 seconds. Had to add a time-out to the resource itself.
