### ISSUE TITLE
Consider adding default Runtime for all Functions

### ISSUE THREAD

**Issue by dinvlad** [awslabs/serverless-application-model#24]
Currently, we have to explicitly set Runtime property for each Function resource, which makes the template unnecessarily verbose. Since most functions will likely be located in the same file (at least for a single resource) or a set of dependent modules, we can assume they will all run under the same runtime. Moreover, it would be nice to avoid hard-coding the runtime version into the template and specify it as a parameter instead:
```
Parameters:
  Runtime:
    Type: String
    Default: nodejs4.3
    AllowedValues:
      - nodejs
      - nodejs4.3
      - java8
      - python2.7
    ...
```
or even perhaps
```
Parameters:
  Runtime:
    Type: AWS::Lambda::Function::Runtime
    Default: nodejs4.3
    ...
```
for an ultimate conciseness. Or even better (though partisan), define nodejs4.3 as the default value of Runtime in the spec. In the latter case, one should still be able to easily specify a different _global_ runtime using syntax similar to the above. Needless to say, in all cases if any function still requires its own runtime, we would still be able to override the global default using the current syntax.
