### ISSUE TITLE
SAM policy templates for VPC don't seem to reliably work?

### ISSUE THREAD

**Issue by bluepeter** [awslabs/serverless-application-model#240]
I have a Lambda function defined with VPC access as follows:

```
  get:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri:
        Bucket:
          Fn::Sub: bigonion-deployment-helper-${AWS::AccountId}-${AWS::Region}
        Key: BigOnion_dummyFunction.zip
      FunctionName: BigOnion_get
      Policies:
        - VPCAccessPolicy: {}
        - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
      VpcConfig:
        SubnetIds:
          - Ref: VPCsubnet1
        SecurityGroupIds:
          - Ref: VPCsecuritygroup
```

The stack fails. Looking at the log, I can see that the Role is created with the VPC Access Policy:

```
        {
            "StackId": "arn:aws:cloudformation:us-east-1:xxx:stack/BigOnion/082d9e10-de40-11e7-9274-503acac41efd",
            "EventId": "getRole-UPDATE_COMPLETE-2017-12-21T03:01:29.349Z",
            "StackName": "BigOnion",
            "LogicalResourceId": "getRole",
            "PhysicalResourceId": "BigOnion-getRole-1WISQQA2H8J9K",
            "ResourceType": "AWS::IAM::Role",
            "Timestamp": "2017-12-21T03:01:29.349Z",
            "ResourceStatus": "UPDATE_COMPLETE",
            "ResourceProperties": "{\"ManagedPolicyArns\":[\"arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole\"],\"Policies\":[{\"PolicyName\":\"getRolePolicy0\",\"PolicyDocument\":{\"Statement\":[{\"Action\":[\"ec2:CreateNetworkInterface\",\"ec2:DeleteNetworkInterface\",\"ec2:DescribeNetworkInterfaces\",\"ec2:DetachNetworkInterface\"],\"Resource\":\"arn:aws:ec2:us-east-1:xxx:network-interface/*\",\"Effect\":\"Allow\"}]}}],\"AssumeRolePolicyDocument\":{\"Version\":\"2012-10-17\",\"Statement\":[{\"Action\":[\"sts:AssumeRole\"],\"Effect\":\"Allow\",\"Principal\":{\"Service\":[\"lambda.amazonaws.com\"]}}]}}\n"
        },
```

But then later the Lambda function fails with `The provided execution role does not have permissions to call CreateNetworkInterface on EC2`

```
        {
            "StackId": "arn:aws:cloudformation:us-east-1:xxx:stack/BigOnion/082d9e10-de40-11e7-9274-503acac41efd",
            "EventId": "get-UPDATE_FAILED-2017-12-21T03:02:09.752Z",
            "StackName": "BigOnion",
            "LogicalResourceId": "get",
            "PhysicalResourceId": "BigOnion_get",
            "ResourceType": "AWS::Lambda::Function",
            "Timestamp": "2017-12-21T03:02:09.752Z",
            "ResourceStatus": "UPDATE_FAILED",
            "ResourceStatusReason": "The provided execution role does not have permissions to call CreateNetworkInterface on EC2",
            "ResourceProperties": "{\"Role\":\"arn:aws:iam::xxx:role/BigOnion-getRole-1WISQQA2H8J9K\",\"FunctionName\":\"BigOnion_get\",\"Runtime\":\"nodejs6.10\",\"VpcConfig\":{\"SubnetIds\":[\"subnet-16a91239\"],\"SecurityGroupIds\":[\"sg-46534333\"]},\"Handler\":\"index.handler\",\"Code\":{\"S3Bucket\":\"bigonion-deployment-helper-xxx-us-east-1\",\"S3Key\":\"BigOnion_dummyFunction.zip\"},\"Tags\":[{\"Value\":\"SAM\",\"Key\":\"lambda:createdBy\"}]}\n"
        },
```

Any clues on how to get SAM policy templates for VPC working properly?

**Comment by bluepeter** [comment]
Update: I tried the `VPCAccessPolicy: {}` SAM policy template in all sorts of ways over the past few days. It simply does not work. Hopefully AWS will fix, or reveal the proper format. It certainly looks like it *SHOULD* work from the stack details.

In the mean time, you can verbosely attach the needed VPC policies as follows, and this does work:

```
  get:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri:
        Bucket:
          Fn::Sub: bigonion-deployment-helper-${AWS::AccountId}-${AWS::Region}
        Key: BigOnion_dummyFunction.zip
      FunctionName: BigOnion_get
      Policies:
    - PolicyName: "BigOnionVPCPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - ec2:CreateNetworkInterface
              - ec2:DeleteNetworkInterface
              - ec2:DescribeNetworkInterfaces
              - ec2:DetachNetworkInterface
            Resource: "*"
    VpcConfig:
      SubnetIds:
        - Ref: VPCsubnet1
      SecurityGroupIds:
        - Ref: VPCsecuritygroup
```
