### ISSUE TITLE
Example of APIG and Lambda integration

### ISSUE THREAD

**Issue by damluar** [awslabs/serverless-application-model#242]
In the example `api_swagger_cors` you connect Lambda to events from APIG in the following way:
```
Events:
        ProxyApiRoot:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /
            Method: ANY
```

But you also specify the mapping in the swagger definition (only POST for whatever reason):
```
/:
  ...
  uri: arn:aws:apigateway:<<region>>:lambda:path/2015-03-31/functions/arn:aws:lambda:<<region>>:<<accountId>>:function:${stageVariables.LambdaFunctionName}/invocations
  passthroughBehavior: when_no_match
  httpMethod: POST
```
Is it a duplication? If not, what is the difference?
