### ISSUE TITLE
Authorization on api?

### ISSUE THREAD

**Issue by willdady** [awslabs/serverless-application-model#25]
It seems it's not possible to define authorization (IAM or Custom) on the implicit API created as a lambda event source. And it looks like AWS::Serverless::Api doesn't support it either? Is there any plan to add this feature?

**Comment by dinvlad** [comment]
I think this can be done through the Swagger template, just add the following sections, the first one either at the top level of the file, or for individual resources:
```
security:
  - sigv4: []
securityDefinitions:
  sigv4:
    type: "apiKey"
    name: "Authorization"
    in: "header"
    x-amazon-apigateway-authtype: "awsSigv4"
```

**Comment by sanathkr** [comment]
Checkout /examples/2016-10-31/api_swagger_cors for example on how to use Swagger with SAM API

**Comment by mparaz** [comment]
I have Authorization working by specifying it in Swagger.

The tricky part is that it's necessary to explicitly permit it to be invoked by API Gateway. I used:

```
AuthorizerFunctionLambdaPermission:
  Type: AWS::Lambda::Permission
  Properties:
    FunctionName: !Ref Authorizerfunctsion
    Action: lambda:InvokeFunction
    Principal: apigateway.amazonaws.com
```

When I add an event to the authorizer function, to let SAM automatically creates the Permission, it looks like the permission isn't granted. I did:

```
AuthorizerFunction:
  Type: AWS::Serverless::Function
  Properties:
    Events:
      AuthorizerApiRoot: 
        Properties:
          Method: GET
          Path: /
          RestApiId: !Ref ApiGatewayApi
        Type: Api
    Handler: authorizer.handler
    Role: arn:aws:iam::570723136177:role/LambdaExecutionRole
    Runtime: nodejs4.3
```

But when I try this, in Cloudwatch I see `Invalid permissions on Lambda function.`
