### ISSUE TITLE
Circular dependency with CodeDeploy

### ISSUE THREAD

**Issue by jarreds** [awslabs/serverless-application-model#258]
We're receiving a circular dep error generating a CloudFormation changeset, and I'm uncertain how to troubleshoot. Looking for some help to figure out if this is an AWS bug or something wrong with the template.

This error began occurring directly after we renamed the stage and modified the `AWS::Serverless::Function` paths.

Here is the error:

`
Circular dependency between resources: [GetOpenCloseGetApiPermissionTest, GetCompanyGetApiPermissionTest, APIDeployment0455a86a11, APILiveStage, GetOpenCloseGetApiPermissionLive, GetCompanyGetApiPermissionLive, API]
`

Here is the template:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  Service:
    Type: String
  Stage:
    Type: String
  BucketName:
    Type: String
  Revision:
    Type: String
  Domain:
    Type: String

Resources:

  API:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Live
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub "s3://${BucketName}/services/${Service}/packages/${Revision}/api.yaml"

  GetCompany:
    Type: AWS::Serverless::Function
    Properties:
      Handler: iex.GetCompany::handleRequest
      Runtime: java8
      CodeUri: ../bazel-bin/iex/getCompany/lambda_deploy.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      AutoPublishAlias: Latest
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /v1.0/stock/{symbol}/company
            Method: get
            RestApiId:
                Ref: API

  GetOpenClose:
    Type: AWS::Serverless::Function
    Properties:
      Handler: iex.GetOpenClose::handleRequest
      Runtime: java8
      CodeUri: ../bazel-bin/iex/getOpenClose/lambda_deploy.jar
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 20
      AutoPublishAlias: Latest
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        GetApi:
          Type: Api
          Properties:
            Path: /v1.0/stock/{symbol}/open-close
            Method: get
            RestApiId:
                Ref: API

  GetCompanyPermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetCompany
      Principal: apigateway.amazonaws.com

  GetOpenClosePermission:
    Type: "AWS::Lambda::Permission"
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetOpenClose
      Principal: apigateway.amazonaws.com

Outputs:
  GatewayId:
    Value: !Sub '${API}'
    Export:
      Name: !Sub '${AWS::StackName}:GatewayId'
```
