### ISSUE TITLE
template resource

### ISSUE THREAD

**Issue by nalbion** [awslabs/serverless-application-model#26]
One of the downsides of the micro services architecture model is that there is more overhead because the configuration, management and deployment tasks are duplicated for each service.  Our swagger schemas and Cloudformation templates are full of copy-and-pasted snippets.

In the example below, the commonality is extracted into `LambdaTemplate`, reducing the `PutFunction` to 3 lines and allowing the differences between the other functions to be more obvious.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LambdaTemplate:
    Type: AWS::Serverless::TemplateFunction
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      Policies: AWSLambdaDynamoDBExecutionRole
      CodeUri: s3://bucketName/codepackage.zip
      Environment:
        Variables:
          TABLE_NAME: !Ref Table

  PutFunction:
    Type: AWS::Serverless::Function
    Properties:
      # extra points if this can (optionally) be imported from an external file, even in a separate but shared repository
      Template: !Ref LambdaTemplate
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Template: !Ref LambdaTemplate
      Handler: index.getHandler
  DeleteFunction:
    Type: AWS::Serverless::Function
    Properties:
      Template: !Ref LambdaTemplate
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt DynamoDBTable.StreamArn
            BatchSize: 100
            StartingPosition: TRIM_HORIZON

   DynamoDBTable:
     Type: AWS::DynamoDB::Table
     Properties: 
       AttributeDefinitions: 
         - AttributeName: id
           AttributeType: S
       KeySchema: 
         - AttributeName: id
           KeyType: HASH
       ProvisionedThroughput: 
         ReadCapacityUnits: 5
         WriteCapacityUnits: 5
       StreamSpecification:
         StreamViewType: streamview type
```
