### ISSUE TITLE
Filter policy support for SNS events

### ISSUE THREAD

**Issue by joshm91** [awslabs/serverless-application-model#261]
Hi guys,

It'd be great to be able to support the new(-ish) [Filter Policy](https://docs.aws.amazon.com/sns/latest/dg/message-filtering.html) feature in SNS when specifying an SNS event on a Lambda function.  

Something like this would be perfect:

```yaml
  myLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda_handlers.handler
      ...
      Events:
        SNS:
          Type: SNS
          Properties:
            Topic: !GetAtt someSnsTopic.Arn
            FilterPolicy:
              AttributeName1:
                - value1
                - value2
              AttributeName2:
                - value3
```
