### ISSUE TITLE
AutoPublishAlias with DynamoDB event source

### ISSUE THREAD

**Issue by moritzzimmer** [awslabs/serverless-application-model#273]
According to the [docs](https://github.com/awslabs/serverless-application-model/blob/master/docs/safe_lambda_deployments.rst#instant-traffic-shifting-using-lambda-aliases) _AutoPublishAlias_ will

> Point all event sources to the Alias & not the function

I tried this with my function and it seems like the trigger is lost after adding _AutoPublishAlias_ to the SAM template. Guess I'm doing something wrong in the deployment?

Deployment steps:
```
zip main.zip ./main
aws cloudformation package --template-file template.yaml --s3-bucket $(BUCKET) --output-template-file packaged.yaml --region eu-west-1

aws cloudformation deploy --template-file ./packaged.yaml --stack-name $(PROJECT_NAME) --region eu-west-1 
```

This is the template:

```
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: my-function
      MemorySize: 128
      Timeout: 60
      Role: some-role
      Handler: main
      CodeUri: main.zip
      Runtime: go1.x
      AutoPublishAlias: live
      Events:
        Stream:
          Type: DynamoDB
          Properties:
            Stream: arn:aws:dynamodb:eu-west-1:some-stream
            BatchSize: 100
            StartingPosition: TRIM_HORIZON
```
