### ISSUE TITLE
Specifying RestApiId for EventSource will not update Lambda policy to let RestApiId Gateway invoke Lambda

### ISSUE THREAD

**Issue by quarryman** [awslabs/serverless-application-model#274]
Flow to reproduce
## Using SAM create Lambda and add API Gateway Event to trigger it 

```
GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      Runtime: nodejs4.3
      Role: LambdaExecutionRole
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /test
            Method: get
```
Expected result: 
1. Lambda is created
2. API Gateway (InitialAPIGateway) is created
3. "/test" endpoint is created
4. InitialAPIGateway is granted permission to invoke lambda

## Next step - we want to add swagger based API Gateway (to add CORS).

API Gateway Resource is added to SAM
```
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: s3://<bucket_name>/swagger.yaml

```
Swagger file  similar to one in examples folder is uploaded to bucket

Lambda is updated to reference created API Gateway
```
GetHelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.get
      Runtime: nodejs4.3
      Role: LambdaExecutionRole
      Events:
        GetEvent:
          Type: Api
          ---->>>RestApiId: !Ref ApiGatewayApi
          Properties:
            Path: /test
            Method: get
```

Expected result:
1. Lambda is updated
2. API Gateway (SwaggerBasedGateway) is created
3. "/test" endpoint is created in SwaggerBasedGateway
4. SwaggerBasedGateway is granted permission to invoke lambda

Unexpected behavior:
1. Two API Gateways is created - InitialGateway and SwaggerBasedGateway
2. Lambda policy has rules for invocation by InitialGateway but has no rules for invocation by SwaggerBasedGateway. Lambda policy is not updated to allow invocation from Swagger generated api.

In [other issue](https://github.com/awslabs/serverless-application-model/issues/59#issuecomment-348709355) it was mentioned 
> If you are using separate Swagger, make sure you add the APIs to the events section as well. This will make SAM add correct Lambda::Permissions. See https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/template.yaml#L24-L35

This doesn't seem to work, as after referencing API in event, Lambda permission is not updated to be invoked from new API.
 
```
Events:
        GetEvent:
          Type: Api
          RestApiId: !Ref ApiGatewayApi
```

Admitting this is not known issue when Lambda can not be invoked from Gateway API Console.
In this case Curl gives the same result as function policy is not updated.
Additionally I am not sure if this use-case should result in deploying 2 Gateway APIs once I reference RestApiId created from Swagger in event source. 

Adding permissions to invoke Lambda in SAM is not an approach as long as it must be defined for each Lambda in template separately as FunctionName property doesnt accept array. 

```
  ConfigLambdaPermission:
    Type: "AWS::Lambda::Permission"
    DependsOn:
    - GetHelloWorld
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !Ref GetHelloWorld
      Principal: apigateway.amazonaws.com
```
