### ISSUE TITLE
[Bug] SAM/CFN returns Circular Dependency Error due to malformed Pseudo Parameter

### ISSUE THREAD

**Issue by heitorlessa** [awslabs/serverless-application-model#276]
Hi,

 While creating an application I noticed that SAM complained about **Circular Dependency** in the following template:

```yaml
    MyParameter:
        Type: "AWS::SSM::Parameter"
        Properties: 
            Name: !Sub EdgeSigningSecretBlah-${AWS::Stack}
            Description: My Parameter
            Type: String
            Value: String

    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
          CodeUri: ../my-function/
          Runtime: nodejs6.10
          Handler: app.handler
          Timeout: 5
```

After a double checking the template I realized that there was a typo in the SSM Parameter Name where``${AWS::Stack}`` should have been ``${AWS::StackName}`` - When corrected the stack was deployed and everything worked as expected.

It seems that this is causing some issues when SAM Transformer explodes the resources and CFN returns this unrelated error that causes confusion - It'd be great to get this fixed or maybe we can create a FAQ.md to take note of occurrences like these.

Happy to provide any more details beyond that if necessary
