### ISSUE TITLE
Using a `AutoPublishAlias` with an `"AWS::Lambda::EventSourceMapping"` resource

### ISSUE THREAD

**Issue by gallamine** [awslabs/serverless-application-model#278]
Perhaps I'm missing something, but if I define a serverless function, like so:

```
aggregateScores:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: aggregator.lambda_handler
      Runtime: python3.6
      CodeUri: ./aggregator
      Description: score aggregator
      MemorySize: 128
      Timeout: 120
      Role: 'arn:aws:iam::<>:role/rolename'
      # Event source mapping below
      AutoPublishAlias: test
```

and now I want to define its event triggers using an `"AWS::Lambda::EventSourceMapping"` resource, how do I make sure the `EventSourceMapping` points to the alias and not the root function?

```
  prodLambdaTriggerAggregator:
    Type: "AWS::Lambda::EventSourceMapping"
    Properties:
      Enabled: True
      EventSourceArn: !GetAtt
        - rawDataStream
        - Arn
      FunctionName: !Ref <what goes here??>
      StartingPosition: TRIM_HORIZON
      BatchSize: 25
```
