### ISSUE TITLE
Is possible to define a catch-all path for api event?

### ISSUE THREAD

**Issue by shangsunset** [awslabs/serverless-application-model#283]
When defining SAM `template.yml`, how can I write a path for the lambda function so it catches all possible routes? This function will be used for url redirecting/forwarding. I tried the following but didn't seem to be working.
```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  Home:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      Runtime: go1.x
      Environment:
        Variables:
          REDIRECT_BASE_URL: https://xxx.xxx.com/
      Tracing: Active
      Events:
        GetEvent:
          Type: Api
          Properties:
            Path: /*
            Method: get
```

Thanks!
