### ISSUE TITLE
DynamoDBStreamReadPolicy is cumbersome to work with

### ISSUE THREAD

**Issue by iamatypeofwalrus** [awslabs/serverless-application-model#289]
Hi!

I'm spinning up a toy Go lambda that reads stream events from a DynamoDB table. Both are specified in the same CloudFormation template.

The [DynamoDBStreaReadPolicy](https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/policy_templates/all_policy_templates.yaml#L60) requires the table name and a stream name. It looks like [it's constructing the `StreamArn` under the hood](https://docs.aws.amazon.com/serverlessrepo/latest/devguide/using-aws-sam.html#dynamo-db-stream-read-policy).

The DynamoDB table resource already includes a [return value for the `StreamArn`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dynamodb-table.html#w2ab2c21c10d336c15) but it doesn't look like it gives access to the stream's name. Given that it's some sort of timestamp it looks like it will be difficult to infer the stream name without creating the stream first.

Can the `DynamoDBStreaReadPolicy` be updated to accept the `StreamArn` directly?

**Comment by brettstack** [comment]
Agreed. It's likely more simple to pass in the StreamArn directly. Could you try using the `Split` and `Select` functions https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-split.html to get the stream name?

```yaml
StreamName: !Select [2, !Split ["/", !GetAtt Table.StreamArn]]
```

In order to make this change we would need to mark this policy template as deprecated and create a new one which accepts a `StreamArn` so as not to break backwards compatibility. Let me now if this works. And if it does, I'd love to see a PR to the examples directory.

**Comment by 0xdevalias** [comment]
Not sure if this has changed since this issue was opened, but my stream reader looks like this and seems to work:

```yaml
Table:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      ProvisionedThroughput:
        WriteCapacityUnits: 1
        ReadCapacityUnits: 1
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - KeyType: HASH
          AttributeName: id

TableChanged:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-TableChanged
      Description: Table stream watcher and event handler
      CodeUri: ./target
      Handler: tableChanged
      Runtime: go1.x
      Events:
        TableEventSource:
          Type: DynamoDB
          Properties:
            Stream: !GetAtt Table.StreamArn
            StartingPosition: TRIM_HORIZON
            BatchSize: 10
      Policies:
        - Statement:
          - Effect: Allow
            Action:
              - ses:SendEmail
            Resource: !Sub
              - "arn:${AWS::Partition}:ses:${region}:${AWS::AccountId}:identity/${identityName}"
              - { region: "us-east-1", identityName: "*" }
```
