### ISSUE TITLE
S3CrudPolicy does not allow object deletion

### ISSUE THREAD

**Issue by technivore** [awslabs/serverless-application-model#294]
The current definition of S3CrudPolicy only allows object create, read, and update permissions. Please add the `s3:DeleteObject` permission to the policy.

**Comment by oharaandrew314** [comment]
Yes, I confirmed this myself.

**Comment by tmclaugh** [comment]
Just got bit by this and can't release [ServerlessOpsIO/aws-application-dollar-monitoring](https://github.com/ServerlessOpsIO/aws-application-dollar-monitoring) to AppRepo as a result. :(

**Comment by oharaandrew314** [comment]
You can get around it by manually writing out a policy.

```
  DeleteData:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ...
      CodeUri: ....
      Policies:
        -
          Version: 2012-10-17
          Statement:
            -
              Effect: Allow
              Action:
                - s3:DeleteObject
              Resource: !Sub ${MyBucket.Arn}/*
```
