### ISSUE TITLE
RDS DBInstanceIdentifier is not working with Join, Sub... any function which return string.

### ISSUE THREAD

**Issue by xkguq007** [awslabs/serverless-application-model#299]
Just work with simple string ex) DBInstanceIdentifier: AbcTest
I also test using DBInstanceIdentifier: !Sub [${Abc}-hi, { Abc: !Ref ServiceName }]

```
  DbInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      AllocatedStorage: '5'
      DBName: !Join ['', [!Ref ServiceName, rds]] => NOT WORK
      DBInstanceIdentifier: => NOT WORK
        Fn::Join:
          - '-'
          - - !Ref ServiceName
            - rds
            - ins
      DBInstanceClass: db.t2.micro
      Engine: MYSQL
      EngineVersion: 5.7
      MasterUsername: !Ref DbUsername
      MasterUserPassword: !Ref DbPassword
      MultiAZ: false
      PubliclyAccessible: false
```

Edit, I was wrong it was DBInstanceIdentifier not DBName.
