### ISSUE TITLE
Issue with query param encoding

### ISSUE THREAD

**Issue by paddymonahan** [awslabs/serverless-application-model#301]
Hey Guys!

Currently facing an issue which I suspect is to do with encoding config somewhere. I'm trying to pass through an email address as a query param in a POST to my lambda endpoint.

`eg. endpoint.com/action?email=test+email@test.com`

The problem is that "+" characters are being removed from the query params.

I followed the instructions to map query params to the event object [here](https://serverless.com/framework/docs/providers/aws/events/apigateway/#pass-through-behavior
)
and have the following in my serverless.yml:
 
```
 - http:
          path: create_case
          method: post
          cors: true
          request:
            template:
              application/json: '{ "email" : "$input.params( ' 'email ' ' )", "password" : "$input.params( ' ' password ' ' )" }'

```
this results in the address being passed to the event object without the + character:
```eg 'me+test@test.com' becomes 'me test@test.com'```

If I encode the special characters eg. test%2Baddress@test.com it is parsed as two separate parts of the query eg.
```
 test%2Baddress@test.com becomes { 'email' :' test', 'address@test.com': ''}
```

If anyone could point me in the right direction that would be fantastic,
Cheers
