### ISSUE TITLE
Specifying Global Runtime issue

### ISSUE THREAD

**Issue by mhball** [awslabs/serverless-application-model#302]
The following template.yaml with the Runtime specified as a Global parameter causes the following error on starting SAM local:
`Ignoring MyFunction (com.andium.cloud.datacore.api.ProxyWithStream::handleRequest) due to unsupported runtime ()`

However, moving the `Runtime: java` line down into the function itself runs fine.

template.yaml
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: My first serverless application.

Globals:
  Function:
    CodeUri: target/datacore.api-1.0-SNAPSHOT.jar
    Runtime: java8

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.andium.cloud.datacore.api.ProxyWithStream::handleRequest
      Events:
        Test:
          Type: Api
          Properties:
            Path: /test
            Method: get
```
