### ISSUE TITLE
S3 Event Source Mapping: Could not list s3 event sources.

### ISSUE THREAD

**Issue by smugcloud** [awslabs/serverless-application-model#31]
Hi Guys,

I was evaluating SAM and created a stack with the YAML below.  The stack creates fine, but if I view the Lambda function triggers, I only see an error: `Could not list s3 event sources.`

If I inspect this function via the API, no even sources are mapped to the function.  Is this a problem with my YAML, or a bug?

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A function is triggered off an upload to a bucket. It logs the content type of the uploaded object.
Resources:
  ProcessorFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: s3://<mybucket>/HelloWorldNode.zip
      Policies: AmazonS3ReadOnlyAccess
      Events:
        Addition:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*

  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sam-cfn-test
```
