### ISSUE TITLE
Regression in SAM/Cloudformation

### ISSUE THREAD

**Issue by parsnips** [awslabs/serverless-application-model#322]
As of about an hour ago all change-set creation started to fail:

```
FAILED - Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 13. Resource with id [PatchConsumer] is invalid. Event with id [GetApi] is invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource in same template Resource with id [GetEconomicData] is invalid. Event with id [GetApi] is invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource in same template Resource with id [GetAllContacts] is invalid. Event with id [GetApi] is invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource in same template Resource with id [PostConsumer] is invalid. Event with id [GetApi] is invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource in same template Resource with id [GetContact] is invalid. Event with id [GetApi] is invalid. RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource in same template Resource with id [PatchAddress] is...
```
across all of our stacks having similar issue.

cc @sanathkr

**Comment by sanathkr** [comment]
Taking a look. Which region are you using?

**Comment by parsnips** [comment]
us-west-2

**Comment by sanathkr** [comment]
This is a regression, because we added explicit checks for some unsupported cases that were not checked earlier. But it is a small one that you can fix yourself:

What is the value of RestApiId in the Events structure? The only supported value is `{"Ref": "LogicalId"}` or `"LogicalId"`

### Supported values for RestApiId

**LogicalId of AWS::Serverless::Api resource**
```
Events:
  MyApi:
    Type: Api
     Properties: 
       Path: /foo
       Method: GET
      # Direct value of the logical ID
       RestApiId: MyServerlessApi
```

**"Ref" of LogicalId of AWS::Serverless::Api resource**
```
Events:
  MyApi:
    Type: Api
     Properties: 
       Path: /foo
       Method: GET
      # Ref of the logical ID
       RestApiId: {"Ref": "MyServerlessApi"}
```

### Unsupported

**Any other intrinsic functions**
```
Events:
  MyApi:
    Type: Api
     Properties: 
       Path: /foo
       Method: GET
      # Fn::Sub of the logical ID
       RestApiId: {
          "Fn::Sub": "${MyServerlessApi}"
       }
```

If you happened to use other intrinsic functions, you should migrate to one of the supported structures. There should be absolutely no change in end result for you.

**Comment by parsnips** [comment]
Ok, we are using `Sub` there at the moment:

```
      Events:
        GetApi:
          Properties:
            Method: get
            Path: /v3.0/address/{address_id}
            RestApiId:
              Fn::Sub: ${API}
          Type: Api
```
We'll go ahead and apply the `Ref` instead. Thanks for quick turn around.
