### ISSUE TITLE
Using API Gateway ANY method yields 500 when invoking

### ISSUE THREAD

**Issue by oharaandrew314** [awslabs/serverless-application-model#326]
I'd like to be able to set up event triggers to proxy http requests from Api Gateway.  Notice how I have an `any` method event for the `/pets`, and `/pets{petId}` paths.

```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: aws-lambda-rest example for pets endpoints

Resources:
  PetsResource:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.andrewohara.pets.PetsResource
      Runtime: java8
      CodeUri: ./kobaltBuild/libs/example-pets-0.0.1.jar
      Timeout: 30
      MemorySize: 1024
      Events:
        Pets:
          Type: Api
          Properties:
            Path: /pets
            Method: any
        Pet:
          Type: Api
          Properties:
            Path: /pets/{petId}
            Method: any
```

The API Gateway appears to be set up correctly.  However, when I invoke the method, I get a `500` error.

```
Thu Mar 08 21:03:00 UTC 2018 : Execution failed due to configuration error: Invalid permissions on Lambda function
Thu Mar 08 21:03:00 UTC 2018 : Method completed with status: 500
```

This is easily fixed by explicitly writing out an event for each HTTP resource/path combination, but it would be nice to have this method supported, since API Gateway supports it.
