### ISSUE TITLE
VPCAccessPolicy does not take effect.

### ISSUE THREAD

**Issue by vinkris** [awslabs/serverless-application-model#327]
```
AdminReturn:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-${EnvName}-adminreturn
      CodeUri: ../build
      Handler: handler.adminReturn
      Policies:
        - VPCAccessPolicy: {}
        - DynamoDBCrudPolicy:
            TableName: !Ref TenantsTable
      VpcConfig:
        SubnetIds: !Split [ ',', 'Fn::ImportValue': !Sub "${BaseVPCStackName}-${EnvName}-SubnetsPrivateAppIds" ]
        SecurityGroupIds: ['Fn::ImportValue': !Sub "${BaseVPCStackName}-${EnvName}-AzureAdSG" ]
      Environment:
        Variables:
          TENANTSTATE_TABLE: !Ref TenantsTable
          DEP_ENVIRONMENT: !Ref EnvName
          DEV_PROFILE: !Ref AzureADDepProfile
      Events:
        Consent:
          Type: Api
          Properties:
            Path: /adminreturn
            Method: get
            RestApiId:
              !Ref AzureADSyncAPI

```

I have a serverless function as above, and I keep getting the following error in Cloudformation:

> The provided execution role does not have permissions to call CreateNetworkInterface on EC2

Everything works fine if I use the AWS managed policy `AWSLambdaENIManagementAccess`, but I really want the policy to be specific to the resources being used by Lambda. Of course, we could write up a policy by hand which is specific to our needs, I am still wondering why this `VPCAccessPolicy: {}` wouldn't work as an inline policy. 

Also, I observed that `VPCAccessPolicy` does work sometimes, although its not clear when.
