### ISSUE TITLE
SNS topic to being linked to Function with Alias? 

### ISSUE THREAD

**Issue by avish1990** [awslabs/serverless-application-model#332]
Hi, The SNS trigger is not getting created automatically when template is deployed. Seems to be an issue with "AutoPublishAlias: test". Works just fine if i remove the alias.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Serverless Specification template describing your function.
Resources:
  SSM:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'SSM'
      AutoPublishAlias: test
      Handler: index.handler
      Runtime: python3.6
      CodeUri: .
      Description: ''
      MemorySize: 128
      Timeout: 3
      Role: 'arn:aws:iam::712115679703:role/Lambda-ssm-ec2'
      DeploymentPreference:
        Type: AllAtOnce
      Events:
        MyTopic:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic
           
  SNSTopic:
    Type: 'AWS::SNS::Topic'
    Properties:
      DisplayName: SNSTopic
```
