### ISSUE TITLE
Request: import published serverless application repository functions to a local template

### ISSUE THREAD

**Issue by smithclay** [awslabs/serverless-application-model#348]
Think it'd be very useful to be able to import applications published to the public serverless application repository into local SAM templates.

For example, for any SAM template, being able to reference a public SAR function by an S3 URI like this:

```
  MySARFunction:
    Type: AWS::Serverless::Function
    Properties:
      # some uri that references a version published to the SAR
      CodeUri: s3://<<PUBLIC SAR FUNCTION URI@VERSION>>>
```

This is equivalent to using the SAR UI (i.e. the 'deploy' button) except I'm using the published function alongside an existing local DAM template. 

Think this would be useful and encourage published SAR functions to be used in larger, more complex SAM templates. If there's a workaround or (undocumented?) URI that could be used directly would be appreciated if this functionality already exists. Thanks!
