### ISSUE TITLE
'AutoPublishAlias' must be a string or a Ref to a template parameter

### ISSUE THREAD

**Issue by joaowingmaite** [awslabs/serverless-application-model#3717]
### Description
When using `sam deploy` with the `AutoPublishAlias` property in the template it always returns the error:

```
Error: Failed to create changeset for the stack: stack-name, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [DocumentLoaderFunction] is invalid. 'AutoPublishAlias' must be a string or a Ref to a template parameter
```

Note 1: This happens wether I use a string directly or a !Ref to a Template Parameter
Note 2: This fails in macOS, but for example when running in a Github Action it works correctly.

### Steps to reproduce
Use the following template:

```yml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Sample

Globals:
  Function:
    Timeout: 30

Resources:
  SomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: function/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      MemorySize: 512
      Timeout: 60
      FunctionName: SomeFunction
      AutoPublishAlias: DEV
      Architectures:
        - x86_64
      Role: arn:aws:iam::XXXXXX:role/SomeRole
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
````

Run
```bash
sam deploy
```

### Observed result

```
Error: Failed to create changeset for the stack: stack-name, ex: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state: For expression "Status" we matched expected path: "FAILED" Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [DocumentLoaderFunction] is invalid. 'AutoPublishAlias' must be a string or a Ref to a template parameter
```

### Expected result

A success full deploy

### Additional environment details

1. OS: macOS 15.3 (Sequoia)
2. If using the [SAM CLI](https://github.com/aws/aws-sam-cli), `sam --version`: 1.133.0
3. AWS region: eu-central-1

**Comment by vicheey** [comment]
Hi @joaowingmaite, 

Your template looks correct and should work. We attempted to reproduce this using a minimal template with `AutoPublishAlias: DEV` on macOS with the latest SAM CLI, and the transform completed successfully — the alias, version, and role resources were all generated as expected.

SAM Template: 
```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Repro for SAM-3717: AutoPublishAlias validation failure

Globals:
  Function:
    Timeout: 30

Resources:
  SomeFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs20.x
      MemorySize: 512
      Timeout: 60
      AutoPublishAlias: DEV
      Architectures:
        - x86_64
    Metadata:
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts
```
Transformed CFN Template: 
```yaml
2026-04-24 14:03:01 Transformed template from AWS::Serverless-2016-10-31: 
{
 "AWSTemplateFormatVersion": "2010-09-09",
 "Description": "Repro for SAM-3717: AutoPublishAlias validation failure\n",
 "Resources": {
  "SomeFunction": {
   "Metadata": {
    "BuildMethod": "esbuild",
    "BuildProperties": {
     "EntryPoints": [
      "app.ts"
     ],
     "Minify": true,
     "Sourcemap": true,
     "Target": "es2020"
    }
   },
   "Properties": {
    "Architectures": [
     "x86_64"
    ],
    "AutoPublishAlias": "DEV",
    "CodeUri": "s3://bucket/value",
    "Handler": "app.lambdaHandler",
    "MemorySize": 512,
    "Runtime": "nodejs20.x",
    "Timeout": 60
   },
   "Type": "AWS::Serverless::Function"
  }
 },
 "Transform": "AWS::Serverless-2016-10-31"
}
2026-04-24 14:03:01 Transformed template: 
{
 "AWSTemplateFormatVersion": "2010-09-09",
 "Description": "Repro for SAM-3717: AutoPublishAlias validation failure\n",
 "Resources": {
  "SomeFunction": {
   "Metadata": {
    "BuildMethod": "esbuild",
    "BuildProperties": {
     "EntryPoints": [
      "app.ts"
     ],
     "Minify": true,
     "Sourcemap": true,
     "Target": "es2020"
    }
   },
   "Properties": {
    "Architectures": [
     "x86_64"
    ],
    "Code": {
     "S3Bucket": "bucket",
     "S3Key": "value"
    },
    "Handler": "app.lambdaHandler",
    "MemorySize": 512,
    "Role": {
     "Fn::GetAtt": [
      "SomeFunctionRole",
      "Arn"
     ]
    },
    "Runtime": "nodejs20.x",
    "Tags": [
     {
      "Key": "lambda:createdBy",
      "Value": "SAM"
     }
    ],
    "Timeout": 60
   },
   "Type": "AWS::Lambda::Function"
  },
  "SomeFunctionAliasDEV": {
   "Metadata": {
    "BuildMethod": "esbuild",
    "BuildProperties": {
     "EntryPoints": [
      "app.ts"
     ],
     "Minify": true,
     "Sourcemap": true,
     "Target": "es2020"
    }
   },
   "Properties": {
    "FunctionName": {
     "Ref": "SomeFunction"
    },
    "FunctionVersion": {
     "Fn::GetAtt": [
      "SomeFunctionVersioneedba9004b",
      "Version"
     ]
    },
    "Name": "DEV"
   },
   "Type": "AWS::Lambda::Alias"
  },
  "SomeFunctionRole": {
   "Metadata": {
    "BuildMethod": "esbuild",
    "BuildProperties": {
     "EntryPoints": [
      "app.ts"
     ],
     "Minify": true,
     "Sourcemap": true,
     "Target": "es2020"
    }
   },
   "Properties": {
    "AssumeRolePolicyDocument": {
     "Statement": [
      {
       "Action": [
        "sts:AssumeRole"
       ],
       "Effect": "Allow",
       "Principal": {
        "Service": [
         "lambda.amazonaws.com"
        ]
       }
      }
     ],
     "Version": "2012-10-17"
    },
    "ManagedPolicyArns": [
     "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
    ],
    "Tags": [
     {
      "Key": "lambda:createdBy",
      "Value": "SAM"
     }
    ]
   },
   "Type": "AWS::IAM::Role"
  },
  "SomeFunctionVersioneedba9004b": {
   "DeletionPolicy": "Retain",
   "Metadata": {
    "BuildMethod": "esbuild",
    "BuildProperties": {
     "EntryPoints": [
      "app.ts"
     ],
     "Minify": true,
     "Sourcemap": true,
     "Target": "es2020"
    }
   },
   "Properties": {
    "FunctionName": {
     "Ref": "SomeFunction"
    }
   },
   "Type": "AWS::Lambda::Version"
  }
 }
}

```

The differences of SAM CLI versions and the environment variables on your local macOS machine and CI could cause the transformation issue. I suggest cleaning up the .aws-sam folder, update SAM CLI version and try building again. 
   
Feel free to open the issue again and add link of this issue in the new issue if the problem persist. Thanks.
