### ISSUE TITLE
Enable CORS options in `Api` event type

### ISSUE THREAD

**Issue by lmammino** [awslabs/serverless-application-model#373]
**Description:**

At the moment it seems to be possible to use the `Cors` options only with resources of type `AWS::Serverless::Api`, for which you have to create a dedicated swagger file.

I have seen pretty often people preferring to just create Lambda functions by using the type `AWS::Serverless::Function` and then attaching to it an event of type `Api`.

I was expecting the `Cors` option to be exposed to an `Api` event as well, but that's apparently not the case.

**Example:**

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Some sample API

Resources:
  purchaseTicket:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: index.purchaseTicket
      Runtime: nodejs8.10
      Role: !GetAtt MyRole.Arn
      Events:
        Endpoint:
          Type: Api
          Properties:  # <--- No way to define Cors here!
            Path: /purchase
            Method: post
```

Is there something I am missing here? If this is really a missing feature, is there any plan to include support for the Cors option in the `Api` event type?

Personally, I think it will be very convenient to have this and I am quite sure it would lead to a more consistent Developer Experience.

**Comment by sanathkr** [comment]
This is available. Cors is exposed on API using Globals. You can define Cors for all your APIs but not at  individual API level.

**Comment by lmammino** [comment]
Thanks for the quick reply @sanathkr, do you have an example for this?

**Comment by lmammino** [comment]
Skip that, Just found it :) https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#globals-section

Gonna close the issue! Thanks!

**Comment by sanathkr** [comment]
https://github.com/awslabs/serverless-application-model/blob/develop/examples/2016-10-31/implicit_api_settings/template.yaml

**Comment by jfuss** [comment]
Doc update? I have been asked this question once or twice already as well.

**Comment by lmammino** [comment]
@sanathkr, @jfuss : I just updated my serverless/SAM workshop to use globals and the CORS options: https://github.com/lucpod/ticketless

Maybe there are parts of it that can be reused to improve the docs. CORS is introduced in [Lesson 6](https://github.com/lucpod/ticketless/tree/master/lessons/06-purchase-ticket-api#0604---enabling-cors-for-non-get-requests).

What do you guys think?

**Comment by manishgkasera** [comment]
agree with @tkeeber Global cors option is only doing half work, its still a pain to get it working.

**Comment by scubbo** [comment]
@tkeeber  , I had a similar problem. According to [here](https://serverless.com/blog/cors-api-gateway-survival-guide/#cors-preflight-requests), there are actually two ways of authorizing CORS:
* Via a "preflight request" to OPTIONS
* Via headers on the direct response

Apparently Preflight requests aren't made on "simple requests" ("_a GET request or a POST request with form data that has no authentication_"). If you're in that bucket (as I am!), you will need to set the headers manually on your response. [Here's](https://github.com/scubbo/popCultureGraph/commit/7941445e7a9296cfbcd815645c3004c7b75b21e5) an example where I added them manually - though if you're using Python, you may prefer [this](https://lambda-decorators.readthedocs.io/en/latest/#lambda_decorators.cors_headers).

**Comment by MatteoGioioso** [comment]
Same problem. I have allowed Cors on `AWS::Serverless::API`, but it is still not working.

**Comment by praneetap** [comment]
@MatteoGioioso Can you share your template and the exact issue you are facing? We would love to root cause the issue..

**Comment by MatteoGioioso** [comment]
@praneetap Thanks for the answer. I took another approach. I just assign these headers on my response 
```
"Access-Control-Allow-Origin":  "*",
"Access-Control-Allow-Headers": "*",
"Access-Control-Allow-Methods": "*",
```

**Comment by ethaneisenhard** [comment]
> This is available. Cors is exposed on API using Globals. You can define Cors for all your APIs but not at individual API level.

Do you think it's possible to set on an individual API level now? Else what is the best practice to handle different headers for public and private APIs? (IE. I want private APIs to have authorization header and public NOT to have authorization header. I would like to avoid two different YAML files, but that seems like one way to do it.

**Comment by jaads** [comment]
i still have problems enabling CORS in my app. Here is a snippet from my SAM template
```
Globals:
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Auth:
        Authorizers:
          MyCognitoAuthorizer: ...

  getByIdFunc:
    Type: AWS::Serverless::Function
    Properties:
      Handler: src/handler.handle
      MemorySize: 128
      Policies: ...
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{id}
            Method: GET
            RestApiId: !Ref MyApi
```
any ideas?
adding the header to the response myself works fine but i rather have it defined in the template.
