### ISSUE TITLE
AWS::Serverless:SimpleTable server-side encryption

### ISSUE THREAD

**Issue by oharaandrew314** [awslabs/serverless-application-model#376]
`AWS::DynamoDB::Table` supports server-side encryption, but this is not an option for `AWS::Serverless::SimpleTable`.  I propose that we add a property to enable it, while it remains disabled by default.

**SAM Template:**

```yaml
MyTable:
  Type: AWS::Serverless::SimpleTable
  Properties:
    ...
    SSESpecification:
      SSEEnabled: boolean
```

**Transformed CFN Template:**

```yaml
MyTable:
  Type: AWS::DynamoDB::Table
  Properties:
    ...
    SSESpecification:
      SSEEnabled: boolean
```

I'm willing to work on this.  I think it's a great first-issue now that the SAM translator is open-source.
