### ISSUE TITLE
Local CodeURI in globals generates an enormous deploy package

### ISSUE THREAD

**Issue by jtratner** [awslabs/serverless-application-model#383]
**Description:**

If I have a template pointing to a zip file in all of my functions if I specify CodeUri in each, the uploaded zip file is ~48K; however, if I put it in globals, `aws cloudformation package` causes a 19MB zip file to be uploaded. Seems like a bug :-/

**Steps to reproduce the issue:**

i.e., this causes a 19MB file to be uploaded:

```
Globals:
  Function:
    Runtime: python3.6
    CodeUri: ./output.zip
Resources:
  Func1:
    Type: AWS::Serverless::Function
  Func2:
    Type: AWS::Serverless::Function
  Func3:
    Type: AWS::Serverless::Function
```

and this template causes a 48K file to be uploaded:

```
Globals:
  Function:
    Runtime: python3.6
Resources:
  Func1:
    Type: AWS::Serverless::Function
    CodeUri: ./output.zip
  Func2:
    Type: AWS::Serverless::Function
    CodeUri: ./output.zip
  Func3:
    Type: AWS::Serverless::Function
    CodeUri: ./output.zip
```

**Observed result:**

```
$ aws cloudformation package ...
<snip>
Uploading to <key>  18379195 / 18379195.0  (100.00%)
<snip>
```

**Expected result:**

(what you see when you put CodeUri into each function)
```
$ aws cloudformation package ...
<snip>
Uploading to <key>  46693 / 46693.0  (100.00%)
<snip>
```
