### ISSUE TITLE
Passing ServerlessRestApi to function variables creates circular dependencies

### ISSUE THREAD

**Issue by mtb-xt** [awslabs/serverless-application-model#386]
**Description:**

I'm trying to pass the generated implicit API url to a function, but it fails with circular dependencies error:
code sample:
```
  Clients:
    Type: "AWS::Serverless::Function"    
    CodeUri: ./lambdas/clients/build/main
    Properties:
      Handler: ./lambdas/clients/build/main
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ClientsTable
      Environment:
        Variables:
          TABLE_NAME: !Ref ClientsTable
          BASE_URL: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
```

I tried adding a dependency to the implicit resource, but it didn't help. 
```
DependsOn: "ServerlessRestApi"
```

cloudformation output:

Waiting for changeset to be created..

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state 
Status: FAILED. 
Reason: Circular dependency between resources: [ClientsDeleteclientsPermissionTest, ClientsDeleteclientsPermissionProd, VehiclesGetVehiclesPermissionProd, Clients, ClientsGetclientsPermissionProd, VehiclesGetVehiclesPermissionTest, ServerlessRestApiDeployment9836ce6440, Vehicles, ClientsPutclientsPermissionProd, ClientsPostclientsPermissionTest, ServerlessRestApi, ClientsPutclientsPermissionTest, ClientsGetclientsPermissionTest, ClientsPostclientsPermissionProd, ServerlessRestApiProdStage]

**Comment by Tanbouz** [comment]
Tried explicitly defining API, it didn't work either :disappointed: 

Currently testing a workaround, it looks stupid but the template does deploy!

Two lambda functions, same code or different up to you!

* If it is an incoming request, the user already knows the API URL.
* Otherwise, if it is an outgoing request triggered by an AWS event for example, the outgoing function has the URL in the environment variable that you can send over to your "first time" user maybe via e-mail or a webhook that points back to the "incoming" lambda function.

```
  Incoming:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Incoming
      Description: Incoming
      Runtime: nodejs8.10
      Handler: index.handler
      MemorySize: 256
      Timeout: 30
      AutoPublishAlias: prod
      Events:
        Trigger:
          Type: Api
          Properties:
            Path: /
            Method: post

  Outgoing:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: Outgoing
      Description: Outgoing
      Runtime: nodejs8.10
      Handler: index.handler
      MemorySize: 256
      Timeout: 30
      AutoPublishAlias: prod
      Environment:
        Variables:
          URL: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"

```
