### ISSUE TITLE
Custom Domain Names?

### ISSUE THREAD

**Issue by frehner** [awslabs/serverless-application-model#40]
Is there a way in SAM to define your Custom Domain Name for an API Gateway endpoint, as well as the base path for it?

**Comment by sanathkr** [comment]
I am afraid not.. AFAIK CloudFormation hasn't supported APIGW custom domains yet. So SAM does not

**Comment by frehner** [comment]
@sanathkr thanks for the info. I'll just close this for the time being, then.

**Comment by lpalbou** [comment]
@frehner any update on this ?

**Comment by frehner** [comment]
I’m not working on this at all.  You will want to ask one of the maintainers

**Comment by lpalbou** [comment]
@frehner thanks, sorry for the confusion.

@sanathkr any update on the ability to define a custom domain name in SAM or CloudFormation ?

**Comment by timoschilling** [comment]
For me this works:
```yaml

AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: subsidy_request_mailer

Parameters:
  DomainName:
    Type: String
    Default: api.example.com
  HostedZoneName:
    Type: String
    Default: example.com

Resources:

  SendFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: send/
      Handler: app.lambda_handler
      Runtime: nodejs8.10
      Events:
        send:
          Type: Api
          Properties:
            Path: /send
            Method: get

  APIDomainName:
    Type: AWS::ApiGateway::DomainName
    Properties:
      CertificateArn: arn:aws:acm:us-east-1:...:certificate/...
      DomainName: !Ref DomainName

  APIBasePathMapping:
    Type: AWS::ApiGateway::BasePathMapping
    Properties:
      DomainName: !Ref APIDomainName
      RestApiId: !Ref ServerlessRestApi
      Stage: Prod

  APIDomain:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Ref HostedZoneName
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          DNSName: !GetAtt APIDomainName.DistributionDomainName
          HostedZoneId: Z2FDTNDATAQYW2 # static ID for CloudFront aliases
```
