### ISSUE TITLE
Cannot use Fn::Sub to reference RestApiId in Function Events definition

### ISSUE THREAD

**Issue by jlhood** [awslabs/serverless-application-model#400]
**Description:**

When defining a RestApi as an Event source for an AWS::Serverless::Function, you can specify a RestApiId. SAM translator supports specifying that id as a hardcoded value or using !Ref. However, it doesn't support using !Sub:

https://github.com/awslabs/serverless-application-model/blob/9ca6e340f051eaa670962303aff64f6cbeea181e/samtranslator/plugins/api/implicit_api_plugin.py#L158-L165

**Steps to reproduce the issue:**

Define a serverless function and serverless api in your template SAM template. Add an event mapping to the serverless function, but use !Sub to reference the api resource like this:

```
Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      ...
      Events:
        RestApi:
          Type: Api
          Properties:
            RestApiId: !Sub ${MyRestApi} # doesn't work when !Ref MyRestApi does
```

Then try to create a changeset with the template and SAM will error with:

**Observed result:**

ChangeSet ends up in FAILED state with message `RestApiId must be a valid reference to an 'AWS::Serverless::Api' resource`

**Expected result:**

ChangeSet should be created successfully
