### ISSUE TITLE
Internal transform failure when Lambda events and Custom Resource are included in the same template

### ISSUE THREAD

**Issue by ts33** [awslabs/serverless-application-model#401]
**Description:**

The following error is raised

`Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.`

when a SAM template includes both of the folllowing features:

- the `Events` Property of the `AWS::Serverless::Function` resource
- using `Fn::GetAtt:` on a custom resource to retrieve its value

If only one of the two above features are used in the template, no error occurs.

**Steps to reproduce the issue:**
1. Use the following SAM template:
```
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31


Parameters:

  PasswordReferenceKey:
    Type: String
    Default: db-password


Resources:

  PasswordLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  PasswordLambda:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: python3.6
      Role: !GetAtt PasswordLambdaRole.Arn
      Code:
        ZipFile: |
          import json
          import boto3
          from urllib.request import build_opener, HTTPHandler, Request

          def handler(event, context):
              response_body = json.dumps({
                  "Status": "SUCCESS",
                  "Reason": "See the details in CloudWatch Log Stream: " + context.log_stream_name,
                  "PhysicalResourceId": context.log_stream_name,
                  "StackId": event["StackId"],
                  "RequestId": event["RequestId"],
                  "LogicalResourceId": event["LogicalResourceId"],
                  "Data": {"db-password":"this-is-a-password"}
              })

              request = Request(event["ResponseURL"], data=str.encode(response_body))
              request.add_header("Content-Type", "")
              request.add_header("Content-Length", len(response_body))
              request.get_method = lambda: "PUT"

              opener = build_opener(HTTPHandler)
              response = opener.open(request)
              return response

  CustomResourcePasswordLambda:
    Type: Custom::CustomResourcePasswordLambda
    Properties:
      ServiceToken:
        Fn::GetAtt:
          - PasswordLambda
          - Arn
      ParameterNames:
        - Ref: PasswordReferenceKey

  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: testdb
      DBInstanceIdentifier: !Sub ${AWS::StackName}-rds
      DBInstanceClass: db.t2.micro
      MasterUsername: testuser
      MasterUserPassword: #this-is-a-password
        Fn::GetAtt:
          - CustomResourcePasswordLambda
          - Ref: PasswordReferenceKey
      StorageType: gp2
      AllocatedStorage: 20
      LicenseModel: postgresql-license
      Engine: postgres
      EngineVersion: 9.6

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: main.handler
      CodeUri: ../pybuild/
      Events:
        handlerPost:
          Type: Api
          Properties:
            Method: post
            Path: /path
```
| `PasswordLambda` and `PasswordLambdaRole` are actually created in another stack, but i'm combining it here for simplicity 

2. Create an S3 bucket 

3. Run the package command:
```
aws cloudformation package \
    --template ${template-file-name} \
    --s3-bucket ${bucket-name} \
    --output-template-file ${deployed-file-name}
```
4. Run the deploy command:
```
aws cloudformation deploy \
    --template-file ${deployed-file-name} \
    --stack-name ${stack-name} \
    --capabilities CAPABILITY_NAMED_IAM
```

**Observed result:**
```
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.
```

**Notes**
If the `Events` property is commented out, the template deploy works:
```
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      Handler: main.handler
      CodeUri: ../pybuild/
#      Events:
#        handlerPost:
#          Type: Api
#          Properties:
#            Method: post
#            Path: /path
```

If the `Fn::GetAtt:` command on the custom resource is commented out (and the password is replaced by a string or a parameter), the deploy also works:
```
  Database:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: testdb
      DBInstanceIdentifier: !Sub ${AWS::StackName}-rds
      DBInstanceClass: db.t2.micro
      MasterUsername: testuser
      MasterUserPassword: this-is-a-password
#        Fn::GetAtt:
#          - CustomResourcePasswordLambda
#          - Ref: PasswordReferenceKey
      StorageType: gp2
      AllocatedStorage: 20
      LicenseModel: postgresql-license
      Engine: postgres
      EngineVersion: 9.6
```
