### ISSUE TITLE
Feature: Kinesis Event Source Mapping - 'Enabled' property as per the console/cloudF.

### ISSUE THREAD

**Issue by kurtmaile** [awslabs/serverless-application-model#414]
Hi,

Can an 'enabled' property of the kinesis event source mapping be added inline with console and raw cloud formation:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-eventsourcemapping.html

At least based on the documentation for SAM this does not appear to be supported?

Thanks

**Comment by Nr18** [comment]
Looks like it's in there: https://github.com/awslabs/serverless-application-model/blob/0bb8ef767eff54640297e52115fd84b0e2b85165/samtranslator/model/lambda_.py#L57 

It's not mentioned in https://github.com/bedge/serverless-application-model/blob/f1d2a879b1bacc52c1f8a31c21f4a5eabb62bd51/versions/2016-10-31.md#kinesis but the following should work:

```
Type: Kinesis
Properties:
  Stream: arn:aws:kinesis:us-east-1:123456789012:stream/my-stream
  StartingPosition: TRIM_HORIZON
  BatchSize: 10
  Enabled: True
```
