### ISSUE TITLE
ElasticsearchHttpPostPolicy set but still receiving "not authorized to perform: es:ESHttpPost"

### ISSUE THREAD

**Issue by villasv** [awslabs/serverless-application-model#429]
**Description:**

I have a Lambda Function that I want to use to query an Amazon Elasticsearch Domain, but even after setting `ElasticsearchHttpPostPolicy`, using `search` will yield `"{\"Message\":\"User: anonymous is not authorized to perform: es:ESHttpPost\"}" }`

```
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Policies:
        - ElasticsearchHttpPostPolicy:
            DomainName: my-domain

  Search:
    Type: AWS::Elasticsearch::Domain
    Properties:
      DomainName: my-domain
      ElasticsearchVersion: 6.2
      ElasticsearchClusterConfig:
        InstanceCount: 1
        InstanceType: t2.small.elasticsearch
      EBSOptions:
        EBSEnabled: true
        Iops: 0
        VolumeSize: 10
        VolumeType: standard
```
