### ISSUE TITLE
Stream BatchSize property ignored in SAM template

### ISSUE THREAD

**Issue by vasylk** [awslabs/serverless-application-model#43]
Hi,
it seems that  BatchSize specified in SAM template for DynamoDB streams is ignored.

```
LambdaFunction:
      ......
      Events:
        DynamoDBNewItemEvent:
          Type: DynamoDB
          Properties:
            Stream:
              "Fn::GetAtt": [ "TableFileImport", "StreamArn" ]
            StartingPosition: "LATEST"
            BatchSize: 10
```

I have compared the original template with processed one in CloudFormation and there is no BatchSize properties in the latter.
The stream gets default BatchSize=100

The similar issue was posted on AWS Forum but for Kinesis Streams [See there](https://forums.aws.amazon.com/thread.jspa?messageID=757522&#757522)
