### ISSUE TITLE
Cannot use Intrinsic function when referencing parameter

### ISSUE THREAD

**Issue by setuk** [awslabs/serverless-application-model#434]
Template snippet:-

```
Transform: AWS::Serverless-2016-10-31

Globals:
    Function:
        Timeout: 3

Parameters:
  pAccountName:
    Description: Name of AWS Account
    Type: Number
    Default: 111111111111
  pRegion:
    Description: Region to deploy within
    Type: String
    MinLength: 9
    MaxLength: 14
    Default: us-east-1

Resources:
    SomeFunction:
        Type: AWS::Serverless::Function 
        Properties:
            CodeUri: build
            Handler: app.lambda_handler
            Runtime: python2.7
            DeadLetterQueue:
              Type: SQS
              # Cannot use a FIFO SQS queue for DLQ according to Cloud Formation
              TargetArn:
                !Sub 'arn:aws:sqs:${pRegion}:${pAccountName}:test_dlq'
```

Runs fine through sam local invoke
Validates fine
Packages ok
When i deploy i get:-

Waiting for changeset to be created..

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Invalid template resource property 'Fn::Sub'

Tried:-

TargetArn:
                !Sub 'arn:aws:sqs:${pRegion}:${pAccountName}:omp_dlq'

TargetArn: !Sub 'arn:aws:sqs:${pRegion}:${pAccountName}:omp_dlq'
TargetArn: !Sub "arn:aws:sqs:${pRegion}:${pAccountName}:omp_dlq"
TargetArn: 
     Fn:Sub: "arn:aws:sqs:${pRegion}:${pAccountName}:omp_dlq"
TargetArn: 
     Fn:Sub: 'arn:aws:sqs:${pRegion}:${pAccountName}:omp_dlq'

Am i doing something wrong or is it a bug?
