### ISSUE TITLE
MethodSettings - Not being deployed

### ISSUE THREAD

**Issue by kurtmaile** [awslabs/serverless-application-model#439]
Hi,

I have some method settings in my globals, however they are not translating through to the deployed API.  I suspect its my yaml, however its really hard to find examples with this in it?

In essence I want cloudwatch logs and metrics enabled for any stages resource methods (in my example I use POST and also /xxx but just want it across the board).  How do I define this in the method settings?  And is below wrong?  The package and deploy does not complain so structurally its correct, maybe just my config?  Anyhow - cant find a full example anywhere.  Thanks!

```
Globals:
  Api:
    # Some properties of AWS::Serverless::Api
    # Also works with Implicit APIs
    Name: aName
    EndpointConfiguration: REGIONAL
    MethodSettings:
      -
        CacheDataEncrypted: false
        CachingEnabled: false
        DataTraceEnabled: true
        HttpMethod: POST
        LoggingLevel: INFO
        MetricsEnabled: true
        ResourcePath: /xxxx
        ThrottlingBurstLimit: 1000
        ThrottlingRateLimit: 2000
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
```

**Comment by Tanoemon** [comment]
Same here. Only prod's MethodSettings is updated.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: my api
Globals:
  Api:
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "'Content-Type, Authorization'"
      AllowOrigin: "'*'"
      MaxAge: "'600'" 
    MethodSettings:
      - ResourcePath: "/*"
        HttpMethod: "*"
        CacheDataEncrypted: false
        CachingEnabled: false
        DataTraceEnabled: true
        LoggingLevel: INFO
        MetricsEnabled: true
        ThrottlingBurstLimit: 50
        ThrottlingRateLimit: 100

Resources:
  GetDealers:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: get-something
      CodeUri: bin/xxxx/list/list.zip
      Role: arn:aws:iam::111111111111:role/lambda_basic_execution
      Handler: list
      Runtime: go1.x
      VpcConfig:
        SecurityGroupIds:
          - sg-ixxxxxxxx
        SubnetIds:
          - subnet-ixxxxxxxxxx
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /getsomething
            Method: get
  GetDealersLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /aws/lambda/GetSomething
      RetentionInDays: 14
      ```
