### ISSUE TITLE
[Question] CodeStarWorker-test-CloudFormation/AWSCloudFormation is not authorized to perform: iam:CreateRole on resource:

### ISSUE THREAD

**Issue by Jun711** [awslabs/serverless-application-model#448]
**Description:**
One of my 'AWS::Serverless::Function' has a policies property like following (without a role property)
```
Type: 'AWS::Serverless::Function'
    Properties:
      Handler: helloWorld.handler
      Runtime: python3.6
      MemorySize: 128
      Description: 'helloWorld'
      FunctionName: helloWorld
      Policies:
        - Statement:
            - Effect: "Allow"
              Action: 
                - "polly:SynthesizeSpeech"
              Resource:
                - "Fn::Sub": "arn:aws:polly:${AWS::Region}:${AWS::AccountId}:lexicon/*"
```

**Observed result:**
CodePipeline ExecuteChangeSet failed with this error: 
API: iam:CreateRole User: arn:aws:sts::AccountId:assumed-role/CodeStarWorker-test-CloudFormation/AWSCloudFormation is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::AccountId:role/awscodestar-test-lambda-helloWorldRole-V5QUHYDCDRBA

So, I went on to add iam:CreateRole policy to the AWSCloudFormation role and I retried. 
In IAM Policy Simulator, that AWSCloudFormation role was able to perform IAM CreateRole action. 
However, I got the same error. 

**Expected result:**
Expected a new role to be created with the Polly policy.
