### ISSUE TITLE
Package with AWS AppSync schema definition leads to deploy failure

### ISSUE THREAD

**Issue by jkahn117** [awslabs/serverless-application-model#461]
**Description:**

When defining an AWS AppSync GraphQL schema in CloudFormation, there is an option to embed the definition (`Definition` property) in the template or load from S3 (`DefinitionS3Location` property). Embedding the definition in a SAM template leads to inclusion of `DefinitionS3Location` in the packaged template, an error condition for the CloudFormation engine.

**Steps to reproduce the issue:**
1. Create SAM template with an AppSync GraphQL schema and serverless function as in the example below.
2. Package.
3. Note that resulting template (e.g. packaged.yaml) includes both a `Definition` and `DefinitionS3Location` property in the `AWS::AppSync::GraphQLSchema` resource.
4. Deploy.
5. CloudFormation will error: "Cannot set both the Definition and the DefinitionS3Location."

**Observed result:**

CloudFormation error: "Cannot set both the Definition and the DefinitionS3Location."

**Expected result:**

Successful deployment.

**Example: template.yaml**

``` yaml
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Resources:
  MyAppSyncApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: API_KEY
      Name: my-api

  SessionManagerSchema:
    Type: AWS::AppSync::GraphQLSchema
    Description: Session Manager GraphQL schema
    Properties:
      ApiId: !GetAtt MyAppSyncApi.ApiId
      Definition: |
        type User {
          username: String!
        }
       type Query {
         allUsers(nextToken: String): [User]
       }
      schema {
        query: Query
      }

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
```

**Comment by maoosi** [comment]
I am having the exact same issue.

**Comment by jkahn117** [comment]
For now, I've modified my template as follows and added a little bit of automation:

``` yaml
SessionManagerSchema:
    Type: AWS::AppSync::GraphQLSchema
    Description: Session Manager GraphQL schema
    Properties:
      ApiId: !GetAtt MyAppSyncApi.ApiId
      DefinitionS3Location: s3://mybucket/schema.graphql
```

Using a Makefile (though you could do this in any number of ways), I added the following to my "deploy" task to upload the schema.graphql file to my S3 location:

``` bash
aws s3 cp schema.graphql s3://mybucket/schema.graphql

aws cloudformation deploy ...
```

A side benefit of this approach is that the my GraphQL schema is managed independently of the rest of my stack.
