### ISSUE TITLE
Add Support for AuthorizationType to API

### ISSUE THREAD

**Issue by jkahn117** [awslabs/serverless-application-model#49]
API Endpoints often require authorization permissions, e.g. only IAM users. Ideally, AWS::Serverless::Api would also support AuthorizationType available for API Gateway.

For example, using IAM user:

```
Events:
  Type: Api
  Properties:
    Path: /secrets
    Method: get
    AuthorizationType: AWS_IAM
```

Or a custom authorizer:

```
Events:
  Type: Api
  Properties:
    Path: /secrets
    Method: get
    AuthorizationType: CUSTOM
    Authorizer: <ARN_CUSTOM_AUTHORIZER>
```

Realize this may be challenging in referencing the custom authorizer function if not a function defined within the template though.

**Comment by collinforrester** [comment]
If I'm understanding you correctly, have you tried defining what you're trying to get in the console and exporting the swagger file?  I've found that my SAM templates support Cognito Authorization definitions by exporting an existing API built in the console and just using it as a starting point.

**Comment by jkahn117** [comment]
Agreed, it is possible to make this work with a Swagger file, but that feels like an unnecessary step (export Swagger, modify, upload + manage separately) for something reasonably simple to configure as part of the API definition.

**Comment by sanathkr** [comment]
Thanks for the request. This is a good feature to have.

**Comment by mparaz** [comment]
It looks like using Swagger stopped working. This was previously working:

```
securityDefinitions:
  authorizerFunc:
    type: "apiKey"
    name: "Authorisation"
    in: "header"
    x-amazon-apigateway-authtype: "custom"
    x-amazon-apigateway-authorizer:
      authorizerUri: "arn:aws:apigateway:ap-southeast-2:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-southeast-2:00000000:function:${stageVariables.AuthorizerFunctionName}/invocations"
      authorizerResultTtlInSeconds: 300
      type: "token"
```

But now I get:
```
Errors found during import: Unable to create authorizer 'authorizerFunc': Authorizers only support Lambda function invocations.
```

What is the correct syntax now?
