### ISSUE TITLE
Invalid event types are not validated

### ISSUE THREAD

**Issue by mikedeck** [awslabs/serverless-application-model#493]
**Description:**

If you specify an unknown event type on a function no error is raised during the transform.

**Steps to reproduce the issue:**
1. Deploy the following template:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    SampleFunction:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: nodejs8.10
        Events:
            ExampleEvent:
                Type: AnInvalidType
                Properties: {}
```

**Observed result:**
The stack is created successfully just without any event triggers on the function.

**Expected result:**
An error should be raised and the stack creation should fail noting that `AnInvalidType` is not a valid event type.
