### ISSUE TITLE
Swagger variables are not interpreted in json template

### ISSUE THREAD

**Issue by I159** [awslabs/serverless-application-model#497]
**Description:**

I have a SAM yaml template and a custom API Gateway definition in a json Swagger file.

```
MyApi:                                                   
    Type: AWS::Serverless::Api                                     
    Properties:                                                    
        DefinitionUri: apigateway.json
        StageName: !Ref Stage                                      
        Variables:                                                 
            FnName: !Ref MyFn                              
            Stage: !Ref Stage                                      
            Region: !Ref Region                 
```                   
In the Swagger file I declare my API and expect to have some custom definitions like resources uri:

```
x-amazon-apigateway-integration: {                                  
    httpMethod: POST,                                               
    passthroughBehavior: when_no_match,
    type: aws_proxy,                                                
    uri: arn:aws:apigateway:${stageVariables.Region}:lambda:path/2015-03-31/functions/arn:${MyFn.Arn}/invocation
}
```
But all the variables are not interpreted when I deploy it with `aws cloudformation deploy` and kept as plain text with all `${..}` syntax. Is it something wrong with the syntax? Should it event work like that in external json files?

**Comment by gitorrin** [comment]
How are you referencing the swagger file?
I'm using the DefinitionBody property of the AWS::Serverless::Api, and it works. 

Example:
`MyLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: FunctionA
      Handler: handlerConfig
      Runtime: dotnetcore2.0
      CodeUri: 
        Bucket: !Ref BucketA
        Key: 'Folder1/deploy.zip'      
      MemorySize: 256
      Timeout: 59
      Role: !Ref myRole
      
MyAPI:
    Type: "AWS::Serverless::Api"
    Properties:
      Name: MessageAPI      
      StageName: latest
      DefinitionBody: 
        Fn::Transform:
          Name: AWS::Include
          Parameters:            
            Location: 
              Fn::Sub: 's3://myBucket/MyAPI/swagger.yaml'`

And here's a snippet from the swagger file:
` x-amazon-apigateway-integration:
        uri: 
          Fn::Sub: 'arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${MyLambda.Arn}/invocations'`

**Comment by brettstack** [comment]
> But all the variables are not interpreted when I deploy it with aws cloudformation deploy and kept as plain text with all ${..} syntax

Could you clarify?

**Comment by keetonian** [comment]
CloudFormation parameters are not resolved if you are using [DefinitionUri](https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-definitionuri).

If you want to have your swagger/openapi spec in a separate file, we recommend using the `AWS::Include` transform inside of `DefinitionBody`.  

Example:
```yaml
  DefinitionBody:
    Fn::Transform:
      Name: AWS::Include
      Parameters:
        Location: s3://bucket/swagger.yaml # Put what you have in DefinitionUri into this property.
```
