### ISSUE TITLE
Question: multiple environments, different properties

### ISSUE THREAD

**Issue by collinforrester** [awslabs/serverless-application-model#50]
So I've seen the stage variables and environment variables but I'm not sure if thats what I need.

What's the correct way to execute the same template in each environment but swap out things like proxy urls, AuthorizationType user pool IDs, etc?

Currently I just use two completely different sam.yaml files that define different stage variables & point to separate stages.  Both YAML files point to the same API gateway swagger definition file.  Is there a better way?

**Comment by sanathkr** [comment]
You should use [CloudFormation parameters](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html) to customize your inputs. You will have one SAM file but customize each stack by specifying different parameters

**Comment by collinforrester** [comment]
So to give a little more insight to what I have so far so you can point me in the right direction:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Parameters: 
  InternalAPIUrl: 
    Type: String
    Description: Internal API URL
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: api.swagger.yaml
```

And inside of api.swagger.yaml:
```
# removed
x-amazon-apigateway-integration:
    responses:
        default:
        statusCode: "200"
    uri: !Ref InternalAPIUrl
    requestParameters:
        integration.request.path.proxy: "method.request.path.proxy"
    passthroughBehavior: "when_no_match"
    httpMethod: "ANY"
    cacheNamespace: "aabbcc"
    cacheKeyParameters:
    - "method.request.path.proxy"
    type: "http_proxy"
# removed
```

When I executed the `deploy` command (after standard `package` command), I did `aws cloudformation deploy --parameter-overrides InternalAPIUrl=http://domain.com/{proxy} --template-file ./service.cfn.yaml --stack-name api-gateway --capabilities CAPABILITY_IAM --region us-east-1`.

Where am I going wrong with this?

The error I got was related to an invalid URI for the proxy endpoint I'm guessing because I didn't get the variable resolved properly.

**Comment by sanathkr** [comment]
You cannot have CloudFormation !Ref directly inside swagger. You need to use StageVariables like this:

https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/template.yaml#L11. You will `!Ref InternalAPIUrl` on the `Variable`

https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/api_swagger_cors/swagger.yaml#L23. Instead of Lambda function ARN, you will simply use refer your to your stage variable

**Comment by collinforrester** [comment]
Ok thanks for the quick response.  I think I'm getting close, but it still seems like I'm missing a piece.  Here are the two things I tried:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: api.swagger.yaml
      StageName: dev
      Variables:
        InternalAPIUrl: !Ref InternalAPIUrl
```

In my swagger file:
```
# ...
uri: ${stageVariables.InternalAPIUrl}/{proxy}
# ...
```

When I tried to deploy it I got this error:
```
aws cloudformation deploy --parameter-overrides InternalAPIUrl=http://domain.com --template-file ./service.cfn.yaml --stack-name api-gateway-main  --capabilities CAPABILITY_IAM --region us-east-1

Waiting for changeset to be created..

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Circular dependency between resources: [ApiGatewayApidevStage]
```

So I tried to simplify it some and remove the cloudformation parameter part and just use the stage variables first... I got a little further.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: api.swagger.yaml
      StageName: dev
      Variables:
        InternalAPIUrl: http://domain.com
```

with the same swagger file got the changeset created but failed during the deploy process with this:
```
Errors found during import: Unable to put integration on 'ANY' for resource at path '/{proxy+}': Invalid HTTP endpoint encoding detected for URI
```

I tried doing the same via the console, adding `${stageVariables.InternalAPIUrl}` for the proxy HTTP endpoint and got `invalid uri` error in the UI.
