### ISSUE TITLE
How To Use Boolean Values?

### ISSUE THREAD

**Issue by JimTheMan** [awslabs/serverless-application-model#501]
Hello, I am using CodePipeline to build and deploy a lambda function (scaffolded out with codestar). I have a template.yml file where I define some parameters like this:
```
Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  Environment:
    Type: String
    Description: The environment in which the lambda function is exectuting (ALPHA, PROD, ...)
```

I would like to be able to add this one for EncryptionEnabled which can be true or false.

```
Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members
  Environment:
    Type: String
    Description: The environment in which the lambda function is exectuting (ALPHA, PROD, ...)
  EncryptionEnabled:
    Type: Boolean
    Description: a boolean value indicating whether request and response are encrypted.
```

However, in the deploy step of my codepipeline I get the error, 

> Action Execution Failed: Parameter [EncryptionEnabled] is invalid

I also tried boolean with a lowercase b but same error. Are boolean values not supported here? Am I just using the wrong value for the parameter's Type?

thanks.
