### ISSUE TITLE
Disable/Prevent CloudWatch Alarms when creating a new DynamoDB table with SAM

### ISSUE THREAD

**Issue by bluepeter** [awslabs/serverless-application-model#507]
I have several non-scaling DynamoDB tables created via CloudFormation. Each table auto-creates CloudWatch Alarms (and more for each GSI). In PROD this is okay, but in DEV this adds up in terms of cost. For example, for action table with a GSI I get the following alarms created:

```
action-ReadCapacityUnitsLimit-BasicAlarm
action-WriteCapacityUnitsLimit-BasicAlarm
action-siteId-lastCaptured-index-ReadCapacityUnitsLimit-BasicAlarm
action-siteId-lastCaptured-index-WriteCapacityUnitsLimit-BasicAlarm
```

My CF template is quite simple for each table. For example:

```
tableuser:
  Type: 'AWS::DynamoDB::Table'
  DependsOn: tablepage
  Properties:
    TableName: user
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: S
    KeySchema:
      - AttributeName: id
        KeyType: HASH
    PointInTimeRecoverySpecification:
      PointInTimeRecoveryEnabled: true
    ProvisionedThroughput:
      ReadCapacityUnits:
        Ref: 5
      WriteCapacityUnits:
        Ref: 5
```

How can I disable CloudWatch Alarms for CloudFormation-created DynamoDB tables? Of course I would prefer to do this via CloudFormation templates itself, but since I am not specifying their creation, I am not sure if this is possible?

**Comment by brettstack** [comment]
As far as I'm aware, these aren't created by SAM. Does DynamoDB create these implicitly?

**Comment by bluepeter** [comment]
Yep, they are created implicitly... which is fine, I suppose. Is there a way in SAM/CF to explicitly disable them? It's frustrating to have this massive (and costly) alerting infrastructure setup for dev environments, for example.

**Comment by jfuss** [comment]
@bluepeter I just deployed this template
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
    MyTable:
        Type: AWS::Serverless::SimpleTable
        Properties:
            TableName: my-table
            PrimaryKey:
                Name: id
                Type: String
            ProvisionedThroughput:
                ReadCapacityUnits: 5
                WriteCapacityUnits: 5
```

And see no alarms being created. Are you sure alarms aren't defined somewhere? 

I even deployed your table above (minus the dependson attribute), with no alarms created.
