### ISSUE TITLE
Code pipline failed due to: No integration defined for method

### ISSUE THREAD

**Issue by avizaviz** [awslabs/serverless-application-model#54]
Hi,
My Code Pipline fails. inthe execution phase with the following error:

> Execute
> AWS CloudFormation
>  Failed 18 hours ago Details

> Action execution failed
> Failed to execute change set. Current stack status: UPDATE_ROLLBACK_COMPLETE. Reason: No reason was provided.
> Link to execution details

Clicking on details shifts to cloud formation stack with the following errors:

> 	13:58:37 UTC+0200	UPDATE_ROLLBACK_IN_PROGRESS	AWS::CloudFormation::Stack	ProdStack2	The following resource(s) failed to create: [apiDeployment].
> 13:58:35 UTC+0200	CREATE_FAILED	AWS::ApiGateway::Deployment	apiDeployment	No integration defined for method
> 13:58:34 UTC+0200	CREATE_IN_PROGRESS	AWS::ApiGateway::Deployment	apiDeployment	
 
Pay attention running the following command locally succeeded:
aws cloudformation deploy --template-file c:\StackData\lambda\outputTemplate.yml --stack-name ProdStack --capabilities CAPABILITY_IAM `

My Template file is:
```
AWSTemplateFormatVersion: '2010-09-09'
Description: Outputs the time
Resources:
  f1:
    Properties:
      CodeUri: s3://lambdabiot/6135bb77878b4c847aee2b609cef4cc2
      Events:
        MyApi:
          Properties:
            Method: GET
            Path: /f1
          Type: Api
      Handler: index.handler
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
  f2:
    Properties:
      CodeUri: s3://lambdabiot/86bd36e690b8f6a2ee59e9375ed7b983
      Events:
        MyApi:
          Properties:
            Method: GET
            Path: /f2
          Type: Api
      Handler: index.handler
      Runtime: nodejs4.3
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
```
