### ISSUE TITLE
Best way to pass binary content through ApiGateway unmodified

### ISSUE THREAD

**Issue by 0xdevalias** [awslabs/serverless-application-model#566]
I searched the existing issues for [`ContentHandling `](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apitgateway-method-integration.html#cfn-apigateway-method-integration-contenthandling) and most that contain it (as part of their example code) seem to be setting at as part of a fully custom OpenAPI/Swagger spec.

I was wondering if there is a canonical way for setting this on the generated 'implicit ApiGateway', or if I should be resorting to manually creating my entire spec for this kind of behaviour?

**Comment by 0xdevalias** [comment]
Reading a little deeper.. the base64 encoding may actually be occurring at the `awslabs/aws-lambda-go-api` proxy level:
* https://github.com/awslabs/aws-lambda-go-api-proxy/blob/master/core/response.go#L81-L86
* https://github.com/awslabs/aws-lambda-go-api-proxy/blob/master/gorillamux/adapter.go#L31-L36

So I'm not sure whether this is even something that would be configurable/fixable in SAM.

**Comment by 0xdevalias** [comment]
Potentially related issues:
* https://github.com/awslabs/aws-sam-cli/issues/653
* https://github.com/awslabs/serverless-application-model/issues/553
* https://github.com/awslabs/serverless-application-model/issues/248

**Comment by 0xdevalias** [comment]
Decided to try implementing this myself using the more manual version of ``. By inspecting the end CloudFormation json, and converting/working backwards into SAM yaml, I came up with this:

```yaml
  FooTestApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: FooTestApi
      StageName: Prod
      DefinitionBody:
        swagger: '2.0'
        info:
          version: '1.0'
          title: !Ref AWS::StackName
        paths:
          "/{proxy+}":
            x-amazon-apigateway-any-method:
              x-amazon-apigateway-integration:
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${AgentProxy.Arn}/invocations
                httpMethod: POST
                contentHandling: CONVERT_TO_BINARY
              responses: {}
```

I also created this permission manually (though I expect if I set the `RestApiId` property on my function it may have been generated for me):

```
  AgentProxyCatchAllPermissionProdFooTestApi:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref AgentProxy
      SourceArn: !Sub
        - arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${__ApiId__}/${__Stage__}/*/*
        - __Stage__: Prod
          __ApiId__: !Ref FooTestApi
      Principal: apigateway.amazonaws.com
      Action: lambda:invokeFunction
```

**Comment by 0xdevalias** [comment]
So, to resolve this properly, it seems that: 
* Need to solve why updates aren't properly setting the binary types (https://github.com/awslabs/aws-sam-cli/issues/653)
* Need to implement a 'SAM-native' way of configuring `"contentHandling" : "CONVERT_TO_BINARY"` as described above for the implicit api

**Comment by brettstack** [comment]
Sorry about this missing feature. Closing in favor of #553.

**Comment by brettstack** [comment]
PR for fixing BinaryMediaTypes getting lost in update #954

**Comment by keetonian** [comment]
To get around needing `contentHandling: "CONVERT_TO_BINARY"`, you can set

```yaml
BinaryMediaTypes:
  - "*~1*"
```

on your API definition. However, I think this will have the side effect of converting all responses to binary (unless `CONVERT_TO_TEXT` is specified in `contentHandling`), which won't work for most cases. I posted in #553 a proposal to support `contentHandling` in Event definitions, will go forward with that proposal.

**Comment by thanhlq** [comment]
Hi everybody,

So does AWS Api gateway support to receive a binary payload? then in api gateway can help to convert that binary to base64 for me?

Thanks very much for any tips...

**Comment by praneetap** [comment]
@thanhlq In lambda proxy integration data is always converted to base64 if the `content-type` is marked as binary on the incoming request. On the response, the JSON proxy response can contain a field that indicates whether or not the payload `isBase64Encoded: true`. The only thing that affects the handling of data to a lambda proxy are the [`BinaryMediaTypes`](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessapi) and the content of the JSON response.

**Comment by brahma712** [comment]
I have a lambda function that is integrated to API Gateway with a Lambda Proxy integration. Basically the lambda function is grabbing a zip file from S3 and returning it as payload by auto downloading the file when the endpoint is hit in a browser. The contentType I sent is application/octet-stream. However, when the zip file is downloaded, it turns into a cpgz. I am not sure how to resolve this issue. My API gateway was created via the console for proof of concept and not via the cfn template (though eventually we will deploy it through our cfn template) hence I dont know how to pass in the contentHandling parameter. Do you have any thoughts on how I can solve this issue?

**Comment by bohana** [comment]
Hi all

>> The only thing that affects the handling of data to a lambda proxy are the BinaryMediaTypes and the content of the JSON response.

I added the binary media types in my `template.yaml`:

```yaml
        Properties:
            StageName: dev
            OpenApiVersion: '3.0.0'
            BinaryMediaTypes:
                    - application~1octet-stream
                    - application~1zip
                    - application~1gzip
```

And after deployment I do see them in the console. (I used sam `1.20.0`)

My application also sets `isBase64Encoded` to `True` at the Lambda layer, but the gateway still does not convert the payload from base64 to binary.

This should be happening right? What am I missing?
