### ISSUE TITLE
VpcConfig invalid when referencing other resources

### ISSUE THREAD

**Issue by jkahn117** [awslabs/serverless-application-model#57]
The following returns the error message `Resource with id [SampleFunction] is invalid. Type of property 'VpcConfig' is invalid.` though appears to be valid.

```
VpcConfig:
  SecurityGroupIds:
    - !Ref FunctionSecurityGroup
  SubnetIds:
    - !ImportValue "aroundme-private-subnet"
```

When I modify the block to reference the actual values (as follows), template works as expected, thus this seems to be a transform issue.

```
VpcConfig:
  SecurityGroupIds:
    - "sg-ABC123"
  SubnetIds:
    - "subnet-ABC123"
```
