### ISSUE TITLE
Transforms on S3Location are not applied for AppSync Resolver resource

### ISSUE THREAD

**Issue by wnkz** [awslabs/serverless-application-model#572]
**Description:**

Transforms on `RequestMappingTemplateS3Location` and `ResponseMappingTemplateS3Location` are not applied to `AWS::AppSync::Resolver`.

**Steps to reproduce the issue:**
1. Using the following template:

```
  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      Name: !Sub ${ProjectName}-api
      AuthenticationType: AMAZON_COGNITO_USER_POOLS
      UserPoolConfig:
        UserPoolId: !Ref UserPoolId
        AwsRegion: !Ref AWS::Region
        DefaultAction: DENY

  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      DefinitionS3Location: ../source/app/amplify/backend/api/app/build/schema.graphql

  ShopDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      Name: ShopTable
      ApiId: !GetAtt GraphQLApi.ApiId
      Type: AMAZON_DYNAMODB
      ServiceRoleArn: !GetAtt DynamoDBAccessRole.Arn
      DynamoDBConfig:
        TableName: !Ref ShopTableName
        AwsRegion:
          Fn::Select: [ 3, !Split [":", !Ref ShopTableArn ] ]

  GetShopResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId: !GetAtt GraphQLApi.ApiId
      DataSourceName: !GetAtt ShopDataSource.Name
      FieldName: getShop
      TypeName: Query
      RequestMappingTemplateS3Location: ../source/app/amplify/backend/api/app/build/resolvers/Query.getShop.request
      ResponseMappingTemplateS3Location: ../source/app/amplify/backend/api/app/build/resolvers/Query.getShop.response

```
2. Run `aws cloudformation package`
3. Download templates

**Observed result:**

```
  [...]

  GraphQLSchema:
    Properties:
      ApiId:
        Fn::GetAtt:
        - GraphQLApi
        - ApiId
      DefinitionS3Location: s3://my-bucket/sam/c916b9d22758889fad10c39474de7d13
    Type: AWS::AppSync::GraphQLSchema

  GetShopResolver:
    Properties:
      ApiId:
        Fn::GetAtt:
        - GraphQLApi
        - ApiId
      DataSourceName:
        Fn::GetAtt:
        - ShopDataSource
        - Name
      FieldName: getShop
      RequestMappingTemplateS3Location: ../source/app/amplify/backend/api/app/build/resolvers/Query.getShop.request
      ResponseMappingTemplateS3Location: ../source/app/amplify/backend/api/app/build/resolvers/Query.getShop.response
      TypeName: Query
    Type: AWS::AppSync::Resolver
```

**Expected result:**

```
  [...]

  GraphQLSchema:
    Properties:
      ApiId:
        Fn::GetAtt:
        - GraphQLApi
        - ApiId
      DefinitionS3Location: s3://my-bucket/sam/c916b9d22758889fad10c39474de7d13
    Type: AWS::AppSync::GraphQLSchema

  GetShopResolver:
    Properties:
      ApiId:
        Fn::GetAtt:
        - GraphQLApi
        - ApiId
      DataSourceName:
        Fn::GetAtt:
        - ShopDataSource
        - Name
      FieldName: getShop
      RequestMappingTemplateS3Location: s3://my-bucket/sam/aabbcc
      ResponseMappingTemplateS3Location: s3://my-bucket/sam/ddeeff
      TypeName: Query
    Type: AWS::AppSync::Resolver
```
