### ISSUE TITLE
Add x-ray enable flag to API gateway

### ISSUE THREAD

**Issue by mburket** [awslabs/serverless-application-model#581]
**Description:**

Hi, a recent announcement of x-ray support for API gateway --https://aws.amazon.com/blogs/aws/apigateway-xray/  

Will that be added to SAM soon?

**Comment by nzoschke** [comment]
As a temporary workaround, I built a custom resource to toggle the setting:

```
  ApiGatewayStage:
    Properties:
      RestApiId: !Ref ServerlessRestApi
      ServiceToken: !GetAtt CustomResourceFunction.Arn
      Stage: !Ref ServerlessRestApiProdStage
      TracingEnabled: true
    Type: Custom::ApiGatewayStage
```
> From https://github.com/nzoschke/gofaas/blob/master/template.yml#L197-L203

With the Lambda implementation handler here:

https://github.com/nzoschke/gofaas/blob/master/cfresource.go

**Comment by brettstack** [comment]
This would be a great first PR if anyone wanted to give it a shot.

**Comment by jlhood** [comment]
@terodox Thanks for asking. We're not able to share internal dates so the best I can say is "soon".

**Comment by alanwill** [comment]
Weird, the [spec](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md) mentions `TracingEnabled` is included in `AWS::Serverless::Api` however it fails when deploying:

```
UPDATE_FAILED

Embedded stack arn:aws:cloudformation:us-east-1:xxxxxx:stack/xxxxxx was not successfully updated. Currently in UPDATE_ROLLBACK_IN_PROGRESS with reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [apigatewaySlack] is invalid. property TracingEnabled not defined for resource of type AWS::Serverless::Api
```

And the CFN reference is:

```
    apigatewaySlack:
        Type: AWS::Serverless::Api
        Properties:
            StageName: !Ref stage
            DefinitionUri: ../../sam/api/swagger.yaml
            TracingEnabled: true
            AccessLogSetting:
                DestinationArn: cwlaccesslogs.Arn
            MethodSettings: 
                DataTraceEnabled: true
                HttpMethod: '*'
                LoggingLevel: INFO
                MetricsEnabled: true
                ResourcePath: /
```
