### ISSUE TITLE
api gateway lambda permissions

### ISSUE THREAD

**Issue by samallisonds** [awslabs/serverless-application-model#584]
I have been experiencing issues with the lambda execute permission not being in place when deploying a stack, or new function, for the first time. I've been resolving it manually within the API Gateway console.

I've finally had a closer look... the stack does create a permission, but it is with the suffix 'Stage'. In my case I am supplying a specific StageName to the AWS::Serverless::Api resource. Actually to be more accurate I have "StageName: !Ref Stage", where Stage is a parameter to the template. Judging by the line linked below this can't be resolved, and rather unhelpfully 'Stage' is used instead. Perhaps this should be 'AllStages'?

https://github.com/awslabs/serverless-application-model/blob/a3a6d5211ed06fd77bdeb649d7277d0cc7843f56/samtranslator/model/eventsources/push.py#L367

**Comment by brettstack** [comment]
I was too quick to jump to this conclusion. I'll need to investigate further.

**Comment by samallisonds** [comment]
Great - thanks for looking!

**Comment by samallisonds** [comment]
I thought that I'd worked around this by removing my "!Ref Stage" instances and just hardcoding my stage name. However today I discovered this wasn't as successful as I'd thought.

After much playing around creating and destroying stacks the only thing I found that worked reliably was creating my own permission with a dependency on the stage

```
  FooFunctionPostResourcePermissionDoubleCheck:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref FooFunction.Alias
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${RestApi}/${RestApibarStage}/GET/foo*

```

I seemed to need to add the `*` on the end to make it a distinct permission from the one that SAM creates itself? Guessing there.... but it didn't work without it

The permission that SAM creates only has a dependency on the restapi, and it just hardcodes the value for the stage.

For reference in this stack I have two functions connected to an API with a swagger definition. I have various other resources. The permissions problem consistently effects the same function, while the other is always OK. In the CloudFormation events log the failing permission is created first.

**Comment by brettstack** [comment]
Glad you worked around it, but I'm not sure why the permission SAM generates for you didn't work. It's hard to root cause your actual problem without more info on the template.

**Comment by patrickgreenwell** [comment]
I ran into this issue today when I was working through things, it looks to be some issue with the `AutoPublishAlias: aliasName` I removed that from my SAM Template and the permissions came back on my Lambda.  

Funny thing is though that when I Viewed the Overview of the stack in the lambda console when I had the AutoPublishAlias set that the permissions were there, but not included as sub-object of the lambda or the version.
![cfbadlambdapermissions](https://user-images.githubusercontent.com/5296581/47312248-d0be9200-d609-11e8-9b86-af1c43fa5d6f.PNG)

Contrast this with after removing the Alias:

![cfgoodlambdapermissions](https://user-images.githubusercontent.com/5296581/47312384-34e15600-d60a-11e8-975b-dc33270ad720.PNG)

My Swagger file didn't contain the alias in it's x-amazon-apigateway-integration object
```yaml
x-amazon-apigateway-integration:
        type: aws_proxy
        httpMethod: POST
        uri: 
          Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations"
```
This might just be a further symptom of how the transform and permissions application gets executed, and various other things might cause the same issue. 

I'll have to try adding the alias name to the integration in swagger and see if that fixes it, though I suspect since the alias is pointer to a version it might have the same issue.
