### ISSUE TITLE
SAM package fails silently when resource type is not valid

### ISSUE THREAD

**Issue by Geranimo** [awslabs/serverless-application-model#592]
**Description:**
sam package didn't validate on invalid resource types defined in the template and failed silently while packaging, for example the Template below has a misspelled `Type : AWS::Serverless::Fuction`

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  helloworld:
    Type: AWS::Serverless::Fuction
    Properties:
      Handler: helloworld.handler
      Runtime: nodejs6.10
      Events:
        GreetingsResource:
          Type: Api
          Properties:
            Path: /greetings
            Method: get
```
$ sam package --template-file deployment.yaml --output-template-file serverless-output.yaml --s3-bucket sam-experiment 

2018-09-24 15:26:17 package command is called

Successfully packaged artifacts and wrote output template to file serverless-output.yaml.
Execute the following command to deploy the packaged template
aws cloudformation deploy --template-file /Documents/serverless-output.yaml --stack-name <YOUR STACK NAME>
2018-09-24 15:26:18 package command successful

**Observed result:**
```
generated serverless-output.yaml

AWSTemplateFormatVersion: '2010-09-09'
Resources:
  helloworld:
    Properties:
      Events:
        GreetingsResource:
          Properties:
            Method: get
            Path: /greetings
          Type: Api
      Handler: helloworld.handler
      Runtime: nodejs6.10
    Type: AWS::Serverless::Fuction
Transform: AWS::Serverless-2016-10-31
```
**Expected result:**
some sort of validation on invalid resource type would be nice to have
