### ISSUE TITLE
Not possible to have CodeUri as a parameter

### ISSUE THREAD

**Issue by Pelto** [awslabs/serverless-application-model#61]
For some reason, it doesn't seem possible to specify `CodeUri` as a parameter.

I have a template that specifies a function:

```yaml
AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A hello world application.
Parameters:
  CodeUri:
    Type: String
    Description: The link to the code to use.
Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      CodeUri: !Ref CodeUri
```

When I try to execute the template using `aws cloudformation deploy` the following error appears:

```bash
aws cloudformation deploy --stack-name example --template-file lambda-example.sam.yaml --parameter-overrides CodeUri=s3://$BUCKET_NAME/example.zip

Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [HelloWorldFunction] is invalid. 'CodeUri' is not a valid S3 Uri of the form "s3://bucket/key" with optional versionId query parameter.
```

I tried running it with the `--debug` flag attached and it looks like the correct S3 Uri is added. Below is an extract from the debug output:

```xml
    <Parameters>
      <member>
        <ParameterKey>CodeUri</ParameterKey>
        <ParameterValue>s3://johannes-lambda-test/example.zip</ParameterValue>
      </member>
    </Parameters>
```

The example code that have been used can be found at https://github.com/Pelto/aws-serverless-2016-10-31-bug
