### ISSUE TITLE
AlexaSkillEvent only add permission but not hook up

### ISSUE THREAD

**Issue by Chris-Liao** [awslabs/serverless-application-model#613]
**Description:**

I'm trying to add Alexa Skill Kit Trigger/Event to Lambda function, by doing the below
`      Events:
        AlexaSkillEvent:
          Type: AlexaSkill`
in SAM template.
I can see in CloudFormation, there is AWS::Lambda::Permission added. But there's no trigger added to lambda. 

Is it because I didn't provide skill ID?

**Steps to reproduce the issue:**
1. Add AlexaSkillEvent under function's properties.

**Observed result:**
Lambda got deployed without Alexa Skill KIt trigger.

**Expected result:**
Lambda got deployed with Alexa Skill KIt trigger.

**Comment by keetonian** [comment]
Adding this event should include the following permission after the transform has been run:
```
"<FunctionName>AlexaSkillEventPermission": {
      "Type": "AWS::Lambda::Permission", 
      "Properties": {
        "Action": "lambda:invokeFunction", 
        "FunctionName": {
          "Ref": "<FunctionName>"
        }, 
        "Principal": "alexa-appkit.amazon.com"
      }
    }, 
```
It looks like it gives alexa skills (principal: alexa-appkit.amazon.com) permission to call this lambda function. Are you saying that this permission is not added?

**Comment by ScriptAutomate** [comment]
PR #363 seems to be trying to achieve exactly what this is asking for, except for Alexa Smart Home Skills specifically.

Do Alexa Smart Home Skills use a different API? Or could it be a two-birds one-stone situation?

**Comment by ScriptAutomate** [comment]
I found a way to do it via normal CFN resources. Further research and testing shows that the following works in the `template.yaml` with `sam-cli`, without needing to resort to a post-configuration modification via `aws-cli`:

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Alexa App Hello World Lambda Endpoint

Mappings:
    Variables:
        AlexaSkillKit:
            Id: amzn1.ask.skill.xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

Globals:
    Function:
        Timeout: 3

Resources:

    HelloWorldFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: hello_world/
            Handler: app.lambda_handler
            Runtime: python3.6

    HelloWorldFunctionAskPermission:
        Type: AWS::Lambda::Permission
        DependsOn: HelloWorldFunction
        Properties:
            Action: lambda:InvokeFunction
            EventSourceToken: !FindInMap
                - Variables
                - AlexaSkillKit
                - Id
            FunctionName: !GetAtt HelloWorldFunction.Arn
            Principal: alexa-appkit.amazon.com

Outputs:

    HelloWorldFunction:
        Description: "Alexa Hello World Lambda Function ARN"
        Value: !GetAtt HelloWorldFunction.Arn

    HelloWorldFunctionIamRole:
        Description: "Implicit IAM Role created for Alexa Hello World function"
        Value: !GetAtt HelloWorldFunctionRole.Arn

    HelloWorldFunctionAlexaSkillKitId:
        Description: "Alexa Skill Permitted Lambda Invokation Permissions"
        Value: !FindInMap
            - Variables
            - AlexaSkillKit
            - Id
```

With this being the case, I suppose there isn't a need to create additional functionality to support this in the Serverless transform?
