### ISSUE TITLE
Lambda@Edge example only works on us-east-1 region

### ISSUE THREAD

**Issue by yvele** [awslabs/serverless-application-model#635]
I'm unable to use [the Lambda@Edge example](https://github.com/awslabs/serverless-application-model/blob/master/examples/2016-10-31/lambda_edge/template.yaml) with CloudFront being set on an other region than `us-east-1`.

Because a Lambda@Edge function must be in region `us-east-1`:

> The function must be in region 'us-east-1'. ARN: arn:aws:lambda:eu-west-1:xxxxxx:function:OriginRequestLambdaFunct-xxxxxx:1 (Service: AmazonCloudFront; Status Code: 400; Error Code: InvalidLambdaFunctionAssociation; Request ID: xxxxxx)

Can you please add a Lambda@Edge example workaround, or recommendations than allow CloudFront and Lambda@Edge to be set up on different regions?

Maybe 2 separate Cloudformation template?

This issue is related to #323 and #565

PS: [Other people on Twitter](https://twitter.com/prestomation/status/971256051516485632) also expresses this needs

![image](https://user-images.githubusercontent.com/4225430/47348871-affe4700-d6b2-11e8-9e83-7c6b96fd0f9c.png)

**Comment by timoschilling** [comment]
I'm planning to solve that Issue via an CloundFormation custom resource which deployes that lambda to the other region, but it would be nice if SAM Transforme will so that out of the box for us.

**Comment by yvele** [comment]
@timoschilling do you have some code tho share? I'm interested

**Comment by yvele** [comment]
@timoschilling how do you make you custom resource work with something like `CodeUri` that should detect code change? 🤔  `CodeUri` is processed by AWS SAM right? 

Should we try to directly use [`AWS::CloudFormation::Macro`](https://aws.amazon.com/blogs/aws/cloudformation-macros/)? (or maybe hacking with [StackSets](https://aws.amazon.com/blogs/aws/use-cloudformation-stacksets-to-provision-resources-across-multiple-aws-accounts-and-regions/)?)

**Comment by timoschilling** [comment]
Sorry at the moment I only have the concept, will share it if its done.

**Comment by yvele** [comment]
Ok.. you can share the detailed concept if you want 😉 

I was think about the following concept (quite hacky but well...):

In a single `cloudformation.yml`

```yml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref LambdaFunctionStandard.Version

  # Unused Lambda function only to get `CodeUri` working
  LambdaFunctionCodeProxy:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      AutoPublishAlias: live

  # Custom resource to "copy" the Lambda in the standard region (us-east-1)
  LambdaFunctionStandard:
    Type: Custom::LambdaEdgeCopy
    Properties:
      ServiceToken: !ImportValue CustomRessourceLambdaEdgeCopy
      Parameters:
        Version: !Ref LambdaFunctionCodeProxy.Version
        Region: us-east-1
```


Something awesome and more simple could be

```yml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        DefaultCacheBehavior:
          LambdaFunctionAssociations:
            - EventType: origin-request
              LambdaFunctionARN: !Ref LambdaFunction.Version

  LambdaFunction:
    Type: Custom::LambdaEdgeCopy
    Properties:
      ServiceToken: !ImportValue CustomRessourceLambdaEdgeCopy
      Parameters:
        CodeUri: src # Unfortunately `CodeUri` is not processed by SAM for Custom resources
```

Unfortunately `CodeUri` is not processed by SAM for Custom resources
