### ISSUE TITLE
Template error: IAM role stack-Lambda-XXXXX doesn't exist

### ISSUE THREAD

**Issue by yvele** [awslabs/serverless-application-model#641]
I have a very strange error when deploying basic Lambda function using SAM.

The strange thing is that it worked this morning and the exact same code fails this afternoon 🤔 

> Template error: IAM role stack-LambdaFunction-XXXXX doesn't exist

My Lambda is quite basic, I'm in region `eu-east-1`

```yml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Resources:
  LambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler     : main.handle
      Runtime     : nodejs8.10
      MemorySize  : 2048
      CodeUri     : ./dist
```

This is strange because we can see that the role has been successfully created just before:

![image](https://user-images.githubusercontent.com/4225430/47515181-6ebc9180-d882-11e8-941b-ac04e028900d.png)

**Comment by yvele** [comment]
Looks like with the exact same code if we keep trying to deploy it succeeded once.. 🤔

**Comment by thomasklinger1234** [comment]
Same here. 

```
18:26:22 UTC+0200 | CREATE_FAILED | AWS::Lambda::Function | MyFunction | Template error: IAM role bcm-api-MyFunction-LM95D3GKBBWL doesn't exist
-- | -- | -- | -- | --
```

Code:

```
---
AWSTemplateFormatVersion: 2010-09-09

Transform: "AWS::Serverless-2016-10-31"

Description: |
  https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md

Globals:
  Function:
    Runtime: python3.6
    MemorySize: 128
    Timeout: 10
    CodeUri: .

Resources:
  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.run
      Description: ""
      Policies:
        - AWSLambdaExecute
        - 
          Version: 2012-10-17
          Statement:
            - 
              Effect: Allow
              Action:
                - "*"
              Resource:
                - "*"
```
