### ISSUE TITLE
Authorizers: Support AuthorizationScopes

### ISSUE THREAD

**Issue by keetonian** [awslabs/serverless-application-model#652]
**Description:**

This was brought up in Slack:

> Starting to work on a PoC using the new authorizer features in SAM and already notice one huge shortcoming I didn't think about.
> `AuthorizationScopes` - this would have been really powerful to include so I could define required scopes for authenticating tokens at the API level instead of inside the code.

This is also necessary for using `access_tokens`.

Docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-authorizationscopes

SAM should support `AuthorizationScopes`.

**Comment by brysontyrrell** [comment]
This was my thread in the channel. My proposal would look something like this:

```
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn
              OAuthScopes:
                - scope1
                - scope2

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: lambda.handler
      MemorySize: 1024
      Runtime: nodejs8.10
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: GET
            Auth:
              Authorizer: MyCognitoAuthorizer
              OAuthScopes:
                - scope3
```

This is a swagger doc from one of my templates to show what it looks like with scopes defined:

```
ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      EndpointConfiguration: EDGE

      DefinitionBody:
        swagger: 2.0
        info:
          title: !Ref AWS::StackName
        securityDefinitions:
          CognitoAuth:
            type: apiKey
            name: Authorization
            in: header
            x-amazon-apigateway-authtype: cognito_user_pools
            x-amazon-apigateway-authorizer:
              type: cognito_user_pools
              providerARNs:
                - !Ref CognitoUserPoolArn

        paths:
          "/messages":
            post:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SendMessage.Arn}/invocations
              responses: {}
              security:
                - CognitoAuth:
                  - "rds-worker/send_message"

          "/errors":
            get:
              x-amazon-apigateway-integration:
                httpMethod: post
                type: aws_proxy
                uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${Errors.Arn}/invocations
              responses: {}
              security:
                - CognitoAuth:
                  - "rds-worker/read_errors
```

**Comment by mau-fyayc** [comment]
+1

**Comment by uokitomer** [comment]
Is there any plan to include this feature in the near future?

**Comment by eterjoost** [comment]
I can look into implementing this. The transformation to swagger is simple enough, although I'm not sure if there are other steps that need to be implemented. 
In any case, what would be the expected behavior when only a scope is specified? Without an authorizer like this:
```
MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn
              OAuthScopes:
                - scope1
                - scope2

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: lambda.handler
      MemorySize: 1024
      Runtime: nodejs8.10
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: GET
            Auth:
              OAuthScopes:
                - scope3
```

**Comment by klmz** [comment]
I can look into implementing this. The transformation to swagger is simple enough, although I'm not sure if there are other steps that need to be implemented. 
In any case, what would be the expected behavior when only a scope is specified? Without an authorizer like this:
```
MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn
              OAuthScopes:
                - scope1
                - scope2

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: lambda.handler
      MemorySize: 1024
      Runtime: nodejs8.10
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: GET
            Auth:
              OAuthScopes:
                - scope3
```

I would propose choosing the default authorizer in this case.

**Comment by klmz** [comment]
I also want to propose calling it ```AuthorizationScopes``` instead of ```OAuthScopes``` since it is more consistent with the naming of the [AWS::ApiGateway::Method](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-authorizationscopes) in normal CloudFormation.
Or is it better to make the naming different to ensure there is no mix up for inexperienced users?

**Comment by keetonian** [comment]
@klmz Keeping the naming the same should be fine.  I think the transformation into swagger + some supporting tests are all that are needed for this feature, correct me if I'm wrong.

**Comment by klmz** [comment]
Yes, that is what I figured. I got most of it working. Is there any documentation on what is expected in terms of tests? I saw some end-to-end test that will be needed, any thing else?

**Comment by keetonian** [comment]
@klmz we don't have any docs on what is expected for tests, but I would recommend some end-to-end tests like you suggested, as well as some tests for the new swagger that is generated in https://github.com/awslabs/serverless-application-model/blob/develop/tests/swagger/test_swagger.py.

**Comment by brettstack** [comment]
> I would propose choosing the default authorizer in this case.

This is correct. Looking forward to the PR!

**Comment by MohammedAlSafwan** [comment]
How long would it be until this get pushed in with the next release !? +1

**Comment by praneetap** [comment]
@MohammedAlSafwan We are still working on reviewing the PR, once that's reviewed and merged in we will assign a release tag on it.

**Comment by MohammedAlSafwan** [comment]
@praneetap ... thank you, I just noticed that it had [conflict](https://github.com/awslabs/serverless-application-model/pull/917)... I really hope that could be done soon

**Comment by Michael1d** [comment]
Looking forward to having this functionality!

**Comment by candyflossuk** [comment]
+1 on looking forward to this functionality - having to work round this was a pain today. Any ETA on the release?

**Comment by keetonian** [comment]
I've been looking into this (both fixing merge conflicts in the code and the actual spec).

Using scopes in method authorization for Cognito is possible as per [APIGW Cognito Docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-enable-cognito-user-pool.html), and is also consistent with the example shared by @brysontyrrell 

This issue is for scopes on methods using Cognito auth, and does not address adding generic OAuth 2.0 support yet.

Some existing questions:

1. With the current proposal (included below for reference), would scopes `scope1` and `scope2` be applied to all methods using `MyCognitoAuthorizer`, meaning that the `root` event would have `scope1`, `scope2`, and `scope3` as scopes?

```yaml
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: MyCognitoAuthorizer
        Authorizers:
          MyCognitoAuthorizer:
            UserPoolArn: !Ref CognitoUserPoolArn
              OAuthScopes:
                - scope1
                - scope2

  MyFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: lambda.handler
      MemorySize: 1024
      Runtime: nodejs8.10
      Events:
        Root:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: GET
            Auth:
              Authorizer: MyCognitoAuthorizer
              OAuthScopes:
                - scope3
```

**Comment by David-V2** [comment]
@keetonian : logically, yes :)
I can't wait to use this !

**Comment by brysontyrrell** [comment]
@keetonian @David-V2 That was the intent of my original example, but it might be more appropriate to have that be a part of `Globals`:

```yaml
Globals:
  Function:
    Auth:
      OAuthScopes:
        - scope-1
        - scope-2
```

Note that `Auth` is not yet listed as a supported value in `Globals`.
