### ISSUE TITLE
execute-changeset fails with new SAM auth model

### ISSUE THREAD

**Issue by mbklaene** [awslabs/serverless-application-model#658]
There seems to be an issue with executing a changeset when defining authorizers with SAM. I am using Codepipeline with codebuild and then creating a CF change set.  

This template works when I use the previous swagger definition for my existing template (commented out below), using exported values from another template for the authorizer function/role. 

When I use the new syntax, I get an error for AWS::LAMBDA::PERMISSION : "Unable to parse HTTP response content (Service: AWSLambda; Status Code: 403; Error Code: null; Request ID:...."

Underlying issue seems to be similar to one described here: https://forums.aws.amazon.com/thread.jspa?threadID=217143

Once, I did not rollback the stack, then simply reselected my existing Lambda function from the API Gateway UI and saved and it worked.  But this kills automation, unless I can find a workaround.

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
    Message:
        Description: "Message from service."
        Type: "String"
Resources:
    GetMessage:
        Type: AWS::Serverless::Function
        Properties:
            Handler: index.handler
            Runtime: python3.6
            CodeUri: ./
            Environment:
                Variables:
                    MESSAGE: !Ref Message
            Events:
              GetResource:
                Type: Api
                Properties:
                  Path: /message
                  Method: get
                  RestApiId:
                      Ref: MyApi

    MyApi:
      Type: AWS::Serverless::Api
      Properties:
        StageName: Prod
        Auth:
          DefaultAuthorizer: MyAuthorizer
          Authorizers: 
            MyAuthorizer:
              FunctionArn:
                Fn::Sub:
                - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CustomAuthorizer}/invocations
                - CustomAuthorizer: !ImportValue custom-authorizer
              FunctionInvokeRole: !ImportValue 'gateway-custom-authorizer-role'

    # MyApi:
    #   Type: AWS::Serverless::Api
    #   Properties:
    #       StageName: prod
    #       DefinitionBody:
    #           swagger: 2.0
    #           info:
    #             title:
    #               Ref: AWS::StackName
    #             description: My API that uses custom authorizer
    #             version: 1.0.0
    #           securityDefinitions:
    #             CustomAuthorizer:
    #               type: apiKey
    #               name: Authorization
    #               in: header
    #               x-amazon-apigateway-authtype: custom
    #               x-amazon-apigateway-authorizer:
    #                 type: token
    #                 authorizerUri:
    #                   Fn::Sub:
    #                   - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${CustomAuthorizer}/invocations
    #                   - CustomAuthorizer: !ImportValue custom-authorizer
    #                 authorizerCredentials:
    #                   !ImportValue 'gateway-custom-authorizer-role'
    #                 authorizerResultTtlInSeconds: 60
    #           paths:
    #             "/message":
    #               get:
    #                 x-amazon-apigateway-integration:
    #                   httpMethod: POST
    #                   type: aws_proxy
    #                   uri:
    #                     Fn::Sub:
    #                     - arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetMessage.Arn}/invocations
    #                     - CustomAuthorizer: !ImportValue custom-authorizer
    #                 authorizerCredentials:
    #                   !ImportValue 'gateway-custom-authorizer-role'
    #                 security:
    #                   - CustomAuthorizer: []
    #                 responses: {}
```
