### ISSUE TITLE
Orphan Stage

### ISSUE THREAD

**Issue by marjanSterjev** [awslabs/serverless-application-model#67]
The following API definition:
```
GreetingsApi:
    Type: AWS::Serverless::Api
    DependsOn:
      - GreetingsFunction
    Properties:
      DefinitionUri: ./greetings-swagger.yaml
      StageName: prod
      Variables:
        GreetingsFunctionName: !Ref GreetingsFunction

```
Creates two stages: **prod** and **Stage**.

Why do we have **Stage** created? Only **prod** is expected.
