### ISSUE TITLE
Internal transform error

### ISSUE THREAD

**Issue by red8888** [awslabs/serverless-application-model#672]
I use a Mapping to transform dev and prod settings. This works for single values but SAM is choking on trying to transform the Events config, whats wrong with my config?:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'

Parameters:
  env:
    Description: Config map for transforming template with dev or prod values
    Type: String
    Default: dev

# Template uses !FindInMap along with env parameter to reference dev or prod values defined here
Mappings:
  ConfigMap:
    dev:
      awsAccount: 'dev'
      configFile: 'sam_configs/dev_lambda_config.yaml'
      cloudwatchEvents: !Ref "AWS::NoValue"
    prod:
      awsAccount: 'prod'
      configFile: 'sam_configs/prod_lambda_config.yaml'
      cloudwatchEvents:
        Schedule1:
          Type: Schedule
          Properties:
            Schedule: rate(3 minutes)

Resources:
  myfunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      CodeUri: ../obj
      Handler: lambda_function.lambda_handler
      Runtime: python3.6
      MemorySize: 128
      Timeout: 30
      # Cloudwatch events defined here are automatically created as part of the stack
      Events:
        !FindInMap
            - ConfigMap
            - !Ref env
            - cloudwatchEvents

      Environment:
        Variables:
          config_file: !FindInMap
            - ConfigMap
            - !Ref env
            - configFile

      Tags:
        account: !FindInMap
          - ConfigMap
          - !Ref env
          - awsAccount
        blah: derp
        team: myteam

```
