### ISSUE TITLE
DependsOn

### ISSUE THREAD

**Issue by ktruckenmiller** [awslabs/serverless-application-model#68]
I may just be having trouble, but it would be great to have "DependsOn" working with serverless for the more complicated deploys.

For instance, if I wanted to create a LambdaRole and Lambda I could say

```
Transform:  AWS::Serverless-2016-10-31
Resources:
Lambda:
  DependsOn: LambdaRole
  Type: AWS::Serverless::Function
    Role: !Ref LambdaRole
LambdaRole:
  Type: AWS::IAM::Role
```

Right now I'm getting a "Circular Dependency" issue. I'm sure it's supported but I wanted to check with you to make sure I'm not doing anything wrong.

**Comment by sanathkr** [comment]
Agreed. DependsOn is a good feature to have. But I don't see how this template would create a circular dependency issue. Can you provide the full template?

**Comment by jrstarke** [comment]
I take it that `AWS::Serverless::Function` does not support `DependsOn` At this time?  In my CloudFormation stack, I have a section like 

```
  LambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "sts:AssumeRole"
            Principal:
              Service:
                - "lambda.amazonaws.com"
  LambdaRolePolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "LambdaRolePolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Action:
              - "logs:CreateLogGroup"
              - "logs:CreateLogStream"
              - "logs:PutLogEvents"
            Resource:
              - "*"
      Roles:
        -
          Ref: "LambdaRole"
  Lambda:
    Type: "AWS::Serverless::Function"
    Properties:
      Role:
        !GetAtt LambdaRole.Arn
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      Timeout: 15
      CodeUri: "s3://..."
    DependsOn: LambdaRolePolicy
```

When I run my CloudFormation stack, the `Lambda` starts creating immediately after the `LambdaRole` finishes creation, and before the `LambdaRolePolicy` event starts it's creation, thus, I get errors like 

```
Error Message: User: arn:aws:sts::***:assumed-role/LambdaRole-***/Lambda-*** is not authorized to perform: logs:CreateLogGroup on resource: arn:aws:logs:us-west-2:***:log-group:/aws/lambda/Lambda-***:log-stream:```

Is there a work around to make the lambda function wait until the policy has been attached to the role?

**Comment by heitorlessa** [comment]
Alternatively, you could make use of Managed Policy and not have an extra resource in here:

```yaml
    LambdaRole:
      Type: "AWS::IAM::Role"
      Properties:
        # Managed Policy include required Lambda Execution Role permissions
        ManagedPolicyArns:
            - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Sid: "AllowLambdaServiceToAssumeRole"
              Effect: "Allow"
              Action:
                - "sts:AssumeRole"
              Principal:
                Service:
                  - "lambda.amazonaws.com"

    Lambda:
      Type: "AWS::Serverless::Function"
      Properties:
        Role: !GetAtt LambdaRole.Arn
        Handler: lambda_function.lambda_handler
        Runtime: python2.7
        Timeout: 15
        CodeUri: "s3://..."
```

Removed ``DependsOn`` in ``Serverless::Function`` as it's not supported and merged Policy and Role by making use of ``AWSLambdaBasicExecutionRole`` that does exactly the same that IAM policy above.

That should allow Lambda to assume just fine and add additional policies right after if you need to. Give it a try and let us know here :)

Hope it helps

**Comment by jrstarke** [comment]
Thanks @heitorlessa, I also discovered an alternative method.

The following is also equivalent to what I put in originally:

```
  Lambda:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      Timeout: 15
      CodeUri: "s3://..."
```

This works because the AWS::Serverless::Function actually generates a number of CloudFormation resources. In the case above, it will generate a role for the function, because one is not explicitly assigned, and it will attach the `AWSLambdaBasicExecutionRole` to it.

Further, for anyone else facing a similar issue, if you need to attach custom permissions, you can do so using:

```
  Lambda:
    Type: "AWS::Serverless::Function"
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python2.7
      Timeout: 15
      CodeUri: "s3://..."
      Policies:
        -
          Version: "2012-10-17"
          Statement:
            -
              Effect: "Allow"
              Action:
                - "s3:GetObject"
              Resource:
                - "arn:aws:s3:::<some_bucket>/*"
```

This will create a custom role, with the `AWSLambdaBasicExecutionRole` Policy attached, and also attach inline policies. In the case above, this will create an inline policy that grants the lambda access to get objects from `<some_bucket>`.

Internally, it appears that `AWS::Serverless::Function` seems to use `AWS::IAM::Role to generate the role for the function, and passes in your defined list of `Policies` to the roles `Policies` document, and waits for it to complete before creating the lambda function that uses it.

**Comment by ktruckenmiller** [comment]
What would be a good way of attaching multiple managed policies to this?

**Comment by heitorlessa** [comment]
@jrstarke  that's right, ``AWS::Serverless::Function`` does create implicit resources including an IAM Role (and Lambda Permissions in case you define an API). Best way to capture these resources as documentation gets updated is to simply [describe resources that Cloudformation created](http://docs.aws.amazon.com/cli/latest/reference/cloudformation/describe-stack-resources.html). 

My suggestion on having an IAM role within the template is that it allows you the flexibility to add Managed Policy (multiples) **and** Inline policies at the same time since it's a cloudformation resource and not a SAM translation, of which also helps in maintainability for those reading and using that SAM template - In fairness, it's a judgement call as both get the job done :)

@ktruckenmiller Following the example above you can add multiple managed policies as follows - Simply include the full ARN whether that be customer or AWS managed policy:

```yaml

    ServiceXLambdaRole:
      Type: "AWS::IAM::Role"
      Properties:
        # Managed Policy include required Lambda Execution Role permissions
        ManagedPolicyArns:
            - "arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"
            - "arn---policy2"
            - "arn---policy3"
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            -
              Sid: "AllowLambdaServiceToAssumeRole"
              Effect: "Allow"
              Action:
                - "sts:AssumeRole"
              Principal:
                Service:
                  - "lambda.amazonaws.com"
```

**Comment by sanathkr** [comment]
`AWS::Serverless::Function` can take multiple [Managed Policy names](https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction). Like this:

```
Type: AWS::Serverless::Function
Properties:
    Runtime: nodejs4.3
    Policies:
        - AWSS3FullAccess
        - AWSDynamoDBFullAccess
```
 SAM will automatically add LambdaBasicExecution role to the permissions.
 
Above will work for AWS Managed Policies. If you are attaching your own Custom Managed policy, you need to follow @heitorlessa's example above. Create your own IAM role and attach the role to SAM function

**Comment by ranman** [comment]
To get the conversation back on track: without DependsOn support there is no real way to build bootstrapping actions in SAM. This needs to be implemented and should be marked as a bug not a question.

**Comment by sanathkr** [comment]
Yup. Supporting DependsOn is a feature request. We will get it prioritized

**Comment by armasegCanal** [comment]
Hi @jrstarke, You may also create a cloudformation stack with the Role and export it to use it in another Cloudformation stack where you will create your Lambda Function 

First cloudformation stack
```yaml
Outputs:
  FunctionRole:
    Description: Role to be used.
    Value:
      !GetAtt LambdaRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-Role"
```

In the second cloudformation stack 
```yaml
Parameters:
  LambdaRoleStackName:
    Description: Name of an active CloudFormation stack that contains the Role, that will be used in this stack.
    Type: String
    MinLength: 1
    MaxLength: 255
    AllowedPattern: ^[a-zA-Z][-a-zA-Z0-9]*$
    Default: SampleCrossStack

Resources:
  LambdaFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Role:
        Fn::ImportValue: !Sub "${LambdaRoleStackName}-Role"

```

However, I prefer your workaround ;)
