### ISSUE TITLE
Request: AWS::Serverless::Function example that includes a custom IAM Policy

### ISSUE THREAD

**Issue by jolexa** [awslabs/serverless-application-model#69]
Hello,

I cannot seem to create a functional example that does, in fact, create a lambda function with a custom IAM policy. This is a request to provide an example that works.

Non Working Example:
```
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  TweetCollectionFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: test.handler
      Runtime: python2.7
      CodeUri: ./deployment.zip
      MemorySize: 128
      Timeout: 3
      Policies:
      - Effect: Allow
        Action: s3:GetObject
        Resource: '*'
```

This results in a lambda function that *only* includes 'AWSLambdaBasicExecutionRole'. I would expect it to also include s3:GetObject access on * resources. Right?

**Comment by vikrambhatt** [comment]
You need to specify the policy this this format:
```
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Resources: 
  TweetCollectionFunction: 
    Type: "AWS::Serverless::Function"
    Properties: 
      Handler: test.handler
      Runtime: python2.7
      CodeUri: ./deployment.zip
      MemorySize: 128
      Timeout: 3
      Policies: 
        - 
          Statement: 
              Effect: Allow
              Action: "s3:GetObject"
              Resource: "*"

```
Policies should be a policy document object and it should have a 'Statement'. 
Reference: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-policy.html#d0e81659
