### ISSUE TITLE
AWS::Lambda::EventSourceMapping is created disabled by default?

### ISSUE THREAD

**Issue by pshvets** [awslabs/serverless-application-model#702]
Noticed today that after redeployment all my queues are not able to trigger lambdas due to disabled  Lambda function triggers.

my YAML hasn't been changed and looks like:

```yaml
Events:
    SQSEvent:
        Type: SQS
        Properties:
            Queue: !GetAtt MessageQueue.Arn
            BatchSize: 10
```

Is it somehow related to #669 and #690 ?
