### ISSUE TITLE
SAM template create OPTIONS method in api gateway

### ISSUE THREAD

**Issue by Nik1990** [awslabs/serverless-application-model#725]
Hi, why with the following yaml file cloudfomation create a method relative to my desidered api (/hello)?
I noticed that by removing 'globals' section  (the CORS options) the OPTIONS method is no longer crated but the cors is now ncessary for me. 

``` AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Api:
    # enable CORS; to make more specific, change the origin wildcard
    # to a particular domain name, e.g. "'www.example.com'"
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"
      
Parameters:
  CognitoUserPoolName:
    Type: String
    Default: AppUsers

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:xxx:userpool/xxx

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        HelloGfmiApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref MyApi
 ```

Following a screen of ip gateway status

[image](https://pasteboard.co/HSjx62n.png)

Any suggest?

Thanks

**Comment by chrisoverzero** [comment]
CORS operates via specially crafted `OPTIONS` requests. That mock endpoint is what produces the CORS responses. 

I'm afraid there's nothing to suggest. If your API requires CORS (and it probably does), it needs a way to respond to the `OPTIONS` verb.

**Comment by jlhood** [comment]
This is expected behavior for CORS support.

**Comment by pokusak** [comment]
Testing with template from first comment SAM/Cloudformation creates GET and OPTIONS which is perfectly OK. 
I am curious if it is OK that both methods are guarded by Cognito authorizer?
This way it would be required from browser to send headers as if it was sending real GET which a) not happening b) probably also not according to w3c specs.
Or does it mean that I have to force browser (via generated API Gateway SDK) to send header or at least to use withCredentials?

**Comment by leantorres73** [comment]
Same issue here. The OPTION method is secured by Cognito also and I'm pretty sure it shouldn't be that way. 
@pokusak  Did you find a way of fixing it?

**Comment by jimmy-ml** [comment]
@leantorres73 @Nik1990 
I solved it like this:
```
Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Auth:
        # DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: arn:aws:cognito-idp:xxx:userpool/xxx

  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs8.10
      Events:
        HelloGfmiApi:
          Type: Api
          Properties:
            Path: /hello
            Method: GET
            RestApiId: !Ref MyApi
            Auth:
                Authorizer: NediCognitoAuthorizer
```

**Comment by leantorres73** [comment]
@jimmy-ml there is a new feature  in SAM that you can allow OPTIONS to don't ask for Authorization! It's a flag called AddDefaultAuthorizerToCorsPreflight, you can check it and you avoid to specify for each method the Auth
  
`    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: userPoolARN
      AddDefaultAuthorizerToCorsPreflight: False
`

**Comment by dilippatidar123** [comment]
AddDefaultAuthorizerToCorsPreflight : False is not working. 
Is there any additional configuration we have to do it ?
Please suggest.
Thanks

**Comment by leantorres73** [comment]
@dilippatidar123  Are you using the latest version? This is a new feature, it was release one month ago in version v1.13.0

**Comment by dilippatidar123** [comment]
@leantorres73 Thanks for response. 
We are not using CLI to deploy this, Adding AddDefaultAuthorizerToCorsPreflight: False 
in template.yml and deploying using cloudformation.
Please suggest.

**Comment by leantorres73** [comment]
@dilippatidar123  So my question is, it fails in the deploy saying the property does not exist or everything is created correctly but CORS is not working?

**Comment by dilippatidar123** [comment]
Its not giving any property or deployment error. But its still taking the default authorizer for options method.
Currently we are using following code for option method.

```
> Events: 
>         ProxyApiRoot1: 
>           Type: Api 
>           Properties: 
>             RestApiId: !Ref ApiGatewayApi 
>             Path: /{proxy+} 
>             Method: ANY
>         ProxyApiRoot2:
>            Type: Api
>            Properties:
>              RestApiId: !Ref ApiGatewayApi
>              Path: /{proxy+}
>              Method: OPTIONS
>              Auth:
>                Authorizer: NONE
> Auth:
>         DefaultAuthorizer: Authorizer
>         Authorizers:
>           Authorizer:
>             FunctionPayloadType: REQUEST
>             FunctionArn: 'Authorizer ann'
>             FunctionInvokeRole: "Role arn'
>             Identity:
>               Headers:
>                  - Cookie
>               ReauthorizeEvery: 300 # seconds
```

 
 So after adding AddDefaultAuthorizerToCorsPreflight: False flag. So I believe after this flag we don't need to add explicit code in events to add options method and auth.

Please correct me if I am wrong.

Thanks

**Comment by leantorres73** [comment]
That's correct, you don't need to include ProxyApiRoot2 at all. If you're using SAM, you will have something like this:

```
 Api:
    Cors:
      AllowHeaders: "'Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization'" 
      AllowOrigin: "'*'"
    Auth:
      DefaultAuthorizer: CognitoAuthorizer
      Authorizers:
        CognitoAuthorizer:
          UserPoolArn: yourUserPool
      AddDefaultAuthorizerToCorsPreflight: False
```

**Comment by dilippatidar123** [comment]
@leantorres73 Its working.
Thanks for the help!

**Comment by dilippatidar123** [comment]
@leantorres73 Thanks Its working.

**Comment by bravodavid56** [comment]
@leantorres73 Somehow this syntax of enabling CORS fixed my issue, thank you.

**Comment by ronytesler** [comment]
@leantorres73 
I have this configuration and still the OPTIONS calls have the authorizer set:
"AWSTemplateFormatVersion": "2010-09-09",
  "Transform": "AWS::Serverless-2016-10-31",
  "Resources": {
  "ApiGatewayApi":
  {
    "Type": "AWS::Serverless::Api",
    "Properties": {
      "StageName": "Prod",
      "Name" : "MainGateway",
      "Cors": {
        "AllowMethods": "'POST, GET, PUT, DELETE'",
        "AllowHeaders": "'access-control-allow-headers,access-control-allow-methods,access-control-allow-origin,authorization,content-type'",
        "AllowOrigin": "'*'",
        "MaxAge": "'1'"
      },
      "Auth" : {
      **"AddDefaultAuthorizerToCorsPreflight": false,**
      "ApiKeyRequired": false,
      "Authorizers": {
      "MyTokenAuth": {
      "FunctionArn": {
            "Fn::GetAtt": [
                "UserAuthorizerGeneral",
                "Arn"
            ]
        },
      "AuthType": "TOKEN"
    }
      },
      "DefaultAuthorizer": "MyTokenAuth"
      }
    }
  },
"GetFollowingOrUnfollowingPosts": {
      "Type": "AWS::Serverless::Function",
      "Properties": {
        "Handler": "AWSServerlessFameOh::AWSServerlessFameOh.Functions::GetFollowingOrUnfollowingPostsAsync",
        "Runtime": "dotnetcore3.1",
        "CodeUri": "",
        "MemorySize": 256,
        "Timeout": 30,
        "Role": null,
        "Policies": [
          "AWSLambdaFullAccess"
        ],
        "Events": {
          "PutResource": {
            "Type": "Api",
            "Properties": {
              "Path": "/GetFollowingOrUnfollowingPosts",
              "Method": "GET",
              "RestApiId" : {"Ref": "ApiGatewayApi"}
            }
          }
        }
      }
    },

**Comment by jagsrajput21** [comment]
@leantorres73 Will it works if in Case of AccessTokenAuthorizer? Because In my case it's not working. 

```
Api:
        Cors:
            AllowHeaders: "'Access-Control-Allow-Headers, Origin,Accept, X-Requested-With, Content-Type, Access-Control-Request-Method, Access-Control-Request-Headers, Authorization'" 
            AllowOrigin: "'*'"
        Auth:
            DefaultAuthorizer: AuthenticationTokenAuthorizer
            Authorizers:
                AuthenticationTokenAuthorizer:
                    FunctionArn: !GetAtt AUTHFunction.Arn
            AddDefaultAuthorizerToCorsPreflight: False


```
