### ISSUE TITLE
Changing an Api Event does not redeploy the API resource

### ISSUE THREAD

**Issue by jolexa** [awslabs/serverless-application-model#73]
Here is my scenerio:

Deployed this:
```
---
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  ExampleFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: test.lambda_handler
      Runtime: python2.7
      CodeUri: ./deployment.zip
      Description: "Test Function"
      MemorySize: 128
      Timeout: 3
      Policies:
        - Statement:
            Effect: Allow
            Action: "sns:Publish"
            Resource:
              - $test_arn1
              - $test_arn2
      Events:
        PostResource:
          Type: Api
          Properties:
            Path: /
            Method: get
```

Then I had to change the Method to `post` and redeployed. I found that I had to go into the AWS Console and manually deploy the API again. I do not think this is by design and perceived by me to be an oversight/bug. Thoughts?
