### ISSUE TITLE
Unresolved resource dependencies when using ${AWS::AccountID}

### ISSUE THREAD

**Issue by radix** [awslabs/serverless-application-model#743]
**Description:**

I'm trying to use `!Sub "foo-${AWS::AccountID}-bar"` in my template. I see many examples of this on the Internet, but it's not working for me. I'm getting `Unresolved resource dependencies [AWS::AccountID] in the Resources block of the template`

**Steps to reproduce the issue:**
1. Use ${AWS::AccountID}
2. sam package
3. sam deploy

**Observed result:**

```
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Template format error: Unresolved resource dependencies [AWS::AccountID] in the Resources block of the template
```

**Expected result:**

AWS::AccountID should be replaced with the account ID.

Template:

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: foobar

Globals:
  Function:
    Timeout: 300

Parameters:
  env:
    Type: String
  SecurityGroup:
    Type: String
  Subnets:
    Type: List<String>

Resources:
  DeployJBApp:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: deploy_jb_app.handler
      Runtime: python3.7
      Role: !Sub "arn:aws:iam::${AWS::AccountID}:role/lambda-deploy-jb-app"
      Environment:
        Variables:
          ENVIRONMENT: !Ref env
      VpcConfig:
        SecurityGroupIds: !Ref SecurityGroup
        SubnetIds: !Ref Subnets

Outputs:
    DeployJBAppFunction:
      Description: "Deploy JB App Function"
      Value: !GetAtt DeployJBApp.Arn
```
