### ISSUE TITLE
Problem using SQS queue reference when defining Lambda event source

### ISSUE THREAD

**Issue by jhw** [awslabs/serverless-application-model#745]
I have a SAM template which -

- defines AWS::SQS::Queue
- defines AWS::Serverless::Function
-  within the Lambda function, defines an SQS event source which contains a *reference* to the SQS queue (since it may not have been created yet)

```
AWSTemplateFormatVersion: '2010-09-09'
Description: OR Backtest
Globals: {}
Outputs:
  ORBacktestFunction:
    Description: OR Backtest Lambda Function ARN
    Value: !GetAtt ORBacktestFunction.Arn
  ORBacktestQueue:
    Description: OR Backtest Lambda Queue ARN
    Value: !GetAtt ORBacktestQueue.Arn
  ORBacktestFunctionIamRole:
    Description: Implicit IAM Role created for OR Backtest function
    Value: !GetAtt ORBacktestFunctionRole.Arn
Resources:
  ORBacktestFunction:
    Properties:
      CodeUri: ../tmp/foobar-22682.zip
      Environment: {}
      Events:
        ORBacktestPingEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt ORBacktestQueue.Arn
            BatchSize: 1
      FunctionName: foobar-22682
      Handler: backtest.app.handler
      Runtime: python3.6
      MemorySize: 2560      
      Timeout: 30
    Type: AWS::Serverless::Function
  ORBacktestSQSQueue:
    Properties:
      QueueName: foobar-22682
    Type: AWS::SQS::Queue
Transform: AWS::Serverless-2016-10-31
```

but on running `sam deploy` I get the following -

```
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Template error: instance of Fn::GetAtt references undefined resource ORBacktestQueue
```

Can a SQS Lambda event source not contain a reference to a queue ? Must the ARN for the queue source be hardcoded ? This implies the SQS queue must be created outside the SAM template :-(

Thx -
