### ISSUE TITLE
Feature Request: AWS::ApiGateway::DocumentationVersion

### ISSUE THREAD

**Issue by Christoph-Schabert** [awslabs/serverless-application-model#747]
Hi,
at the moment its not possible to auto publish API Gateway Documentation that is define e.g. via inline Swagger.

Its also not possible to specify the DocumentationVersion at the stage.

``` 
  ApiDocumentation:
    Type: AWS::ApiGateway::DocumentationVersion
    Properties:
      DocumentationVersion: $hash_of_template
      RestApiId: !Ref ExternalApi
      
  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref Deployment
      DocumentationVersion: !Ref ApiDocumentation
      RestApiId: !Ref RestApi
      StageName: !Ref stageName
````

**Comment by keetonian** [comment]
SAM could probably do more than this for documentation; it could possibly allow users to document their API inline inside the SAM template. This is something that could be good for SAM to do

**Comment by mvanbaak** [comment]
@schabert @keetonian Any known workaround/method to actually deploy the documentation, other then logging into the console and publish it?

**Comment by cappaberra** [comment]
I am interested in seeing this functionality in SAM, as well.  Thanks! 👍

**Comment by Creatur3245** [comment]
👀

Here are some examples of how to define `AWS::ApiGateway::DocumentationVersion` and `AWS::ApiGateway::Stage`:

### Example of `AWS::ApiGateway::DocumentationVersion`
```yaml
myRestApiDocumentationVersion:
  Type: AWS::ApiGateway::DocumentationVersion
  Properties:
    DocumentationVersion: !Ref APIDocVersion
    RestApiId: !Ref myRestApi
  DependsOn: myRestApiDocumentationPart
```

### Example of `AWS::ApiGateway::Stage`
```yaml
myRestApiStage:
  Type: AWS::ApiGateway::Stage
  Properties:
    StageName: v1
    RestApiId: !Ref myRestApi
    DeploymentId: !Ref myRestApiDeployment
    DocumentationVersion: !Ref myRestApiDocumentationVersion
```

### Example of Automatically Publishing API Gateway Documentation

To automatically publish API Gateway documentation and specify the `DocumentationVersion` at the stage, you can use a CloudFormation template similar to the following:

```yaml
Resources:
  ApiDocumentation:
    Type: AWS::ApiGateway::DocumentationVersion
    Properties:
      DocumentationVersion: !Ref DocumentationVersion
      RestApiId: !Ref ExternalApi

  Stage:
    Type: AWS::ApiGateway::Stage
    Properties:
      DeploymentId: !Ref Deployment
      DocumentationVersion: !Ref ApiDocumentation
      RestApiId: !Ref RestApi
      StageName: !Ref StageName
```

* Please note that the search results might be incomplete. For more examples and further details, you can view the results directly in the GitHub UI using the following search links:

- [Search Results for DocumentationVersion](https://github.com/search?q=content%3AAWS%3A%3AApiGateway%3A%3ADocumentationVersion)

- [Search Results for Stage](https://github.com/search?q=content%3AAWS%3A%3AApiGateway%3A%3AStage)
