### ISSUE TITLE
VpcConfig Substitution Parameters

### ISSUE THREAD

**Issue by marjanSterjev** [awslabs/serverless-application-model#75]
Is it possible to define Comma Delimited List parameter and use that parameter reference when configuring Function’s VpcConfig?

```
Parameters:
  SubnetIdList:
    Type: CommaDelimitedList
    Description: Subnet Id list

. . .

  VpcConfig:
    SubnetIds: !Ref SubnetIdList
```

The deployment fails with the following error:

‘Invalid Serverless Application Specification document. Number of errors found: 1. Resource with id [TestFunction] is invalid. Type of property 'VpcConfig' is invalid’

Actually, the list is not the only problem. The following construct does not work as well.

```
Parameters:
  SubnetId:
    Type: String
    Description: Subnet Id 

. . .

  VpcConfig:
    SubnetIds: 
      - !Ref SubnetId
```
Any opinion?
