### ISSUE TITLE
Use variable in layers

### ISSUE THREAD

**Issue by mnapoli** [awslabs/serverless-application-model#751]
**Description:**

We are building PHP runtimes (as layers) in [Bref](https://github.com/mnapoli/bref).

But to use the layers users have to replace the region in `template.yaml` with the region their application is in.

Similar problem: the version of the layer will change over time, users will have to manually edit `template.yaml` to change the version number.

**Steps to reproduce the issue:**
1. Create the following `template.yaml`

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'my-function'
            CodeUri: .
            Handler: index.php # the name of your PHP file
            Runtime: provided
            Layers:
                - 'arn:aws:lambda:${AWS_DEFAULT_REGION}:416566615250:layer:php-72:${MY_LAYER_VERSION}'
```

2. Try to deploy or run locally

**Observed result:**

It doesn't work.

**Expected result:**

It should replace the variables in the layer name with the existing environment variables.

**Comment by timoschilling** [comment]
have you tried this?
```
 - !Sub 'arn:aws:lambda:${AWS_DEFAULT_REGION}:416566615250:layer:php-72:${MY_LAYER_VERSION}'
```

**Comment by mnapoli** [comment]
@timoschilling yes it doesn't either

`- 'arn:aws:lambda:us-east-2:416566615250:layer:php-72:9'`

works.

`- !Sub 'arn:aws:lambda:us-east-2:416566615250:layer:php-72:${MY_LAYER_VERSION}'`

doesn't work, this is the result in `sam local`:

```json
{
  "errorType": "Runtime.ExitError",
  "errorMessage": "RequestId: 52fdfc07-2182-154f-163f-5f0f9a621d72 Error: Couldn't find valid bootstrap(s): [/var/task/bootstrap /opt/bootstrap]"
}
```

Also this is the result when trying to deploy with SAM:

```
Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Template format error: Unresolved resource dependencies [MY_LAYER_VERSION] in the Resources block of the template
```

`- !Sub 'arn:aws:lambda:us-east-2:416566615250:layer:php-72:9'`

doesn't work either with `sam local`.

I think this is related to this issue: https://github.com/awslabs/aws-sam-cli/issues/528

**Comment by keetonian** [comment]
There seem to be a few issues:
1. `AWS_DEFAULT_REGION` is not a CFN parameter, but could be user defined. The corresponding CFN parameter is `AWS::Region`
1. `MY_LAYER_VERSION` wasn't defined in the parameters section of the template you supplied.
1. You need to use `!Sub` in order to resolve these parameters
1. SAM CLI doesn't resolve many intrinsics; this may be an intrinsic that it can't (yet) resolve and so it returns an error.

The following template should work (provided that the layer arn is valid):
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Parameters:
  MyLayerVersion:
    Default: 1
    Type: Number
Resources:
    MyFunction:
        Type: AWS::Serverless::Function
        Properties:
            FunctionName: 'my-function'
            CodeUri: .
            Handler: index.php # the name of your PHP file
            Runtime: provided
            Layers:
                - !Sub 'arn:aws:lambda:${AWS::Region}:416566615250:layer:php-72:${MyLayerVersion}'
```
