### ISSUE TITLE
Layer retention policy delete doesn't delete versions

### ISSUE THREAD

**Issue by estyh** [awslabs/serverless-application-model#761]
**Description:**
AWS::Serverless::LayerVersion has an optional property for RetentionPolicy. The docs say:

> Options are Retain and Delete. Defaults to Retain. When Retain is set, SAM adds DeletionPolicy: Retain to the transformed resource so CloudFormation does not delete old versions after an update.

I inferred from this that setting the value to Delete would cause cloudformation to delete old versions after updating. It doesn't though, it just keeps creating new versions and retaining the old ones.

**Steps to reproduce the issue:**
Here is a snippet from my template.yaml

```
Resources:
  BDBLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: 'bdb-Shared'
      ContentUri: ./dist
      CompatibleRuntimes:
        - nodejs8.10
      RetentionPolicy: Delete
```

**Observed result:**
New layer version is created. Lambda Layers console continues to show old layers.

**Expected result:**
I expected only the latest layer version to be available, and earlier versions to get deleted.
