### ISSUE TITLE
Cross-Stack reference - ImportValue

### ISSUE THREAD

**Issue by GeekOnGadgets** [awslabs/serverless-application-model#768]
**Description:**
Sorry this might fall under `question` label. I am trying to reference output from one stack into the other stack but keeps on getting error. I am pretty sure, I am doing it wrong!  

Below is `template.yaml` for `custom authorizer`

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Globals:
  Function:
    Runtime: nodejs8.10

Resources:
  Authorizer:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: test-custom-authorizer
      CodeUri: src/
      Handler: index.handler

Outputs:
  AuthorizerArn:
    Description: The Arn of the test authorizer
    Value: !GetAtt Authorizer.Arn
    Export: 
      Name: test-autorizer-a
```

I am trying to use the `Export value` from above stack into below. 

```
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"

Globals:
  Function:
    Runtime: nodejs8.10
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  #API Gateway and custom authorizer
  TestApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: test-custom-authorizer
        Authorizers:
          test-custom-authorizer:
            FunctionArn:
              Fn::ImportValue: test-autorizer-a
            Identity:
            Header: Auth
            ValidationExpression: Bearer.*
            ReauthorizeEvery: 30

  #Test endpoint
  Test:
    Type: "AWS::Serverless::Function"
    Properties:
      FunctionName: test
      CodeUri: src/test
      Handler: index.test
      Events:
        EndPoint:
          Type: Api
          Properties:
            RestApiId: !Ref TestApi
            Path: /test
            Method: get
            Auth:
              Authorizer: !Ref test-custom-authorizer
```

I tried different ways to use the ImportValue but somehow I am not getting this. Any help would be highly appreciated. 

Error: Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Transform AWS::Serverless-2016-10-31 failed with: Internal transform failure.

Thanks
