### ISSUE TITLE
GET function on resource missing

### ISSUE THREAD

**Issue by bolddp** [awslabs/serverless-application-model#77]
This template data:

```
  # GET thing by filter
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.getThingsByFilter
      Runtime: nodejs4.3
      CodeUri: lambda.zip
      Role: !GetAtt ThingsLambdaRole.Arn
      Timeout: 10
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /things
            Method: get

  # GET thing by id
  GetFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.getThing
      Runtime: nodejs4.3
      CodeUri: lambda.zip
      Role: !GetAtt ThingsLambdaRole.Arn
      Timeout: 10
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /things/{resourceId}
            Method: get

```

results in only one GET function in the output template:

```
  GetFunction:
    Properties:
      CodeUri: s3://bucket-name/2e273691a2f36a1bb5558e13f9761de3
      Events:
        GetResource:
          Properties:
            Method: get
            Path: /things/{resourceId}
          Type: Api
      Handler: lambda.getThing
      Role:
        Fn::GetAtt:
        - ThingsLambdaRole
        - Arn
      Runtime: nodejs4.3
      Timeout: 10
    Type: AWS::Serverless::Function

```

Please advice!
