### ISSUE TITLE
VpcConfig invalid when referencing other resources

### ISSUE THREAD

**Issue by Leuloch** [awslabs/serverless-application-model#770]
The following returns the error message `Resource with id [CustomersFunction] is invalid. property SubnetIds not defined for resource of type AWS::Serverless::Function`.  Though appears to be valid.

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Vending API to expose customers from database

Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  CustomersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.test.customers.LambdaFunctionHandler::handleRequest
      Runtime: java8
      CodeUri: target/test-1.0.0.jar
      MemorySize: 512
      Policies:
        - AWSLambdaBasicExecutionRole
        - AWSLambdaVPCAccessExecutionRole
      Timeout: 600
      VpcConfig:
        SubnetIds:
          - subnet-1111aaaa
          - subnet-2222eeee
        SecurityGroupIds:
          - sg-2333333
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
```

If I try to set the VpcConfig throug AWS console, doesn't work either, if no error message.
