### ISSUE TITLE
Inject StageVariable into API resource definition that uses a Swagger file

### ISSUE THREAD

**Issue by sanathkr** [awslabs/serverless-application-model#8]
When using a Swagger file to define an API, users have to explicitly specify `Stage Variables` to hold the Lambda function ARN and use the stage variable in their Swagger template to specify the integration. This is not intuitive.

We could simplify this process by automatically injecting the Stage Variable when users specify an API Event source to their Lambda Function

When customers specify a template like this:
```
LambdaFunction:
  Type: AWS::Serverless::Function
  Properties:
      Handler: index.handler
      Runtime: nodejs4.3
      Events:
         GetApi:
             Type: API
              Properties:
                  Path: /
                  Method: GET
                  RestApiId: !Ref MyApiResource

MyApiResource:
   Type: AWS::Serverless::Api
   Properties:
        DefinitionUri: s3://bucket/myswagger.yaml
```

we could inject a StageVariable to the API resource where variable name is equal to the function resource's logical name and value equal to the function's ARN

```
MyApiResource:
   Type: AWS::Serverless::Api
   Properties:
        DefinitionUri: s3://bucket/myswagger.yaml
        Variables:
             LambdaFunction: !Ref LambdaFunction
```

**Comment by dinvlad** [comment]
_examples/2016-10-31/api_swagger_cors_ seems to inject the function logical name. Could we somehow get the full ARN such that we don't have to hard-code `region` and `accountId` into Swagger as well? Thanks

**Comment by mparaz** [comment]
Yes, getting the full ARN would be useful. This will solve my problem with using a stage variable for the account ID - #87

**Comment by prearrangedchaos** [comment]
Region/AccountId would be very usefull. I know this is a limitation on the API Gateway, but could this info not be merged into the swagger file at package time in the CloudFormation cli?

**Comment by dinvlad** [comment]
My current workaround (since I cannot use inline body in other tools, like Swagger Editor, or for input validation) is to maintain a separate swagger.yaml, but format everything as if it was inside a SAM template (i.e. I can use the intrinsics etc.). I then terminate my SAM template with the Api resource, but instead of specifying DefinitionBody as the last parameter, I just terminate it there and during 'build' I concatenate the two (YAML lets you do that if you also properly indent all lines of the Swagger file, either explicitly in the file or using a regular expression in gulp-replace or something similar).

**Comment by dinvlad** [comment]
Nice, it seems like now we will be able to use http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/create-reusable-transform-function-snippets-and-add-to-your-template-with-aws-include-transform.html to directly insert the Swagger YAML stored on S3. Will report back once I test it.

**Comment by gertjvr** [comment]
Eager to see what possible with include transform, wonder if they will allow you to point to a local template like `aws package` does.

**Comment by dinvlad** [comment]
Yay, it is! Here's my snippet:
```
  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Latest
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: !Sub s3://${ArtifactsBucket}/swagger.yaml
```
Then, in swagger.yaml I'm able to use `!Sub` and possibly other functions to reference resources, e.g.
```
x-amazon-apigateway-integration:
  type: aws_proxy
  httpMethod: GET
  uri:
    Fn::Sub: "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/\
      functions/${GetApi.Arn}/invocations"
```
Obviously, I have to upload the swagger template to the specified bucket and pass the bucket name as a parameter to the SAM template prior to 'packaging' it. But it works! And allows me to preview the changeset, unlike with "nested" templates.

**Comment by dinvlad** [comment]
Finally got it working! In my SAM template:
```
Api:
  Type: AWS::Serverless::Api
  Properties:
    StageName: Latest
    DefinitionBody:
      Fn::Transform:
        Name: AWS::Include
        Parameters:
          Location: !Sub s3://${ArtifactsBucket}/swagger.yaml
```
where `ArtifactsBucket` refers to the bucket where I upload my Swagger spec prior to 'packaging' the SAM template. Then, in the Swagger template itself I can use the intrinsics, e.g.
```
x-amazon-apigateway-integration:
  type: aws_proxy
  httpMethod: POST
  uri:
    Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetProjects.Arn}/invocations
```
I'm using the long `Fn::Sub` notation here instead of just `!Sub`, because Swagger doesn't natively support the latter, and also because the docs on `AWS::Include` Transform say that shorthand forms are not supported yet.

On a side note, just wasted ~4 hours troubleshooting the `Invalid ARN specified in the request` error, thinking that `Fn::Sub` for function ARNs doesn't work. Turns out, I only forgot to prepend an ARN reference for `authorizerCredentials` role in the spec (I'm using a custom authorizer). I really wish API Gateway import errors were more informative! Like specifying the concrete line that fails.. In any case, just make sure to prepend `Fn::Sub`/`Fn::Ref`/`Fn::GetAtt` to ALL of your CloudFormation references in the spec.
