### ISSUE TITLE
Circular dependency error with S3 event in Lambda function

### ISSUE THREAD

**Issue by ellier** [awslabs/serverless-application-model#816]
I'm getting the circular dependecy error below. I've tried every example possible I've found on the web and always get the same error. Please, advise.

> Failed to create the changeset: Waiter ChangeSetCreateComplete failed: Waiter encountered a terminal failure state Status: FAILED. Reason: Circular dependency between resources: [Bucket, ProcessFileFunctionFileUploadedEventPermission, ProcessFileFunction]

```
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Csv Integration

Parameters:
  OutputBucketName:
    Type: String

Globals:
  Function:
    Handler: app.handler
    Runtime: nodejs8.10
    Timeout: 15

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref OutputBucketName

  ProcessFileFunction:
    Type: AWS::Serverless::Function
    DependsOn: Bucket
    Properties:
      CodeUri: ProcessFile/
      Policies:
        - AWSLambdaExecute
        - AmazonS3ReadOnlyAccess
      Events:
        FileUploadedEvent:
          Type: S3
          Properties:
            Bucket: !Ref Bucket
            Events: s3:ObjectCreated:*
```
