### ISSUE TITLE
AWS::Serverless::Function with Condition=false tries to resolve !Refs

### ISSUE THREAD

**Issue by mxpv** [awslabs/serverless-application-model#832]
**Description:**
I use `Condition` property for creating resources depending on CF parameter configuration. 
I noticed that when `Condition` is set to false in `AWS::Serverless::Function` (resource is not going to be created) it still tries to resolve references. 

**Steps to reproduce the issue:**
Here is an example of template to reproduce the issue:
```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Conditions:
  CreateResources: !Equals ["1", "2"]
Resources:
  Topic:
    Type: AWS::SNS::Topic
    Condition: CreateResources
    Properties:
      TopicName: TestTopic
  Lambda:
    Type: AWS::Serverless::Function
    Condition: CreateResources
    Properties:
      CodeUri: s3://s3_path/
      FunctionName: TestLambda
      Handler: lambda
      MemorySize: 128
      Runtime: go1.x
      Policies:
      - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          SNS_TOPIC_ARN: !Ref Topic <-- this ref will fail when CreateResources=false

```

**Observed result:**
When `CreateResources` false, resources are not going to be created. However when deploying this template, it fails with error `Template format error: Unresolved resource dependencies [Topic] in the Resources block of the template. Rollback requested by user.` When `CreateResources` true everything works as expected. Basically it tries to resolve reference between two not existing resources.

**Expected result:**
`!Ref`s inside `AWS::Serverless::Function` with `Condition=false` should not be resolved, resource is not going to be created.
