### ISSUE TITLE
Gradual deployment for AWS::Serverless::Function fails from time to time due to permission error

### ISSUE THREAD

**Issue by zllvm** [awslabs/serverless-application-model#838]
**Description:**

When using gradual deployment SAM feature with Hooks, hook lambda fails with AccessDeniedException _from time to time_ (there are periods during the week when our pipe could be stuck for an hour or more due to this), though in most cases it works pretty fine.
Although I am aware of [eventual consistency for IAM changes](https://docs.aws.amazon.com/IAM/latest/UserGuide/troubleshoot_general.html#troubleshoot_general_eventual-consistency), it seems like this should be handled by SAM, since it is an internal routine that is abstracted away and could not be controlled directly.

**Steps to reproduce the issue:**
1. Create a serverless lambda with a gradual deployment and a hook.
```yaml
Lambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: z-lambda
      Runtime: dotnetcore2.1
      Timeout: 40
      MemorySize: 256      
      Role: !GetAtt LambdaRole.Arn
      Handler: <handler>
      CodeUri: 
        Bucket: !Ref  Bucket
        Key: !Ref S3Key
      AutoPublishAlias: live
      DeploymentPreference:
        Type: !Ref DeploymentPreference
        Hooks:
          PreTraffic: !Ref PreTrafficLambda
      Environment:
        Variables:
          CurrentVersion: !Ref Version

PreTrafficLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub CodeDeployHook_z-lambda_preTrafficHook 
      Runtime: python3.6
      Timeout: 20
      MemorySize: 128
      Handler: pre_traffic_hook.handler
      CodeUri: 
        Bucket: !Ref Bucket
        Key: !Ref PreS3Key
      Environment:
        Variables:
          NewVersion: !Ref Lambda.Version
      Policies:
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - codedeploy:PutLifecycleEventHookExecutionStatus
            Resource:
              !Sub arn:aws:codedeploy:${AWS::Region}:${AWS::AccountId}:deploymentgroup:${ServerlessDeploymentApplication}/*
        - Version: "2012-10-17"
          Statement:
          - Effect: "Allow"
            Action:
              - lambda:InvokeFunction
            Resource: !Ref Lambda.Version
```
2. Create a hook lambda that could contain the following call to the a new version of the lambda:
```python
def handler(event, context):
   new_version = os.environ['NewVersion']
   . . .
   response = lambda_client.invoke(
      FunctionName=new_version,
      Payload=json.dumps(event)
   )
```
3. Do a deployment. 

**Observed result:**
Just before CodeDeploy deployment is started, the inlined policy for the hook is updated to the following:
```yaml
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Action": [
                "lambda:InvokeFunction"
            ],
            "Resource": "arn:aws:lambda:<region>:<account>:function:z-lambda:10",
            "Effect": "Allow"
        }
    ]
}
```
And the environment variable NewVersion for the hook lambda is updated to:
arn:aws:lambda:<region>:<account>:function:z-lambda:10

However, CodeDeploy step fails with:
```
[ERROR]	2019-03-04T13:37:38.468Z	cc4f65f9-1d5b-4052-96ee-b77348ffcfb4	Invoke lambda exception: An error occurred (AccessDeniedException) when calling the Invoke operation: User: arn:aws:sts::<account>:assumed-role/z-lambda-PreTrafficLambda-WBTI1BL3LJED/CodeDeployHook_z-lambda_preTrafficHook is not authorized to perform: lambda:InvokeFunction on resource: arn:aws:lambda:<region>:<account>:function:z-lambda:10
```
**Expected result:**
The pretraffic hook lambda should be able to call successfully a newly deployed version of the original lambda.
