### ISSUE TITLE
Feature Request: CORS response headers on lambda throttling

### ISSUE THREAD

**Issue by P00L** [awslabs/serverless-application-model#840]
When you enable CORS support for your API (like in the snippet below) it all works perfectly. Easy to define, read and manage, except in case your lambda exceed timeout execution, in this case the client receive an exception `Check CORS is enabled` instead of a throttling error, due to the fact that headers are not present in the response handled by API gateway since you have no control on Method Response. It's possible to define the entire swagger but you will loose readability and maintenance, would be great that will be manage by SAM directly.

```
Api:
    Name: "Test"
    Cors:
      AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
      AllowHeaders: "''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token''"
      AllowOrigin: "'*'"
Resources:
  Get:
    Type: AWS::Serverless::Function
    Properties:
      Role: !GetAtt TestFunctionRole.Arn
      CodeUri: get
      Handler: app.lambda_handler
      Tracing: Active
      Events:
        Endpoint:
          Type: Api
          Properties:
            Path: /test
            Method: get
```

Thanks
