### ISSUE TITLE
Swagger does not allow a stage variable for the account ID

### ISSUE THREAD

**Issue by mparaz** [awslabs/serverless-application-model#87]
I am trying to use this Swagger:

paths:
  /documents:
    post:
      responses: {}
      security:
      - authorizerFunc: []
      x-amazon-apigateway-integration:
        uri: arn:aws:apigateway:ap-southeast-2:lambda:path/2015-03-31/functions/arn:aws:lambda:ap-southeast-2:${stageVariables.AccountId}:function:${stageVariables.PostFunctionName}/invocations
        passthroughBehavior: "when_no_match"
        httpMethod: "POST"
        type: "aws_proxy"

with the corresponding template:

Resources:
# Explicit API Gateway definition needed for the Custom Authorizer.
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: swaggerFile.yaml
      StageName: Prod
      Variables:
        PostFunctionName: !Ref PostFunction
        AccountId: 1234567890

But I get a CloudFormation stack event with:

"ResourceStatusReason": "Errors found during import:\n\tUnable to put integration on 'POST' for resource at path '/documents': Lambda function ARN must be in same account"

It works fine when I put the literal AccountId 1234567890 in the URI.

It looks like the stageVariable reference isn't expanded, is that right?

Thanks!

**Comment by sanathkr** [comment]
Unfortunately, AccountID has to be hard-coded. This is an APIGateway limitation

**Comment by prearrangedchaos** [comment]
Region/AccountId would be very usefull. I know this is a limitation on the API Gateway, but could this info not be merged into the swagger file at package time in the CloudFormation cli?

**Comment by ffxsam** [comment]
@sanathkr could you please explain how this works?

For example:

```yaml
ApiGatewayApi:
  Type: AWS::Serverless::Api
  Properties:
    DefinitionUri: swaggerFile.yaml
    StageName: Prod
      Variables:
        PostFunctionName: !Ref PostFunction
        AccountId: 1234567890
```

Why would `${stageVariables.AccountId}` not work? It seems we can pass whatever variables we want from the CloudFormation template, correct? Why would `PostFunctionName` work but not `AccountId` since it's just another variable?

I'm having a similar issue #178 where I can't pass a Cognito UserPool ARN into a Swagger doc. How are these limitations of API Gateway when I can create an API and set the exact same stage variables & values I'm trying to pass via CloudFormation?

**Comment by deddu** [comment]
Can we please reopen this issue? Or at least can someone please address the question @ffxsam asked? 
Why do some stage variables get interpolated and some do not? Where can we find documentation about this? 
EG:

```
Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Stage
      # built dynamically during built phase, so that it can use all the yml features
      DefinitionUri: swagger.json
      Variables:
        #those will be exposed as stage vars in the swagger file, and some, interpolated by api-gw!
        BasePath: !Ref Stage 
        TheLambda: !Ref TheLambda
        TheLambdaARN: !GetAtt TheLambda.Arn # does not work
        Region: !Ref "AWS::Region" # does not work
        AccountId: !Ref "AWS::AccountId" # does not work
```
WHY?
