### ISSUE TITLE
Policy not applied

### ISSUE THREAD

**Issue by madmod** [awslabs/serverless-application-model#88]
When I create a lambda with a statement like the following the policy is not applied but no error is thrown either. The result is a policy with only the `AWSLambdaBasicExecutionRole` without any Role policies.

```yaml
  SignAttachmentUploadFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'index.handler'
      Runtime: 'nodejs4.3'
      CodeUri: 'lambdas/sign-attachment-upload'
      Description: !Sub '${Project} API endpoint for signing a new file upload with a random filename hash.'
      Policies:
        - PolicyName: 'AllowAttachmentUploads'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: 'Allow'
                Action:
                  - 's3:PutObject'
                  - 's3:PutObjectACL'
                Resource: !Sub 'arn:aws:s3:::${AttachmentsBucket}/*'
      Environment:
        Variables:
          AttachmentUploadBucket: !Ref 'AttachmentsBucket'
      Events:
        SignAttachmentUpload:
          Type: 'Api'
          Properties:
            Path: '/sign-attachment-upload'
            Method: 'post'
    DependsOn:
      - 'AttachmentsBucket'
```

I solved it by only including the `PolicyDocument` instead of the entire policy.

```yaml
  SignAttachmentUploadFunction:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: 'index.handler'
      Runtime: 'nodejs4.3'
      CodeUri: 'lambdas/sign-attachment-upload'
      Description: !Sub '${Project} API endpoint for signing a new file upload with a random filename hash.'
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: 'Allow'
              Action:
                - 's3:PutObject'
                - 's3:PutObjectACL'
              Resource: !Sub 'arn:aws:s3:::${AttachmentsBucket}/*'
      Environment:
        Variables:
          AttachmentUploadBucket: !Ref 'AttachmentsBucket'
      Events:
        SignAttachmentUpload:
          Type: 'Api'
          Properties:
            Path: '/sign-attachment-upload'
            Method: 'post'
    DependsOn:
      - 'AttachmentsBucket'
```

Thanks!
