### ISSUE TITLE
SAM doesn't support Fn::If On Policy Templates

### ISSUE THREAD

**Issue by mlaff** [awslabs/serverless-application-model#889]
**Description:**

SAM doesn't support `Fn::If` in `Policies` section of `AWS::Serverless::Function` when managed policies are listed.

Using template: 

```yaml
Conditions:
  StreamNameProvided:
    Fn::Not:
    - Fn::Equals:
      - Ref: StreamName
      - ''

Resources:
  ProcessLogs:
    Properties:
      InlineCode: print('hi')
      Description: Do stuff
      Handler: index.handler
      MemorySize: 128
      Policies:
        - Fn::If:
          - StreamNameProvided
          - KinesisStreamReadPolicy
            StreamName:
              Ref: StreamName
          - AWS::NoValue
        - Statement:
          Action: cloudwatch:PutMetricData
          Effect: Allow
          Resource: '*'
      Runtime: nodejs8.10
      Timeout: 10
    Type: AWS::Serverless::Function
```
we fail with an unhandled exception. But as seen in [874](https://github.com/awslabs/serverless-application-model/issues/874), this (sort of) works with explicit policy statements. `Fn::If` should work with managed policies as well as explicit ones.
