### ISSUE TITLE
SAM does not support empty SemanticVersion in AWS::Serverless::Application resource

### ISSUE THREAD

**Issue by ylynn** [awslabs/serverless-application-model#891]
**Description:**

SAM does not support empty SemanticVersion in AWS::Serverless::Application resource.

Using template:

```
Resources:
    helloworld:
      Type: AWS::Serverless::Application
      Properties:
        Location:
          ApplicationId: arn:aws:serverlessrepo:us-east-1:077246666028:applications/hello-world
          SemanticVersion:
        Parameters:
          IdentityNameParameter: YOUR_VALUE
```

Fail with an unhandled exception.
