### ISSUE TITLE
Support APIGW Models in API Events

### ISSUE THREAD

**Issue by keetonian** [awslabs/serverless-application-model#895]
It would be nice to add options to the `API` event source for `AWS::Serverless::Function` for models (request and response) and validators similar to how authorizers can be defined in there now without having to dive into swagger.

_Originally posted by @beck3905 in https://github.com/awslabs/serverless-application-model/issues/850#issuecomment-485141374_

Models in swagger: https://swagger.io/docs/specification/2-0/describing-request-body/ (see Object Payload section).

I think we should add models to the `Serverless::Api` resource and allow events to reference them:

```yaml
Resource:
  Api:
    Type: AWS::Serverless::Api
    Properties:
      Models: # use swagger format to define models. This gets passed through to the `definitions` section of swagger.
        User:   
          type: object
          required:
            - userName
          properties:
            userName:
              type: string
            firstName:
              type: string
            lastName:
              type: string
     ...

  Function:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            RequestModel: User    # reference by string name
            ResponseModel: User  # reference by string name
```
