### ISSUE TITLE
Nested stack issue

### ISSUE THREAD

**Issue by Jamakase** [awslabs/serverless-application-model#90]
I am trying to make stack with nested stacks, but when i have Transform in nested stack, i get an error: 
`CreateStack cannot be used with templates containing Transforms`. If this error is expected, this should be added somewhere to docs, that only parent stack should have `Transforms`.

In case i delete `Transforms` from nested stacks, i get `	Circular dependency between resources: [ApiGatewayApi, InviteUserFunction, LambdaInvokePermission]`, which i do not have if i create this stack separately.

Here is part of nested stack template
```
AWSTemplateFormatVersion: 2010-09-09
Resources:
  ApiGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      DefinitionUri: ./../target/swagger.yaml
      StageName: Prod
      Variables:
        InviteUserFunctionName: !Ref InviteUserFunction
  InviteUserFunction:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 30
      Role: !GetAtt LambdaFunctionIAMRole.Arn
      Handler: com.MyHandler
      Runtime: java8
      CodeUri: ./../target/some.jar
      Events:
        GetRequest:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGatewayApi
            Path: /invite
            Method: POST
  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        !GetAtt InviteUserFunction.Arn
      Principal: apigateway.amazonaws.com
      SourceArn:
        Fn::Join:
        - ''
        - - 'arn:aws:execute-api:'
          - Ref: AWS::Region
          - ":"
          - Ref: AWS::AccountId
          - ":"
          - Ref: ApiGatewayApi
          - "/*"
```

**Comment by sanathkr** [comment]
You should use `create-change-set` and `execute-change-set` APIs to create a stack using with Transforms. `create-stack` API won't work

**Comment by ulu5** [comment]
@sanathkr how would you do that with a nested stack? There's no ChangeSet resource.

http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html

**Comment by schmitzcc** [comment]
+1

**Comment by windlessuser** [comment]
+1

**Comment by dbrainnet** [comment]
Came here to mention something specifically about the Change Set requirement and Nested stacks. Currently Change Sets do not traverse Nested stacks, so I'm going to operate under the assumption that you can not nest with SAM which is a major pitfall.

**Comment by alanwill** [comment]
Only the reverse seems to work, i.e. you can have a SAM enabled template as the parent template just not the child, which is quite a bummer and limiting.

**Comment by alanwill** [comment]
This really should be tagged as a bug not a question @sanathkr

**Comment by sanathkr** [comment]
How about including `Transform: 'AWS::Serverless-2016-10-31'` to the parent template even if it doesn't use SAM resources. AFAIK, the nested templates should get transformed as well when they are processed. 

If not, this is a bug that needs to be fixed.

**Comment by alanwill** [comment]
@sanathkr tried that before and just did it again to be sure, same error `CreateStack cannot be used with templates containing Transforms`. Thanks for marking this as a bug, hope it can get addressed soon.

**Comment by dinvlad** [comment]
Same here `CreateStack cannot be used with templates containing Transforms`. I hit the 200 resource limit in the SAM template, so it has to be split it into a nested stack. Otherwise the development is stalled at the moment.

**Comment by alanwill** [comment]
Any thoughts on this @sanathkr I now have a workaround to a workaround just to try to get around this. The workaround was to put all the SAM resources in the parent stack, but then that go too large in a single stack so I have another workaround to that. Any guidance you can provide here would be super helpful.

**Comment by dejonghe** [comment]
What I've done is create a CFN Template launcher in python with Boto that goes through all the steps. I have a Yaml file that defines stacks and can grab output from one stack and pass it as a parameter to another.

**Comment by Dunedan** [comment]
@sanathkr Any news regarding this issue? It'd be so great to have that fixed.

**Comment by mastrchee** [comment]
Having the same issue, any update @sanathkr?

**Comment by dinvlad** [comment]
We moved away from SAM due to this problem. At the cost of more verbose templates and an extra packaging step, we also got more flexibility with 'native' resources.

**Comment by Widdershin** [comment]
Even further than that, this issue was a factor in my team dropping CloudFormation in favour of Terraform.

At least with Terraform, we can fork and fix issues ourselves, rather than just waiting.

**Comment by aehlke** [comment]
@dinvlad could you share what your template looks like?

**Comment by dinvlad** [comment]
@aehlke serverless functions can be replaced with 3 resources: `AWS::Lambda::Function`, `AWS::IAM::Role` and `AWS::Lambda::Permission`, then you just customize them as needed:
```yaml
  Function:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Environment:
        Variables:
          VAR_NAME: !Ref ...
      Runtime: nodejs6.10
      Code:
        S3Bucket: !Ref LambdaBucket
        S3Key: !Ref LambdaPackageKey
      Role: !GetAtt FunctionRole.Arn

  FunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: FunctionRole
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - service:Action
                Resource:
                  - !GetAtt Resource.Arn

  FunctionRolePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref Function
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn:
        !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiId}/${ApiStage}/GET/...
```
Before execution of the stack, you also need to upload lambda package as a zip file to `s3://${LambdaBucket}/${LambdaPackageKey}`.

**Comment by sanathkr** [comment]
Turns out this is a CloudFormation feature that doesn't exist today. We are working internally with the team to this feature implemented.

Keeping the issue open for tracking

**Comment by lfdesousa** [comment]
Any news, on this one?

**Comment by rossrossp** [comment]
+1

**Comment by dqvist** [comment]
+1

**Comment by jasondebolt** [comment]
I encountered the same "CreateStack cannot be used with templates containing Transforms." when trying to do transforms on a nested stack.

**Comment by SubatomicHero** [comment]
Ive just come across this issue and would like this fixed. Adding transform to the parent also doesnt solve the issue

**Comment by jfuss** [comment]
@SubatomicHero Please read @sanathkr message above. His statement still holds true.

**Comment by aliniacobv** [comment]
We'd very much like a fix for this, as well.

**Comment by niraj-bpsoftware** [comment]
After struggling for weeks on trying to resolve different SAM issues, I think we are better off with Cloud Formation templates as SAM still has a long way to go and also there are still very limited documents out there.

**Comment by paul-wilkinson** [comment]
+1

**Comment by jniedrauer** [comment]
This is a big limitation. The whole deployment mechanism for SAM feels like a hack. Cloudformation should be smart enough to do the transforms on the server side.

**Comment by Dunedan** [comment]
> Cloudformation should be smart enough to do the transforms on the server side.

CloudFormation does these transformations on server side. But your comment got me thinking. Thanks to the recent open sourcing of [samtranslator](https://github.com/awslabs/serverless-application-model/tree/develop/samtranslator) it's possible to do the transformations locally before deploying. I haven't tested that with nested stacks yet, but I suppose that could work.

In case somebody wants to try it out, I already made a small script for doing such transformations locally: https://github.com/Dunedan/serverless-applications-with-aws-sam/blob/gh-pages/local_samtranslator.py
In theory running all nested templates through that script before deploying should just work.

**Comment by brettstack** [comment]
@Dunedan we'd love to see a light CLI with transform and validate commands. Would you be open to submitting a PR?

**Comment by rohitrishi** [comment]
does `aws cloudformation deploy` also not support sam? I am trying to use the deploy function and keep getting the following error: 
```aws: error: argument subcommand: Invalid choice, valid choices are:

push                                     | register
deregister                               | install
uninstall
Warning: Task "deploy:201805301407" failed. Use --force to continue.```

This is my grunt task:
```grunt.registerTask('deploy', function(timestamp) {
    const { code } = shelljs.exec('aws cloudformation deploy --stack-name my_Stack ' +
    '--template-file ./cloudformation.yaml ' +
    '--capabilities CAPABILITY_IAM ' +
    '--parameter-overrrides AwsServerlessExpressS3Bucket=myBucket ' +
    `Timestamp=${timestamp} ` +
    `LambdaFunctionS3Key=lambda-function.${timestamp}.zip ` +
    `ApiGatewaySwaggerS3Key=swagger.${timestamp}.yaml ` +
    '--region eu-west-1');
    return code === 0;
  });```

aws cli version: 1.12.2

**Comment by kurtmaile** [comment]
Hi, Any update on SAM and nested stacking issue? Bit of an issue for myself at the moment when you get into a sizeable set of resources.

**Comment by kurtmaile** [comment]
Also with SAM, the steps are to package then deploy.  How best to introduce change sets (for prod approval) and stack deletion policies as they are skipped over when using the package/deploy step?

**Comment by brettstack** [comment]
We're hoping to support nested stacks via SAM CLI local transformations.

**Comment by jniedrauer** [comment]
@brettstack If the transform happens on the clientside, won't this mean that SAM nested stacks will be limited to 200 resources between both the parent stack and the nested stack(s) (ie. they are combined into a single stack using a clientside transform)? Doesn't this defeat the point of using nested stacks?

**Comment by brettstack** [comment]
That's not what we have in mind. More like it will perform the transform on each individual template

**Comment by SamanehU** [comment]
Hope there will be a possibility in AWS SAM CLI to transform SAM template locally soon. Then I will be able to have the transformed stack as a nested stack in my master stack. @brettstack When this feature will be available to use?

**Comment by brettstack** [comment]
I can't comment on timeline, but we're actively talking about this internally and we'll create a thread in the SAM CLI repo for more discussion and details soon.

You could potentially hack this together yourself with `sam validate --debug` which logs the transformed template in latest SAM CLI version, but it won't be ideal. Alternatively, if you're really ambitious you could fork the CLI and have a crack at implementing Local Transform

**Comment by Dunedan** [comment]
@brettstack: Just out of curiosity: What's the motivation to solve that by applying the transformations locally? Couldn't that be done in the same way by CloudFormation as the transformation of the parent template?

**Comment by brettstack** [comment]
We want to do local transform for other reasons anyway. Two birds sort of deal.

**Comment by christianklotz** [comment]
I happened to run into the same nested SAM template issue a couple of days ago. Although it would be great if SAM templates would be expanded automatically by CloudFormation, for now I use [sam-translate.py](/awslabs/serverless-application-model/blob/master/bin/sam-translate.py) as workaround locally and for deployment.

1. Package SAM template to make sure all `CodeUri` point to S3 urls since `aws-sam-translator` doesn't support local uris.
2. Expand the packaged template using [`sam-translate.py`](/awslabs/serverless-application-model/blob/master/bin/sam-translate.py)
3. Upload expanded template to S3 bucket.
4. Deploy the root stack, providing the bucket the templates have been uploaded to.


## Steps

I didn't have `aws-sam-translator` installed so the following worked for me.

    pip install docopt PyYAML aws-sam-translator

As far as I can tell [`sam-translate.py`](/awslabs/serverless-application-model/blob/master/bin/sam-translate.py) itself doesn't get installed so create a copy of it on my machine.

    sam package
      --s3-bucket "$BUCKET" \
      --template-file "$TEMPLATE_DIR/my-app.sam.yaml" \
      --output-template-file "$TEMPLATE_DIR/my-app.sam.pkg.yaml"

    python sam-translate.py \
      --input-file="$TEMPLATE_DIR/my-app.sam.pkg.yaml" \
      --output-file="$TEMPLATE_DIR/my-app.cfn.json"

    aws s3 cp --recursive "$TEMPLATE_DIR" "s3://$BUCKET/templates"

    aws cloudformation deploy --template-file ./my-root-stack.yaml

### Example of the root stack

```yaml
AWSTemplateFormatVersion: 2010-09-09

Description: Nested stack featuring SAM

Parameters:
  TemplateBucket:
    Type: String
    Default: deployment-artifacts
    Description: |
      The bucket for the CloudFormation templates and packaged SAM application.

Resources:
  MyAppStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://s3.amazonaws.com/${TemplateBucket}/templates/my-app.cfn.json
```
