### ISSUE TITLE
Strings not translating with sam-cli or awscli.

### ISSUE THREAD

**Issue by taylorbartley** [awslabs/serverless-application-model#906]
**Description:**

I'm using ```sam-cli``` to package my ```.yaml``` template. I've noticed that some strings do not translate properly in the packaging process.  Unfortunately, this causes my template to fail validation. So far, ```"08"``` and ```"09"``` fail to translate to ```'08'``` or ```'09'```. Other 
strings, like ```"00"``` and ```"07"``` do translate properly to ```'00'``` and ```'07'```, respectively.
Example:
```yaml
  HourParam:
    Type: String
    Default: "08"
```

**Steps to reproduce the issue:**
1. Yaml template, such as "template.yaml" with the text 
```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Creates snapshot management lambda functions.
Parameters:
  HourParam_0:
    Type: String
    Default: "08"
  HourParam_1:
    Type: String
    Default: "07"
```
2. Run 
```bash
sam build
```
3. Run
```bash
sam package --template-file template.yaml --output-template-file packaged.yaml --s3-bucket <your-bucket>
```

**Observed result:**
```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Creates snapshot management lambda functions.
Parameters:
  HourParam_0:
    Type: String
    Default: 08
  HourParam_1:
    Type: String
    Default: '07'
```

**Expected result:**
```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Creates snapshot management lambda functions.
Parameters:
  HourParam_0:
    Type: String
    Default: '08'
  HourParam_1:
    Type: String
    Default: '07'
```

**Note**
I've update 
```bash
aws-lambda-builders
aws-sam-cli
aws-sam-translator
awscli
```
And even
```bash
boto3
cnf-lint
```

I'm aware of issue [131](https://github.com/awslabs/serverless-application-model/issues/131), but it shows as closed 2 years ago. 
And the bug seems to be back.
