### ISSUE TITLE
AWS::Serverless:Function with Ref in codeuri for code in relative path 

### ISSUE THREAD

**Issue by revolutionisme** [awslabs/serverless-application-model#912]
**Description:**

We are using SAM with serverless functions having codeuri being specified to a local path and then perform aws package to package and deploy using scripts. 

Now the problem is that I can specify codeuri to be the top level folder if I hard code it but SAM is not letting me apply the value from a parameter (via !Ref or !Sub).

**Steps to reproduce the issue:**
In the example below, we have the code uri to be something similar:
https://github.com/awslabs/serverless-application-model/blob/master/HOWTO.md#packing-artifacts

but what we want is to have something like:

```
MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: !Ref CodePath
        ...
```

or

```
MyLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
        CodeUri: !Sub "./${CodePath}"
        ...
```

And then package and deploy the lambdas accordingly. We don't have a requirement to use s3 path directly.

**Observed result:**
Ref or Sub is not replacing the parameter even for non-s3 uploaded codeuri

**Expected result:**
Ref or Sub is allowed to substitute the string for local relative path.
