### ISSUE TITLE
Allow customize the CloudWatch scheduled name

### ISSUE THREAD

**Issue by hoang-innomizetech** [awslabs/serverless-application-model#934]
Currently, Schedule event type only supports two props, I think it would be better if we can control more props of the CloudWatch event likes below

```yaml
Type: Schedule
Properties:
    Name: scheduled name
    Description: description
    Enabled: true/false
    Schedule: rate(1 hour)
    Input: ''
```

We have faced an issue when updating the scheduled event on CloudWatch **RE: Member must have length less than or equal to 100.**
