### ISSUE TITLE
CodeUri doesn't handle local files in Globals section

### ISSUE THREAD

**Issue by watersofoblivion** [awslabs/serverless-application-model#944]
**Description:**

`CodeUri` property of `AWS::Serverless::Function` has inconsistent Global behavior when packaging.  When passed a local file in a Resource, it uploads the file.  When passed the same file in the Globals section, it ignores it and zips the current directory.

Related to #537.  That was closed with "Docs have been updated", but this behavior isn't documented that I can find.

**Steps to reproduce the issue:**

`works.yaml`:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: go1.x

Resources:
  Func:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: lambdas.zip
      Handler: main
```

`broken.yaml`:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: go1.x
    CodeUri: lambdas.zip

Resources:
  Func:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
```

Create a zip and package:

```bash
zip lambdas.zip *.yaml
aws cloudformation package --template-file works.yaml --s3-bucket MyBucket --output-template works-output.yaml
aws cloudformation package --template-file broken.yaml --s3-bucket MyBucket --output-template broken-output.yaml
```

**Observed result:**

The two outputs upload different MD5s:

`works-output.yaml`:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: go1.x
Resources:
  Func:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://MyBucket/b13bc5770ca867a3c231cd252dde7dc9
      Handler: main
```

`broken-output.yaml`:

```yaml
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Globals:
  Function:
    Runtime: go1.x
    CodeUri: lambdas.zip

Resources:
  Func:
    Type: AWS::Serverless::Function
    Properties:
      Handler: main
      CodeUri: s3://MyBucket/3ceb0ce77a33daef7c86fa1cee9e3867
```

Download and list the zips:

```bash
aws s3 cp s3://MyBucket/b13bc5770ca867a3c231cd252dde7dc9 works-lambdas.zip
aws s3 cp s3://MyBucket/3ceb0ce77a33daef7c86fa1cee9e3867 broken-lambdas.zip
```

`zipinfo works-lambdas.zip` returns:

```
Archive:  works-lambdas.zip
Zip file size: 653 bytes, number of entries: 2
-rw-r--r--  3.0 unx      233 tx defN 19-Jun-02 12:22 broken.yaml
-rw-r--r--  3.0 unx      235 tx defN 19-Jun-02 12:22 works.yaml
2 files, 468 bytes uncompressed, 333 bytes compressed:  28.8%
```

`zipinfo broken-lambdas.zip` returns:

```
Archive:  broken-lambdas.zip
Zip file size: 1456 bytes, number of entries: 4
-rw-r--r--  2.0 unx      653 b- defN 19-Jun-02 12:22 lambdas.zip
-rw-r--r--  2.0 unx      233 b- defN 19-Jun-02 12:22 broken.yaml
-rw-r--r--  2.0 unx      235 b- defN 19-Jun-02 12:22 works.yaml
-rw-r--r--  2.0 unx      276 b- defN 19-Jun-02 12:22 works-output.yaml
4 files, 1397 bytes uncompressed, 1032 bytes compressed:  26.1%
```

**Expected result:**

They should both upload the given file.
