### ISSUE TITLE
sam validate gives empty error

### ISSUE THREAD

**Issue by kay-is** [awslabs/serverless-application-model#952]
**Description:**

I created a SAM template and wanted to validate it, which led to an undefined error.

The question about what is wrong with the template is a general help question, but I still think that the validator shouldn't answer with empty error messages.

**Steps to reproduce the issue:**
1. Create `template.yaml`
2. Run `sam validate`

**Observed result:**

    2019-06-05 15:40:48 Found credentials in shared credentials file: ~/.aws/credentials
    Template provided at '/home/ec2-user/environment/serverless-api/template.yaml' was invalid SAM Template.
    Error:

**Expected result:**

Some error that tells me what I did wrong.

This was the template I created:

```yaml
AWSTemplateFormatVersion: "2010-09-09"
Transform: "AWS::Serverless-2016-10-31"
Description: "A example REST API build with serverless technology"

Globals:
  Function:
    Runtime: nodejs8.10
    Handler: index.handler
    Tags:
      Application: Serverless API
  
Resources:

  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Prod
      Cors: "'*'"
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt UserPool.Arn

  IndexFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/index/
      Events:
        Home:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: GET
            Auth:
              Authorizer: NONE

  ImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/images/
      Events:
        ListImages:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /images
            Method: GET
        DeleteImage:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /images/{imageId}
            Method: DELETE
        CreateImage:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /images
            Method: POST

  TagsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: functions/tags/
      Events:
        ListTags:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /tags
            Method: GET
        ListImages:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /tags/{tagId}/images
            Method: GET

  AuthFunction:
    Type: AWS::Serverless::Function
    Properties:
      Environment:
        Variables:
          USER_POOL_CLIENT_ID: !Ref UserPoolClient
      Events:
        Signup:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /signup
            Method: POST
            Auth:
              Authorizer: NONE
        Signin:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /signin
            Method: POST
            Auth:
              Authorizer: NONE

  PreSignupFunction:
    Type: AWS::Serverless::Function
    Properties:
      InlineCode: |
        exports.handler = async event => {
          event.response = { autoConfirmUser: true };
          return event;
        };

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: ApiUserPool
      LambdaConfig:
        PreSignUp: !GetAtt PreSignupFunction.Arn
      Policies:
        PasswordPolicy:
          MinimumLength: 6
      UsernameAttributes:
        - email
      Schema:
        - AttributeDataType: String
          Name: email
          Required: no
  
  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: ApiUserPoolClient
      GenerateSecret: no

  LambdaCognitoUserPoolExecutionPermission:
    Type: AWS::Lambda::Permission
    Properties: 
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt PreSignupFunction.Arn
      Principal: cognito-idp.amazonaws.com
      SourceArn: !Sub 'arn:${AWS::Partition}:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPool}'
```
