### ISSUE TITLE
Feature Request: Add Support for ParameterGroups/ParameterLabels

### ISSUE THREAD

**Issue by himanshu219** [awslabs/serverless-application-model#971]
*Description:**

Currently when one deploys the Serverless Application the UI does not support [ParameterGroups](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudformation-interface-parametergroup.html) and [ParameterLabels](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudformation-interface-parameterlabel.html)

Even though I added below snippet the screenshot shown below does not have any groups
```
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      -
        Label:
          default: "Sumo Logic Deployment Configuration"
        Parameters:
          - SumoDeployment
          - SumoAccessID
          - SumoAccessKey
      -
        Label:
          default: "Collection Configuration"
        Parameters:
          - CollectorName
          - SourceName
          - SourceCategoryName
          - RemoveSumoResourcesOnDeleteStack
    ParameterLabels:
      SumoDeployment:
        default: "Deployment Name"
      SumoAccessID:
        default: "Access ID"
      SumoAccessKey:
        default: "Access Key"
      CollectorName:
        default: "Collector Name"
      SourceName:
        default: "Source Name"
      SourceCategoryName:
        default: "Source Category Name"
      RemoveSumoResourcesOnDeleteStack:
        default: "Remove Sumo Resources On Delete Stack"
```

**Observed result:**
<img width="750" alt="Screen Shot 2019-06-12 at 6 55 57 PM" src="https://user-images.githubusercontent.com/3620468/59355262-541d2700-8d44-11e9-9e59-705276a7a2f9.png">

**Expected result:**
Ideally the groups should be similar to how Cloudformation shows in its UI as shown below 

<img width="706" alt="Screen Shot 2019-06-12 at 6 58 10 PM" src="https://user-images.githubusercontent.com/3620468/59355142-18825d00-8d44-11e9-8164-57bab5dc787f.png">
