### ISSUE TITLE
LayerVersion: unsupported properties ContentUri, RetentionPolicy

### ISSUE THREAD

**Issue by jfeltesse-mdsol** [awslabs/serverless-application-model#978]
**Description:**

I can't seem to be able to deploy the simplest ruby lambda layer. Both `sam validate` and `sam package` work but then it fails at the `sam deploy` stage. 

**Steps to reproduce the issue:**
Given the following file structure, template and existing S3 bucket

```
(top folder, running sam commands from here)
├── layer
│  └── (layer code in here)
└── templates
   └── sam_template.yaml

```

```yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  BaseRubyGemsLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: baseRubyGems
      ContentUri: ../layer
      RetentionPolicy: Delete
      CompatibleRuntimes:
        - ruby2.5
```

Running

```
sam package --template-file ./templates/sam_template.yaml --s3-bucket base-ruby-gems-dev --output-template-file ./templates/packaged.yaml

sam deploy --template-file ./templates/packaged.yaml --stack-name base-ruby-gems --capabilities CAPABILITY_IAM
```

**Observed result:**
```
"ResourceStatus": "CREATE_FAILED",
"ResourceStatusReason": "Property validation failure: [Encountered unsupported properties in {/}: [ContentUri, RetentionPolicy]]"
```

**Expected result:**
I should have the layer deployed and ready to use.

```
sam --version
SAM CLI, version 0.17.0
```
